{
  "hash": "c807ed5de82508ff35448d172b1346ef",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A3 - Tips Dataset\"\nauthor: \"Gayatri Jadhav\"\nprof: \"Arvind Venkatadri\"\n---\n\n\n\n## Introduction\n\nThis dataset looks at **tips** left by restaurant customers and includes details like their **gender** and whether they prefer **Veg** or **Non-Veg** food. It helps see if there are any patterns, like whether people who eat certain types of food tip more or if certain groups tend to give bigger tips.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Data Processing in R\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) # Our workhorse for stats, sampling\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntip <- read_csv(\"../../Data/tip.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 60 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Name, Gender, Preferance\ndbl (1): Tip\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(tip)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60\nColumns: 4\n$ Name       <chr> \"Aanya\", \"Adit\", \"Aditi\", \"Akash\", \"Akshita\", \"Anandita\", \"…\n$ Gender     <chr> \"Female\", \"Male\", \"Female\", \"Male\", \"Female\", \"Female\", \"Fe…\n$ Preferance <chr> \"Veg\", \"Veg\", \"Veg\", \"Non-veg\", \"Non-veg\", \"Non-veg\", \"Non-…\n$ Tip        <dbl> 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Crosstabulating the Tip variable against Preferance (categorical variable) to summarize the relationship\n# This helped me understand how tips are distributed across the two preferences (Veg/Non-veg)\n\ntip %>% \n  crosstable(Tip ~ Preferance) %>% \n  as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-b3229e66{table-layout:auto;}.cl-b3148718{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b3148736{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b31d34b2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b31d34bc{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b31d5956{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d5960{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d596a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d596b{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d5974{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b3229e66'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-b31d5956\"><p class=\"cl-b31d34b2\"><span class=\"cl-b3148718\">label</span></p></th><th  rowspan=\"2\"class=\"cl-b31d5956\"><p class=\"cl-b31d34b2\"><span class=\"cl-b3148718\">variable</span></p></th><th  colspan=\"2\"class=\"cl-b31d5960\"><p class=\"cl-b31d34b2\"><span class=\"cl-b3148718\">Preferance</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b31d596a\"><p class=\"cl-b31d34b2\"><span class=\"cl-b3148718\">Non-veg</span></p></th><th class=\"cl-b31d596a\"><p class=\"cl-b31d34b2\"><span class=\"cl-b3148718\">Veg</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-b31d596b\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">Tip</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">Min / Max</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">0 / 50.0</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">0 / 100.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">Med [IQR]</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">0 [0;20.0]</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">0 [0;20.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">Mean (std)</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">10.0 (12.9)</span></p></td><td class=\"cl-b31d5974\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">12.3 (21.9)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b31d596b\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">N (NA)</span></p></td><td class=\"cl-b31d596b\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">30 (0)</span></p></td><td class=\"cl-b31d596b\"><p class=\"cl-b31d34bc\"><span class=\"cl-b3148736\">30 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mutating by converting Gender and Preferance into factors\n\ntips_modified <- tip %>%\n  dplyr::mutate(\n  Gender = as_factor(Gender),\n  Preferance = as_factor(Preferance)\n  )\nglimpse(tips_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60\nColumns: 4\n$ Name       <chr> \"Aanya\", \"Adit\", \"Aditi\", \"Akash\", \"Akshita\", \"Anandita\", \"…\n$ Gender     <fct> Female, Male, Female, Male, Female, Female, Female, Female,…\n$ Preferance <fct> Veg, Veg, Veg, Non-veg, Non-veg, Non-veg, Non-veg, Veg, Veg…\n$ Tip        <dbl> 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a histogram to see the distribution of Tips by Preferance\ntips_modified %>%\n  gf_histogram(~Tip|Preferance, fill = ~Preferance,position= \"dodge\" ,data = tips_modified) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nVeg <- tips_modified %>% \n  filter(Preferance == \"Veg\") %>% \n  select(Tip)\n\nNonveg <- tips_modified %>% \n  filter(Preferance == \"Non-veg\") %>% \n  select(Tip)\n\nshapiro.test(Veg$Tip) # Performing the Shapiro-Wilk test for normality on the \"Veg\" group's Tip values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Veg$Tip\nW = 0.6286, p-value = 1.661e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(Nonveg$Tip)# Performing the Shapiro-Wilk test for normality on the \"Non-veg\" group's Tip values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  Nonveg$Tip\nW = 0.71661, p-value = 2.747e-06\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nThe p-values are extremely small, indicating that neither the Veg nor the Non-veg Tip data is normally distributed.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::t_test( Tip ~ Preferance, data = tips_modified ) %>% \n\n  broom::tidy() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1     2.33      12.3        10     0.503   0.617      46.9    -6.99      11.7\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nSince neither the Veg nor Non-veg Tip data is normally distributed, using a t-test wouldn't be the right choice. Instead, it's better to use the **Wilcoxon test**, which is a non-parametric method that's ideal for comparing the medians when the data isn’t normally distributed.\n:::\n\nSplitting the dataset by Preferance into Veg and Nonveg groups-\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Selecting only the Tip column for further testing\ntips_modified %>% \n  filter(Preferance == \"Veg\") %>% \n  select(Tip) -> Veg\n\n# Checking the \"Veg\" group Tip values\nVeg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 1\n     Tip\n   <dbl>\n 1     0\n 2     0\n 3    20\n 4    35\n 5    40\n 6     0\n 7     0\n 8     0\n 9    15\n10   100\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Extracting the Tip values for the \"Non-veg\" group\ntips_modified %>% \n  filter(Preferance == \"Non-veg\") %>% \n  select(Tip) -> Nonveg\n\n# Checking the \"Non-veg\" group Tip values\nNonveg \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 1\n     Tip\n   <dbl>\n 1     0\n 2     0\n 3     0\n 4    20\n 5     0\n 6     0\n 7     0\n 8     0\n 9     0\n10    20\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(Tip ~ Preferance , data = tips_modified) %>% \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic p.value method                                           alternative\n      <dbl>   <dbl> <chr>                                            <chr>      \n1       437   0.833 Wilcoxon rank sum test with continuity correcti… two.sided  \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nThe Wilcoxon test gave a result of 437 for the statistic and a **p-value of 0.83**. This high p-value means there’s no significant difference between the tips left by the Veg and Non-veg groups. IBoth groups leave about the same amount in tips.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_diff_tip <- diffmean( Tip ~ Preferance, data = tips_modified) \nobs_diff_tip\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n diffmean \n-2.333333 \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nThe **diffmean** result is **-2.33**, which means that, on average, the Non-veg group left 2.33 less in tips than the Veg group. But because the Wilcoxon test has not showed any significant difference, this small difference doesn’t actually matter much.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generating a null distribution for the difference in means through permutation testing (5000 permutations)\nnull_dist_tip <- \n  do(4999) * diffmean(data = tips_modified, Tip ~ shuffle(Preferance))\nnull_dist_tip\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        diffmean\n1     -1.6666667\n2    -10.3333333\n3     -8.3333333\n4      3.0000000\n5      2.0000000\n6      1.3333333\n7      7.0000000\n8      7.3333333\n9     -2.6666667\n10    -1.3333333\n11    -4.0000000\n12    -5.6666667\n13     0.0000000\n14     5.6666667\n15    -1.3333333\n16    -1.3333333\n17     4.3333333\n18     6.3333333\n19     3.3333333\n20     2.3333333\n21    -0.6666667\n22    -3.0000000\n23    -7.3333333\n24    -6.0000000\n25    -1.3333333\n26    -4.3333333\n27     1.3333333\n28    -2.6666667\n29    -2.0000000\n30    -1.6666667\n31     0.0000000\n32     2.0000000\n33    -1.0000000\n34   -10.3333333\n35    -2.0000000\n36    -3.0000000\n37     0.6666667\n38    -3.3333333\n39    -6.6666667\n40    -4.3333333\n41     6.6666667\n42    -3.3333333\n43     0.6666667\n44     5.3333333\n45     0.6666667\n46     4.6666667\n47    -5.6666667\n48     5.3333333\n49     4.3333333\n50     6.3333333\n51     2.0000000\n52    11.0000000\n53     3.3333333\n54     1.3333333\n55    -3.0000000\n56    -5.6666667\n57    -5.3333333\n58    -0.3333333\n59     5.0000000\n60     3.0000000\n61    -0.6666667\n62    -3.3333333\n63     0.6666667\n64    -5.0000000\n65     5.0000000\n66     7.0000000\n67    -2.0000000\n68    -2.6666667\n69     3.0000000\n70     3.6666667\n71    -5.3333333\n72     0.3333333\n73    -1.6666667\n74     0.3333333\n75     7.0000000\n76    -0.6666667\n77     2.0000000\n78     0.3333333\n79     1.6666667\n80     1.6666667\n81    -5.6666667\n82     5.3333333\n83    -0.3333333\n84     2.6666667\n85     1.6666667\n86    -3.0000000\n87    -4.0000000\n88    -2.3333333\n89     6.0000000\n90    -3.3333333\n91     4.0000000\n92    -3.0000000\n93    -1.3333333\n94     6.3333333\n95    -1.6666667\n96     3.3333333\n97     9.6666667\n98     1.3333333\n99    -5.6666667\n100    3.3333333\n101    0.0000000\n102    7.3333333\n103    3.0000000\n104   -0.3333333\n105   -4.3333333\n106    1.6666667\n107   -4.6666667\n108    4.3333333\n109    3.3333333\n110    4.3333333\n111    2.6666667\n112   -2.0000000\n113   -0.3333333\n114    6.0000000\n115   -5.6666667\n116   -5.3333333\n117   -6.0000000\n118    3.6666667\n119   -0.6666667\n120    0.0000000\n121    3.0000000\n122    2.3333333\n123   -3.6666667\n124    0.6666667\n125   -2.6666667\n126    2.6666667\n127    3.3333333\n128    9.6666667\n129   -0.6666667\n130    7.3333333\n131    5.3333333\n132   -3.6666667\n133   -0.3333333\n134    4.0000000\n135   -5.6666667\n136   10.0000000\n137   -8.3333333\n138   -1.0000000\n139   -2.0000000\n140    1.3333333\n141    6.3333333\n142   -5.0000000\n143    2.6666667\n144   -4.6666667\n145    2.6666667\n146   -5.3333333\n147    5.6666667\n148    3.0000000\n149   -0.3333333\n150    8.0000000\n151   -3.6666667\n152   -7.0000000\n153    1.0000000\n154   -5.0000000\n155  -10.6666667\n156    5.3333333\n157    7.6666667\n158   -8.0000000\n159    3.6666667\n160   -0.3333333\n161   -3.3333333\n162   -0.3333333\n163   -4.0000000\n164   -4.6666667\n165    1.6666667\n166    2.6666667\n167    0.6666667\n168   -5.6666667\n169    6.3333333\n170   -5.6666667\n171    1.6666667\n172  -10.0000000\n173    7.3333333\n174   -3.3333333\n175    4.3333333\n176   -1.0000000\n177    5.6666667\n178   -7.0000000\n179    8.6666667\n180   -2.6666667\n181    7.0000000\n182   -7.3333333\n183    5.3333333\n184    1.6666667\n185   -8.6666667\n186    1.0000000\n187    4.0000000\n188    7.3333333\n189    2.0000000\n190    6.0000000\n191    1.3333333\n192    5.6666667\n193   -3.3333333\n194   -1.6666667\n195   -6.0000000\n196   -4.6666667\n197    4.3333333\n198   -5.0000000\n199    3.0000000\n200    3.3333333\n201   -0.3333333\n202    4.3333333\n203   -3.0000000\n204   -3.0000000\n205   -4.6666667\n206   -1.0000000\n207    2.0000000\n208   -1.6666667\n209   -5.0000000\n210   -0.3333333\n211    1.6666667\n212    1.6666667\n213   -8.3333333\n214   -1.3333333\n215   -3.3333333\n216   -2.3333333\n217    3.0000000\n218    4.0000000\n219    0.3333333\n220   -4.0000000\n221   -0.6666667\n222    7.6666667\n223   -1.0000000\n224   -5.6666667\n225    6.0000000\n226   -4.0000000\n227   -1.0000000\n228    2.3333333\n229   -5.3333333\n230    7.0000000\n231   -0.3333333\n232   -1.0000000\n233    1.0000000\n234   -6.6666667\n235    2.6666667\n236    1.0000000\n237    0.0000000\n238   -3.0000000\n239   -7.0000000\n240   -1.0000000\n241    5.6666667\n242   -1.6666667\n243    9.3333333\n244    1.3333333\n245   -2.3333333\n246    1.6666667\n247   -5.0000000\n248   -0.6666667\n249   -3.0000000\n250   12.3333333\n251   -1.3333333\n252    6.3333333\n253    1.3333333\n254    2.0000000\n255    3.3333333\n256    0.3333333\n257    3.6666667\n258   -6.0000000\n259    1.3333333\n260    7.6666667\n261    6.6666667\n262   -4.0000000\n263    5.6666667\n264   -4.0000000\n265    4.3333333\n266    4.3333333\n267   -8.6666667\n268   -5.3333333\n269   -2.6666667\n270   -3.6666667\n271    8.6666667\n272   -7.0000000\n273   11.3333333\n274    4.0000000\n275   -3.0000000\n276   -5.0000000\n277   -7.6666667\n278    3.0000000\n279   -5.0000000\n280    0.3333333\n281   -5.3333333\n282   -1.6666667\n283    5.3333333\n284    5.0000000\n285   -7.3333333\n286    5.3333333\n287    3.6666667\n288    0.3333333\n289    5.3333333\n290   -7.6666667\n291    1.6666667\n292   -1.3333333\n293    9.3333333\n294   -0.3333333\n295   -2.0000000\n296   -2.3333333\n297    2.6666667\n298    5.6666667\n299   -6.0000000\n300    0.6666667\n301   -4.3333333\n302   -3.3333333\n303    5.3333333\n304    0.0000000\n305   -1.0000000\n306    5.3333333\n307    4.6666667\n308    2.6666667\n309    4.0000000\n310    5.6666667\n311   -0.6666667\n312   -3.0000000\n313    3.3333333\n314    2.3333333\n315   -6.6666667\n316   -5.0000000\n317    4.3333333\n318    5.0000000\n319   -1.6666667\n320   -2.3333333\n321   -1.0000000\n322    5.3333333\n323   -3.0000000\n324   -6.3333333\n325    1.6666667\n326   -2.0000000\n327    0.3333333\n328    2.0000000\n329   -5.6666667\n330   -7.6666667\n331    0.3333333\n332    9.3333333\n333   -4.0000000\n334    7.6666667\n335    8.0000000\n336   -9.6666667\n337    6.6666667\n338    8.0000000\n339    0.0000000\n340   -7.0000000\n341   -0.3333333\n342   -1.6666667\n343   -6.0000000\n344    4.6666667\n345    4.6666667\n346   -8.6666667\n347    8.0000000\n348   -8.3333333\n349   -3.6666667\n350    0.3333333\n351    1.0000000\n352    0.3333333\n353    0.0000000\n354    3.3333333\n355   -0.3333333\n356   -4.6666667\n357    6.3333333\n358   -3.3333333\n359   -5.6666667\n360    3.0000000\n361   -4.0000000\n362    2.6666667\n363   -8.3333333\n364    8.0000000\n365   -1.3333333\n366    4.6666667\n367    7.3333333\n368   -1.3333333\n369    4.3333333\n370    0.6666667\n371   -2.3333333\n372    2.0000000\n373    3.0000000\n374    9.6666667\n375   -6.3333333\n376   -7.0000000\n377   -4.0000000\n378   -2.3333333\n379    9.0000000\n380   -1.0000000\n381   -5.0000000\n382   -9.3333333\n383   -3.6666667\n384   -2.3333333\n385    0.0000000\n386   -4.0000000\n387   -8.3333333\n388    1.6666667\n389    6.0000000\n390   -2.6666667\n391    3.6666667\n392    7.3333333\n393   -2.0000000\n394   -5.3333333\n395    1.0000000\n396    6.3333333\n397    4.3333333\n398   -2.6666667\n399   -5.0000000\n400    6.3333333\n401    1.3333333\n402   -4.0000000\n403    7.0000000\n404   -0.6666667\n405    2.3333333\n406    4.3333333\n407    4.6666667\n408    2.3333333\n409    3.0000000\n410   -5.0000000\n411    3.3333333\n412   -3.0000000\n413    0.6666667\n414    3.0000000\n415    2.0000000\n416    0.3333333\n417   -5.0000000\n418   -4.0000000\n419    0.0000000\n420    7.3333333\n421   -0.3333333\n422    0.0000000\n423    4.0000000\n424    0.0000000\n425   -0.6666667\n426  -10.0000000\n427    0.0000000\n428    7.6666667\n429    8.3333333\n430   -5.3333333\n431   -7.3333333\n432    3.0000000\n433    6.6666667\n434    0.0000000\n435    0.3333333\n436    9.3333333\n437   -5.0000000\n438   -7.6666667\n439   -4.3333333\n440   -4.6666667\n441    1.3333333\n442   -4.0000000\n443    7.6666667\n444    3.6666667\n445    5.3333333\n446    9.3333333\n447    5.3333333\n448   -2.3333333\n449   -4.3333333\n450   -1.3333333\n451   -9.6666667\n452    2.6666667\n453   -7.6666667\n454    5.0000000\n455   -4.0000000\n456   -6.0000000\n457    3.0000000\n458    2.3333333\n459    1.6666667\n460    7.3333333\n461    2.6666667\n462    5.6666667\n463   -1.0000000\n464    5.0000000\n465    2.3333333\n466    9.0000000\n467   -0.6666667\n468    0.3333333\n469   -6.0000000\n470    6.6666667\n471    3.6666667\n472    2.6666667\n473   -8.3333333\n474    0.3333333\n475    4.3333333\n476   -5.6666667\n477   -8.6666667\n478    2.0000000\n479    3.0000000\n480    0.3333333\n481    3.6666667\n482   -5.6666667\n483   -3.3333333\n484   -6.0000000\n485    1.3333333\n486   -2.3333333\n487   -8.0000000\n488   -3.0000000\n489   -1.0000000\n490   -1.3333333\n491    1.6666667\n492   -3.6666667\n493  -10.0000000\n494    1.0000000\n495    1.3333333\n496    7.3333333\n497   -1.0000000\n498   -6.0000000\n499    2.6666667\n500   -4.0000000\n501    3.6666667\n502   10.3333333\n503   -1.3333333\n504    3.3333333\n505   -1.3333333\n506    1.6666667\n507    0.0000000\n508    0.0000000\n509   -6.3333333\n510   -2.0000000\n511  -11.0000000\n512    2.0000000\n513   -2.3333333\n514    8.3333333\n515    1.6666667\n516    2.6666667\n517   -1.3333333\n518   -0.3333333\n519   -5.3333333\n520    0.0000000\n521    2.0000000\n522    6.6666667\n523    3.3333333\n524    1.6666667\n525   -0.6666667\n526   -1.0000000\n527    6.3333333\n528    2.0000000\n529    4.0000000\n530   -7.0000000\n531    3.6666667\n532   -7.0000000\n533    3.3333333\n534   -2.3333333\n535   -0.3333333\n536   -0.3333333\n537    2.6666667\n538    2.6666667\n539   -9.6666667\n540    0.3333333\n541   -1.3333333\n542   -4.3333333\n543    1.0000000\n544    1.6666667\n545   -2.3333333\n546    4.6666667\n547   -6.3333333\n548    2.0000000\n549   -2.0000000\n550   -2.0000000\n551    1.6666667\n552    3.0000000\n553    4.0000000\n554    1.6666667\n555    0.3333333\n556    2.3333333\n557   -1.3333333\n558   -5.3333333\n559   -5.0000000\n560    3.0000000\n561    1.0000000\n562    4.3333333\n563   -2.0000000\n564    0.3333333\n565    0.3333333\n566   -1.6666667\n567   -1.6666667\n568   -6.3333333\n569   -8.0000000\n570    3.3333333\n571    5.0000000\n572    2.0000000\n573    0.3333333\n574    3.6666667\n575    4.6666667\n576   -2.3333333\n577    0.3333333\n578   -4.6666667\n579   -4.6666667\n580    4.3333333\n581    5.0000000\n582    1.3333333\n583    7.0000000\n584   -3.0000000\n585   -8.6666667\n586   -1.3333333\n587   -4.0000000\n588    1.3333333\n589    0.6666667\n590   -4.6666667\n591   -4.6666667\n592   -0.3333333\n593    2.6666667\n594    4.6666667\n595    1.0000000\n596   -5.3333333\n597   -6.6666667\n598   -3.6666667\n599    6.6666667\n600   -3.0000000\n601    4.3333333\n602    3.0000000\n603   -4.6666667\n604    1.3333333\n605    2.6666667\n606    0.3333333\n607   -8.0000000\n608    3.0000000\n609   -3.3333333\n610    2.6666667\n611   -5.0000000\n612   -4.0000000\n613   -2.6666667\n614   -1.0000000\n615    2.3333333\n616    3.3333333\n617   -4.0000000\n618  -12.0000000\n619   -4.3333333\n620   -2.6666667\n621    0.0000000\n622   -1.0000000\n623    1.6666667\n624    3.0000000\n625   -3.3333333\n626    1.0000000\n627    1.6666667\n628    8.0000000\n629    5.0000000\n630    7.0000000\n631    5.6666667\n632    6.0000000\n633   -9.6666667\n634   -4.6666667\n635    0.0000000\n636   -1.3333333\n637    1.6666667\n638    1.6666667\n639   -3.0000000\n640    1.3333333\n641   -2.0000000\n642   -5.0000000\n643   -1.3333333\n644   -5.0000000\n645    0.6666667\n646    2.6666667\n647   -1.0000000\n648    2.0000000\n649   -1.6666667\n650   -5.3333333\n651   -0.6666667\n652    3.6666667\n653    2.0000000\n654    7.6666667\n655   -3.0000000\n656   -0.3333333\n657    6.0000000\n658   -3.3333333\n659    0.6666667\n660   -3.0000000\n661    3.3333333\n662   -0.6666667\n663   -3.0000000\n664    0.3333333\n665    3.3333333\n666   -0.3333333\n667   -3.6666667\n668    5.6666667\n669   -2.0000000\n670   -4.0000000\n671   -6.6666667\n672    4.3333333\n673   -3.0000000\n674   -1.3333333\n675    0.3333333\n676   -6.0000000\n677    0.0000000\n678    6.0000000\n679   -2.6666667\n680    1.0000000\n681    2.6666667\n682    3.0000000\n683   -6.0000000\n684    3.3333333\n685    1.6666667\n686   -2.3333333\n687   -4.6666667\n688    3.0000000\n689    6.0000000\n690   -1.0000000\n691   -1.3333333\n692   10.6666667\n693    0.6666667\n694    0.3333333\n695    4.6666667\n696   -5.0000000\n697    0.0000000\n698    3.3333333\n699   -2.6666667\n700    2.6666667\n701   -4.3333333\n702    4.6666667\n703    4.3333333\n704   -1.3333333\n705    4.3333333\n706    1.0000000\n707   -0.3333333\n708    0.0000000\n709    6.0000000\n710   -4.3333333\n711    0.0000000\n712    5.3333333\n713   -0.3333333\n714   -4.6666667\n715   -1.6666667\n716   -4.3333333\n717   -2.3333333\n718    2.0000000\n719   -2.6666667\n720  -11.6666667\n721    3.0000000\n722   -1.6666667\n723   -1.6666667\n724   -0.6666667\n725    6.3333333\n726   -5.3333333\n727    4.6666667\n728   -0.3333333\n729    8.3333333\n730    5.3333333\n731   -1.6666667\n732    3.3333333\n733   -4.0000000\n734   -5.0000000\n735    5.3333333\n736    5.0000000\n737    3.0000000\n738    2.3333333\n739   -0.6666667\n740    9.6666667\n741    0.3333333\n742   -3.6666667\n743   -1.6666667\n744   -3.6666667\n745   -8.6666667\n746    0.3333333\n747    1.6666667\n748   -0.6666667\n749   -1.0000000\n750   -7.0000000\n751   -7.0000000\n752   -1.3333333\n753   -7.3333333\n754    2.3333333\n755    6.6666667\n756   -2.3333333\n757    0.6666667\n758    1.6666667\n759   -4.3333333\n760   10.0000000\n761   -5.3333333\n762    2.6666667\n763   -8.0000000\n764    1.6666667\n765    5.6666667\n766   -0.6666667\n767    8.3333333\n768  -10.0000000\n769    1.6666667\n770    0.6666667\n771    0.0000000\n772   -2.0000000\n773   -3.0000000\n774    6.0000000\n775   -2.3333333\n776    3.6666667\n777   -4.3333333\n778    4.0000000\n779   -3.0000000\n780   -3.3333333\n781   -2.0000000\n782   -8.6666667\n783    3.6666667\n784    3.3333333\n785   -3.0000000\n786    5.3333333\n787   -0.6666667\n788    2.0000000\n789    1.3333333\n790    6.0000000\n791    3.6666667\n792   -2.6666667\n793   -0.6666667\n794   -2.6666667\n795    1.6666667\n796    4.6666667\n797   -1.6666667\n798   10.0000000\n799   -1.3333333\n800    4.3333333\n801   -1.6666667\n802    4.6666667\n803    8.6666667\n804   -7.6666667\n805    6.3333333\n806   -4.6666667\n807    6.3333333\n808    2.6666667\n809    4.0000000\n810   -1.6666667\n811   -4.6666667\n812    3.6666667\n813    1.0000000\n814    2.6666667\n815    1.6666667\n816   -1.0000000\n817   -3.3333333\n818    6.6666667\n819    3.3333333\n820    3.3333333\n821   -3.6666667\n822    1.0000000\n823   -1.3333333\n824    2.3333333\n825    2.0000000\n826    0.3333333\n827   10.0000000\n828    0.6666667\n829    5.3333333\n830    3.3333333\n831   -1.3333333\n832   -4.3333333\n833   -4.3333333\n834   -3.3333333\n835    7.0000000\n836    9.0000000\n837    2.6666667\n838   -0.3333333\n839    6.0000000\n840   -2.0000000\n841   -1.0000000\n842    1.0000000\n843    3.6666667\n844   -7.3333333\n845   -2.3333333\n846    1.0000000\n847   -3.0000000\n848   -3.3333333\n849   -2.0000000\n850    2.6666667\n851   -5.0000000\n852   -2.0000000\n853    7.3333333\n854    4.6666667\n855   -3.0000000\n856   -3.6666667\n857    6.3333333\n858    6.3333333\n859    6.6666667\n860   -1.6666667\n861    6.3333333\n862   -4.0000000\n863    0.0000000\n864    6.6666667\n865    4.0000000\n866    4.6666667\n867    8.6666667\n868   -1.0000000\n869    2.6666667\n870    8.0000000\n871   -1.6666667\n872   -4.3333333\n873   -8.6666667\n874   -6.0000000\n875    6.3333333\n876    1.6666667\n877   -2.0000000\n878    2.0000000\n879    3.0000000\n880   -8.0000000\n881    6.3333333\n882    4.0000000\n883   -5.0000000\n884   -3.0000000\n885    4.0000000\n886    7.0000000\n887    1.3333333\n888    2.6666667\n889   -4.0000000\n890   -0.3333333\n891   -3.6666667\n892   -0.3333333\n893   -2.6666667\n894   -3.3333333\n895    3.0000000\n896    7.0000000\n897    7.6666667\n898   -1.0000000\n899    6.0000000\n900    3.3333333\n901   -6.0000000\n902   -0.3333333\n903    2.6666667\n904   -0.6666667\n905    0.6666667\n906   -8.3333333\n907    4.0000000\n908    7.0000000\n909   -4.0000000\n910    0.0000000\n911   -3.3333333\n912   -4.3333333\n913   -2.6666667\n914   -3.3333333\n915   -3.3333333\n916    3.3333333\n917    2.3333333\n918   -1.0000000\n919    1.6666667\n920    5.0000000\n921   -2.6666667\n922   11.6666667\n923   -2.6666667\n924    3.0000000\n925   -4.0000000\n926    1.3333333\n927   -3.0000000\n928   -1.0000000\n929   -1.3333333\n930    1.6666667\n931    1.6666667\n932    5.3333333\n933    3.3333333\n934    4.3333333\n935    8.6666667\n936    9.0000000\n937    4.3333333\n938    8.6666667\n939    1.0000000\n940    2.6666667\n941   -1.0000000\n942    3.6666667\n943    0.3333333\n944    6.6666667\n945   -6.3333333\n946   -0.6666667\n947   -3.0000000\n948   -4.6666667\n949    1.3333333\n950    0.0000000\n951    7.0000000\n952   -5.6666667\n953    8.3333333\n954   -2.6666667\n955    6.6666667\n956   -8.3333333\n957    1.3333333\n958   -1.3333333\n959   -3.6666667\n960    3.6666667\n961    8.3333333\n962    3.6666667\n963   -3.6666667\n964    3.0000000\n965    5.3333333\n966    1.3333333\n967   -5.3333333\n968    9.3333333\n969    2.3333333\n970   -0.6666667\n971    1.6666667\n972  -11.0000000\n973   -2.6666667\n974   -3.6666667\n975   -7.0000000\n976   -6.0000000\n977    6.6666667\n978    0.6666667\n979   -3.0000000\n980    1.3333333\n981    2.0000000\n982   -3.6666667\n983    8.0000000\n984   -2.3333333\n985   -4.6666667\n986    3.0000000\n987    6.6666667\n988   -4.0000000\n989    3.6666667\n990    4.6666667\n991    5.0000000\n992    4.6666667\n993    8.6666667\n994    5.3333333\n995   -1.6666667\n996    6.0000000\n997    1.3333333\n998   -1.3333333\n999   -3.3333333\n1000  -0.3333333\n1001  -4.0000000\n1002  -2.6666667\n1003   4.6666667\n1004  -1.0000000\n1005   3.0000000\n1006  -4.0000000\n1007  -8.3333333\n1008   6.6666667\n1009  -1.3333333\n1010   6.3333333\n1011   4.0000000\n1012   5.0000000\n1013   6.6666667\n1014   5.3333333\n1015   1.6666667\n1016   0.0000000\n1017   1.3333333\n1018   2.0000000\n1019   1.3333333\n1020  -1.0000000\n1021   5.3333333\n1022  -0.3333333\n1023   4.3333333\n1024  -0.6666667\n1025  -7.0000000\n1026   0.3333333\n1027  -5.3333333\n1028  -2.6666667\n1029  -4.0000000\n1030  -5.0000000\n1031   4.0000000\n1032   4.6666667\n1033   0.0000000\n1034  -3.6666667\n1035  -3.0000000\n1036   5.3333333\n1037  -2.0000000\n1038   2.0000000\n1039  -1.0000000\n1040  -0.6666667\n1041   1.6666667\n1042  -2.0000000\n1043  -2.6666667\n1044  -3.0000000\n1045  -1.0000000\n1046   4.0000000\n1047   0.3333333\n1048   3.6666667\n1049  -3.0000000\n1050  -3.0000000\n1051   1.0000000\n1052  -1.0000000\n1053   2.3333333\n1054   5.6666667\n1055   1.3333333\n1056  -8.3333333\n1057   0.3333333\n1058   7.3333333\n1059  -1.6666667\n1060   0.6666667\n1061  -6.3333333\n1062  -4.3333333\n1063  -2.3333333\n1064   8.3333333\n1065   5.0000000\n1066  -5.6666667\n1067  -2.6666667\n1068   5.3333333\n1069   0.6666667\n1070   8.6666667\n1071   6.6666667\n1072   2.0000000\n1073   9.0000000\n1074   4.3333333\n1075   4.3333333\n1076  -1.0000000\n1077   3.3333333\n1078   0.6666667\n1079  -7.0000000\n1080   1.0000000\n1081   6.0000000\n1082  -4.3333333\n1083   1.6666667\n1084  -1.0000000\n1085   0.6666667\n1086   3.3333333\n1087   7.6666667\n1088   8.6666667\n1089   1.0000000\n1090   1.3333333\n1091  -0.6666667\n1092  -1.0000000\n1093  -5.6666667\n1094   5.3333333\n1095  -3.0000000\n1096   2.3333333\n1097   1.3333333\n1098  -3.0000000\n1099  -0.6666667\n1100  -6.0000000\n1101   3.0000000\n1102   4.3333333\n1103  -0.3333333\n1104  -1.6666667\n1105  -5.0000000\n1106  -2.0000000\n1107   1.6666667\n1108   4.6666667\n1109   0.0000000\n1110  -4.0000000\n1111  -1.3333333\n1112   1.6666667\n1113   2.6666667\n1114   2.3333333\n1115   2.0000000\n1116  -5.6666667\n1117   8.0000000\n1118   1.0000000\n1119   0.6666667\n1120  -3.0000000\n1121  -7.0000000\n1122  -3.0000000\n1123   3.3333333\n1124   4.3333333\n1125   4.6666667\n1126  -0.6666667\n1127  -7.3333333\n1128   4.0000000\n1129  -6.0000000\n1130   0.3333333\n1131  -3.0000000\n1132  15.0000000\n1133  -1.6666667\n1134  -5.6666667\n1135  -1.6666667\n1136   0.6666667\n1137  -2.3333333\n1138  -4.6666667\n1139  11.0000000\n1140   0.0000000\n1141   2.0000000\n1142   6.3333333\n1143  -3.0000000\n1144  -4.3333333\n1145  -5.3333333\n1146   6.0000000\n1147   5.3333333\n1148  -4.0000000\n1149   1.3333333\n1150  -3.6666667\n1151   4.0000000\n1152  -2.3333333\n1153  -1.0000000\n1154   5.0000000\n1155   5.6666667\n1156  -0.3333333\n1157  -8.3333333\n1158  -1.3333333\n1159   2.6666667\n1160   2.3333333\n1161  -6.6666667\n1162  -3.3333333\n1163  -4.3333333\n1164   0.6666667\n1165   4.0000000\n1166   5.3333333\n1167  -2.3333333\n1168   8.3333333\n1169   7.6666667\n1170   0.0000000\n1171  -4.0000000\n1172   2.0000000\n1173  -1.0000000\n1174  -1.0000000\n1175   8.3333333\n1176   0.0000000\n1177  -1.6666667\n1178  -1.6666667\n1179  -4.6666667\n1180   3.3333333\n1181   0.3333333\n1182   4.0000000\n1183  -7.0000000\n1184  -5.0000000\n1185   5.3333333\n1186   5.0000000\n1187   5.0000000\n1188  -7.6666667\n1189   0.3333333\n1190  -2.3333333\n1191   3.3333333\n1192  -1.0000000\n1193   0.0000000\n1194   1.0000000\n1195   6.6666667\n1196  -3.6666667\n1197   4.3333333\n1198   4.6666667\n1199   8.3333333\n1200   3.3333333\n1201  -1.6666667\n1202   1.6666667\n1203   0.6666667\n1204   4.6666667\n1205   1.0000000\n1206  -5.3333333\n1207   4.0000000\n1208  -1.0000000\n1209  -4.0000000\n1210   6.3333333\n1211  -6.6666667\n1212  -5.0000000\n1213   1.3333333\n1214   3.0000000\n1215   0.6666667\n1216   7.3333333\n1217  -3.0000000\n1218   6.3333333\n1219  -9.0000000\n1220  -1.0000000\n1221  -5.0000000\n1222  -8.0000000\n1223   6.6666667\n1224   4.3333333\n1225   7.3333333\n1226   7.6666667\n1227   4.6666667\n1228  -3.0000000\n1229  -0.3333333\n1230  -0.6666667\n1231 -10.0000000\n1232  -2.0000000\n1233   0.6666667\n1234  -6.3333333\n1235   6.0000000\n1236  -3.3333333\n1237  -3.0000000\n1238   4.0000000\n1239   2.6666667\n1240  -2.0000000\n1241   6.0000000\n1242   1.6666667\n1243  -2.3333333\n1244   2.0000000\n1245  -0.6666667\n1246   7.3333333\n1247  -2.6666667\n1248  -0.6666667\n1249   1.3333333\n1250   3.3333333\n1251   6.0000000\n1252   2.6666667\n1253   1.3333333\n1254   6.6666667\n1255  -8.6666667\n1256  -3.3333333\n1257  -4.0000000\n1258  -2.6666667\n1259  -3.0000000\n1260   2.0000000\n1261  -0.3333333\n1262  -5.0000000\n1263  -7.6666667\n1264  -0.3333333\n1265  -9.0000000\n1266   1.3333333\n1267  -2.6666667\n1268   2.0000000\n1269   5.3333333\n1270   5.3333333\n1271  -5.0000000\n1272   4.0000000\n1273   2.0000000\n1274  -1.3333333\n1275  -5.3333333\n1276  -0.6666667\n1277   6.3333333\n1278  -0.6666667\n1279  -4.3333333\n1280   3.6666667\n1281   0.0000000\n1282   0.3333333\n1283  -2.3333333\n1284   4.3333333\n1285  -9.0000000\n1286   5.6666667\n1287   2.3333333\n1288  -0.3333333\n1289   4.3333333\n1290  -1.6666667\n1291   4.0000000\n1292  -2.6666667\n1293  -3.0000000\n1294  -3.0000000\n1295   3.0000000\n1296  -4.0000000\n1297   0.6666667\n1298   4.6666667\n1299   4.6666667\n1300   9.3333333\n1301  -6.6666667\n1302   4.3333333\n1303  -6.0000000\n1304  -0.6666667\n1305  -0.3333333\n1306   3.0000000\n1307  -2.6666667\n1308   5.3333333\n1309  -0.3333333\n1310  -9.3333333\n1311  -2.0000000\n1312   3.6666667\n1313   2.0000000\n1314  -1.0000000\n1315  -0.6666667\n1316  -6.3333333\n1317   0.0000000\n1318  -6.3333333\n1319  -8.6666667\n1320   5.0000000\n1321  -7.3333333\n1322   6.3333333\n1323  -5.3333333\n1324   3.3333333\n1325  -3.0000000\n1326   0.0000000\n1327   4.0000000\n1328  -4.6666667\n1329 -10.0000000\n1330   7.3333333\n1331   4.0000000\n1332   1.6666667\n1333   0.6666667\n1334   2.3333333\n1335   3.3333333\n1336  -5.3333333\n1337   0.0000000\n1338  -5.3333333\n1339   5.0000000\n1340   1.0000000\n1341  -4.0000000\n1342   7.3333333\n1343   2.6666667\n1344  -3.0000000\n1345  -4.0000000\n1346  -9.3333333\n1347  -1.6666667\n1348  -3.0000000\n1349   2.6666667\n1350  -0.6666667\n1351   5.6666667\n1352   8.0000000\n1353   4.3333333\n1354   1.0000000\n1355  -0.3333333\n1356  -5.3333333\n1357  -3.3333333\n1358   1.0000000\n1359   0.3333333\n1360   1.3333333\n1361  -9.3333333\n1362   6.0000000\n1363 -10.6666667\n1364  -5.0000000\n1365   2.6666667\n1366   5.3333333\n1367   1.6666667\n1368   1.3333333\n1369  -5.3333333\n1370   5.0000000\n1371  -6.3333333\n1372   7.3333333\n1373  -5.3333333\n1374   5.6666667\n1375   8.6666667\n1376   3.6666667\n1377   3.3333333\n1378   6.3333333\n1379  -0.6666667\n1380   1.3333333\n1381   5.0000000\n1382   0.6666667\n1383   0.0000000\n1384  -1.0000000\n1385   0.3333333\n1386  -3.3333333\n1387  -5.0000000\n1388  -2.6666667\n1389   5.0000000\n1390  -4.0000000\n1391   8.0000000\n1392  -4.0000000\n1393  -1.6666667\n1394   0.3333333\n1395   5.3333333\n1396 -10.3333333\n1397  -4.6666667\n1398   2.6666667\n1399   1.3333333\n1400   2.3333333\n1401  -7.6666667\n1402  -5.0000000\n1403   4.3333333\n1404  -4.3333333\n1405   0.6666667\n1406   2.6666667\n1407   1.0000000\n1408  -4.6666667\n1409 -11.3333333\n1410  -0.3333333\n1411   2.6666667\n1412   0.0000000\n1413  -4.3333333\n1414   7.6666667\n1415   6.3333333\n1416   6.3333333\n1417   8.0000000\n1418  -4.6666667\n1419  -3.3333333\n1420  -1.6666667\n1421   0.6666667\n1422   4.0000000\n1423   2.6666667\n1424   1.6666667\n1425   6.6666667\n1426   8.6666667\n1427  -6.0000000\n1428  -9.3333333\n1429  -9.3333333\n1430  -1.0000000\n1431   0.6666667\n1432  -6.6666667\n1433   0.3333333\n1434 -10.6666667\n1435  -4.0000000\n1436  -2.0000000\n1437  -9.6666667\n1438  -4.0000000\n1439   6.6666667\n1440 -10.0000000\n1441  -4.6666667\n1442   2.6666667\n1443   0.6666667\n1444  -1.0000000\n1445  -3.6666667\n1446   5.3333333\n1447   4.0000000\n1448   4.0000000\n1449  -1.0000000\n1450  -3.3333333\n1451  -1.3333333\n1452  -0.3333333\n1453   0.3333333\n1454  -1.0000000\n1455   1.3333333\n1456  -9.6666667\n1457  -0.6666667\n1458  -5.3333333\n1459   1.6666667\n1460   5.3333333\n1461   3.0000000\n1462   3.3333333\n1463  -1.6666667\n1464  -8.3333333\n1465  -4.3333333\n1466   5.6666667\n1467   2.3333333\n1468   4.3333333\n1469   2.6666667\n1470   2.3333333\n1471  -0.6666667\n1472  -3.6666667\n1473   1.6666667\n1474   0.3333333\n1475 -11.6666667\n1476   2.6666667\n1477   7.6666667\n1478  -2.0000000\n1479   9.3333333\n1480   2.3333333\n1481  -7.3333333\n1482  -3.0000000\n1483  -4.0000000\n1484   3.6666667\n1485   2.0000000\n1486   0.6666667\n1487   5.6666667\n1488   2.6666667\n1489   2.6666667\n1490   0.3333333\n1491   8.3333333\n1492   6.6666667\n1493  -9.0000000\n1494  -3.0000000\n1495   0.3333333\n1496  -4.0000000\n1497  -4.6666667\n1498   3.3333333\n1499   4.6666667\n1500   4.3333333\n1501   2.6666667\n1502   0.3333333\n1503  -3.0000000\n1504  -2.3333333\n1505   2.6666667\n1506  -4.3333333\n1507  -2.3333333\n1508  -1.6666667\n1509  -3.0000000\n1510  -3.0000000\n1511   1.6666667\n1512   8.0000000\n1513  -4.3333333\n1514   4.0000000\n1515  -2.3333333\n1516   6.3333333\n1517  -3.6666667\n1518  -4.6666667\n1519  -1.0000000\n1520  -2.6666667\n1521  -0.6666667\n1522   0.6666667\n1523   4.0000000\n1524  -0.6666667\n1525  -3.6666667\n1526   5.6666667\n1527   0.0000000\n1528  -3.0000000\n1529   5.0000000\n1530   2.6666667\n1531   7.3333333\n1532  -1.0000000\n1533  -1.6666667\n1534   0.0000000\n1535   2.3333333\n1536   4.6666667\n1537   1.6666667\n1538   8.6666667\n1539  -2.6666667\n1540   2.6666667\n1541  -2.6666667\n1542  -4.6666667\n1543  -1.6666667\n1544   0.0000000\n1545  -3.6666667\n1546   3.6666667\n1547   5.0000000\n1548   2.3333333\n1549   8.0000000\n1550  -6.0000000\n1551   1.0000000\n1552  -3.0000000\n1553   1.0000000\n1554  -6.3333333\n1555   1.6666667\n1556   4.6666667\n1557   6.0000000\n1558  -0.3333333\n1559  -5.6666667\n1560   2.0000000\n1561   0.6666667\n1562  -4.3333333\n1563   0.0000000\n1564   4.0000000\n1565  -8.3333333\n1566  -0.3333333\n1567   4.6666667\n1568   0.0000000\n1569   6.0000000\n1570  -0.3333333\n1571  -2.3333333\n1572  -2.3333333\n1573  -4.3333333\n1574  -5.6666667\n1575   4.3333333\n1576  -5.6666667\n1577  -4.3333333\n1578   8.0000000\n1579  -2.0000000\n1580  -8.0000000\n1581   5.6666667\n1582   2.3333333\n1583  -3.3333333\n1584  -0.3333333\n1585   3.0000000\n1586   9.6666667\n1587  -5.6666667\n1588  -5.0000000\n1589   1.3333333\n1590  -0.6666667\n1591   8.6666667\n1592   3.6666667\n1593   1.0000000\n1594   7.3333333\n1595  -1.0000000\n1596   0.6666667\n1597   2.3333333\n1598   0.6666667\n1599  -0.6666667\n1600  -5.6666667\n1601  -0.6666667\n1602  -3.6666667\n1603   2.3333333\n1604   0.6666667\n1605   5.3333333\n1606   0.0000000\n1607  -0.6666667\n1608  -2.3333333\n1609   3.3333333\n1610   2.3333333\n1611   4.0000000\n1612   6.0000000\n1613  -0.3333333\n1614  -6.3333333\n1615   8.3333333\n1616  -5.0000000\n1617  -5.3333333\n1618  -1.0000000\n1619   1.3333333\n1620   1.3333333\n1621   3.6666667\n1622  -8.0000000\n1623   1.3333333\n1624  -3.0000000\n1625  -1.0000000\n1626  -0.3333333\n1627   0.0000000\n1628  -4.0000000\n1629  -3.6666667\n1630   6.0000000\n1631   9.3333333\n1632   2.0000000\n1633   8.0000000\n1634  10.0000000\n1635  -7.0000000\n1636  -0.3333333\n1637   0.0000000\n1638   7.3333333\n1639   1.3333333\n1640   1.6666667\n1641   7.6666667\n1642  -5.6666667\n1643  -0.6666667\n1644   6.6666667\n1645  -1.0000000\n1646  -7.0000000\n1647   4.0000000\n1648  -4.3333333\n1649  -5.3333333\n1650  -0.6666667\n1651   9.0000000\n1652   7.3333333\n1653  -4.3333333\n1654   1.0000000\n1655   5.3333333\n1656  -7.3333333\n1657  -3.3333333\n1658   2.6666667\n1659   9.3333333\n1660   5.6666667\n1661   2.6666667\n1662  -0.6666667\n1663   6.6666667\n1664  -3.3333333\n1665   3.3333333\n1666  -2.6666667\n1667   5.0000000\n1668   2.6666667\n1669  -8.6666667\n1670   1.3333333\n1671  -5.6666667\n1672   7.6666667\n1673   0.6666667\n1674  -4.0000000\n1675   0.0000000\n1676  -2.6666667\n1677   2.3333333\n1678  -1.6666667\n1679   0.0000000\n1680  -0.3333333\n1681   3.6666667\n1682   2.0000000\n1683  -7.6666667\n1684  -2.0000000\n1685   2.6666667\n1686  -5.6666667\n1687  -1.0000000\n1688   1.6666667\n1689   3.3333333\n1690   1.6666667\n1691   7.3333333\n1692  -1.3333333\n1693   7.6666667\n1694   2.0000000\n1695   0.0000000\n1696   1.0000000\n1697   2.0000000\n1698   3.3333333\n1699  10.0000000\n1700   7.6666667\n1701   8.0000000\n1702  -6.0000000\n1703  -2.3333333\n1704   7.0000000\n1705   1.0000000\n1706  -2.6666667\n1707  -1.0000000\n1708   3.3333333\n1709   4.3333333\n1710   8.6666667\n1711  -3.0000000\n1712   0.3333333\n1713  -0.3333333\n1714  -8.3333333\n1715   1.3333333\n1716 -11.6666667\n1717  -3.0000000\n1718   7.0000000\n1719   4.3333333\n1720  -5.0000000\n1721   5.3333333\n1722  -7.6666667\n1723   2.0000000\n1724  -6.0000000\n1725   2.0000000\n1726  -4.0000000\n1727  -5.0000000\n1728   2.6666667\n1729  -2.3333333\n1730   2.0000000\n1731  -4.0000000\n1732  -1.6666667\n1733  -3.0000000\n1734  -1.6666667\n1735   0.3333333\n1736   3.0000000\n1737  -7.6666667\n1738  -6.6666667\n1739  -1.6666667\n1740  -3.0000000\n1741   1.0000000\n1742 -11.0000000\n1743  -0.6666667\n1744   5.6666667\n1745  -2.3333333\n1746   5.6666667\n1747   3.0000000\n1748  -5.6666667\n1749   3.6666667\n1750   1.0000000\n1751  -1.6666667\n1752   6.6666667\n1753  -5.6666667\n1754  -2.3333333\n1755   0.3333333\n1756   1.6666667\n1757  -7.0000000\n1758  -1.0000000\n1759   1.6666667\n1760   2.0000000\n1761   3.0000000\n1762  -0.6666667\n1763   7.3333333\n1764  -8.0000000\n1765   4.0000000\n1766  -2.3333333\n1767  -4.3333333\n1768  -2.0000000\n1769  -2.6666667\n1770  11.6666667\n1771  -2.3333333\n1772  -8.0000000\n1773   5.3333333\n1774  -3.6666667\n1775   6.3333333\n1776   3.3333333\n1777  -2.0000000\n1778   3.0000000\n1779   5.6666667\n1780  -2.0000000\n1781  -6.0000000\n1782  -1.3333333\n1783   7.3333333\n1784   3.3333333\n1785  -1.0000000\n1786  -8.0000000\n1787  -2.3333333\n1788  -5.3333333\n1789   2.6666667\n1790   0.0000000\n1791   0.3333333\n1792  -1.6666667\n1793  -5.3333333\n1794  -0.6666667\n1795   0.3333333\n1796   6.0000000\n1797   1.6666667\n1798   2.6666667\n1799   1.3333333\n1800   2.6666667\n1801   1.0000000\n1802   2.6666667\n1803   2.3333333\n1804  -1.6666667\n1805 -11.6666667\n1806   5.0000000\n1807  -2.0000000\n1808   6.6666667\n1809  -2.3333333\n1810  -2.0000000\n1811   1.3333333\n1812  -2.0000000\n1813   9.0000000\n1814   0.3333333\n1815   0.0000000\n1816  -3.0000000\n1817  -2.6666667\n1818  -4.6666667\n1819  -4.3333333\n1820  -5.0000000\n1821  -6.0000000\n1822   0.3333333\n1823  -2.6666667\n1824   0.3333333\n1825  -4.3333333\n1826  -1.0000000\n1827 -10.6666667\n1828  -7.3333333\n1829   5.0000000\n1830 -12.0000000\n1831   4.0000000\n1832  -8.3333333\n1833  -6.6666667\n1834   1.0000000\n1835  -6.0000000\n1836  -7.6666667\n1837  -5.3333333\n1838  -1.0000000\n1839  -0.6666667\n1840   1.3333333\n1841   1.6666667\n1842  -7.0000000\n1843   2.6666667\n1844  -3.3333333\n1845  -1.3333333\n1846  -3.6666667\n1847   1.3333333\n1848   4.0000000\n1849   2.6666667\n1850   0.6666667\n1851   4.3333333\n1852  -0.6666667\n1853  -1.6666667\n1854   6.6666667\n1855  -1.0000000\n1856   3.3333333\n1857   2.6666667\n1858   5.0000000\n1859   6.6666667\n1860  -0.3333333\n1861   1.3333333\n1862   5.0000000\n1863  -4.0000000\n1864  -0.3333333\n1865   7.6666667\n1866  -6.0000000\n1867   1.6666667\n1868  -8.0000000\n1869   1.6666667\n1870  -0.3333333\n1871   4.6666667\n1872   2.3333333\n1873   2.0000000\n1874   3.6666667\n1875  -4.3333333\n1876  -6.6666667\n1877  -2.0000000\n1878  -4.3333333\n1879   7.3333333\n1880  -4.6666667\n1881  -1.0000000\n1882   5.6666667\n1883   7.0000000\n1884   5.3333333\n1885   1.3333333\n1886  -2.3333333\n1887   1.0000000\n1888  -3.6666667\n1889   8.0000000\n1890   7.0000000\n1891   4.6666667\n1892   7.6666667\n1893  -4.0000000\n1894   2.6666667\n1895  -4.6666667\n1896  -7.3333333\n1897  -3.6666667\n1898   5.0000000\n1899  -3.0000000\n1900  -1.3333333\n1901   5.0000000\n1902   6.6666667\n1903  -2.0000000\n1904   1.6666667\n1905   2.3333333\n1906   5.0000000\n1907   0.3333333\n1908   9.3333333\n1909  -0.6666667\n1910   5.3333333\n1911   1.6666667\n1912   5.0000000\n1913   3.0000000\n1914   7.3333333\n1915  -2.3333333\n1916  -2.6666667\n1917  -3.3333333\n1918   1.3333333\n1919   4.6666667\n1920   5.6666667\n1921   1.0000000\n1922   1.0000000\n1923   2.0000000\n1924  -2.0000000\n1925  -1.0000000\n1926   1.0000000\n1927  -4.6666667\n1928  -4.3333333\n1929   2.0000000\n1930 -10.0000000\n1931  -5.3333333\n1932  -3.0000000\n1933  -1.0000000\n1934   2.3333333\n1935   3.6666667\n1936  -0.6666667\n1937  -6.3333333\n1938   1.6666667\n1939  -5.3333333\n1940  -8.6666667\n1941   3.3333333\n1942   7.0000000\n1943  -2.3333333\n1944   0.3333333\n1945   6.0000000\n1946   1.6666667\n1947  11.3333333\n1948   0.0000000\n1949   3.3333333\n1950  -5.0000000\n1951   6.6666667\n1952  -6.6666667\n1953   7.0000000\n1954  -1.6666667\n1955   0.0000000\n1956 -10.0000000\n1957  -0.3333333\n1958   2.0000000\n1959   2.0000000\n1960  -5.6666667\n1961  -2.3333333\n1962   3.6666667\n1963   2.0000000\n1964   4.3333333\n1965  -4.6666667\n1966  -6.0000000\n1967  10.0000000\n1968   3.0000000\n1969   8.6666667\n1970   6.3333333\n1971   6.3333333\n1972  -0.6666667\n1973   6.3333333\n1974  -5.6666667\n1975  -6.3333333\n1976  -1.3333333\n1977  -5.0000000\n1978  -2.6666667\n1979  -0.6666667\n1980   4.3333333\n1981   0.3333333\n1982  -7.3333333\n1983   2.3333333\n1984  -4.0000000\n1985  -0.3333333\n1986  -6.3333333\n1987   7.6666667\n1988   7.0000000\n1989  -7.3333333\n1990 -15.6666667\n1991  13.3333333\n1992   0.3333333\n1993   5.6666667\n1994  -0.6666667\n1995  -1.6666667\n1996 -11.6666667\n1997   0.3333333\n1998  -1.0000000\n1999   2.6666667\n2000  -4.6666667\n2001  -2.6666667\n2002  -5.6666667\n2003   7.0000000\n2004  -0.6666667\n2005   3.6666667\n2006   0.3333333\n2007   4.6666667\n2008   1.6666667\n2009  -2.6666667\n2010   2.0000000\n2011   0.6666667\n2012   2.6666667\n2013   1.0000000\n2014  -0.6666667\n2015   2.6666667\n2016   2.3333333\n2017  -5.3333333\n2018  -0.3333333\n2019  -0.3333333\n2020   0.3333333\n2021   6.6666667\n2022   6.6666667\n2023  -6.3333333\n2024   5.3333333\n2025  -1.6666667\n2026  -5.0000000\n2027  -8.3333333\n2028  -6.0000000\n2029   1.6666667\n2030  -3.6666667\n2031  -4.0000000\n2032  -4.3333333\n2033  -2.3333333\n2034   1.0000000\n2035   0.6666667\n2036   4.3333333\n2037   1.3333333\n2038  -5.3333333\n2039   3.6666667\n2040  -6.3333333\n2041   0.6666667\n2042   4.3333333\n2043  -4.3333333\n2044  -4.0000000\n2045  -3.6666667\n2046   1.3333333\n2047  -3.6666667\n2048   4.0000000\n2049   3.0000000\n2050  -2.6666667\n2051   3.6666667\n2052  -3.6666667\n2053 -10.3333333\n2054   4.0000000\n2055  -4.3333333\n2056   4.6666667\n2057  -1.3333333\n2058   3.3333333\n2059   0.6666667\n2060  -7.6666667\n2061   2.0000000\n2062   3.6666667\n2063   9.6666667\n2064  -7.3333333\n2065   1.0000000\n2066   0.6666667\n2067  -1.6666667\n2068  -3.0000000\n2069   3.3333333\n2070  -6.6666667\n2071   3.0000000\n2072  -3.3333333\n2073   6.0000000\n2074  -5.3333333\n2075  -0.6666667\n2076   5.6666667\n2077   0.6666667\n2078   3.6666667\n2079  -5.0000000\n2080  -4.6666667\n2081  -6.6666667\n2082  -4.6666667\n2083   1.6666667\n2084  -4.6666667\n2085  -1.3333333\n2086  -5.0000000\n2087  -2.3333333\n2088  -8.6666667\n2089  -6.3333333\n2090   4.3333333\n2091   9.0000000\n2092   3.6666667\n2093   1.0000000\n2094  -2.6666667\n2095 -10.6666667\n2096   7.3333333\n2097   5.0000000\n2098   8.0000000\n2099  -4.3333333\n2100   3.0000000\n2101   6.0000000\n2102   3.3333333\n2103   0.0000000\n2104   3.0000000\n2105  -1.0000000\n2106   1.6666667\n2107  -7.0000000\n2108   6.6666667\n2109  -3.3333333\n2110   7.6666667\n2111  -2.0000000\n2112  -6.3333333\n2113   4.6666667\n2114   2.3333333\n2115   5.3333333\n2116  -3.0000000\n2117  -4.6666667\n2118   0.3333333\n2119   3.6666667\n2120  -8.0000000\n2121   8.3333333\n2122   1.3333333\n2123   5.6666667\n2124   5.3333333\n2125  -2.0000000\n2126  -1.6666667\n2127   5.0000000\n2128  -2.0000000\n2129  -4.6666667\n2130   1.0000000\n2131   7.0000000\n2132  -7.0000000\n2133  -3.6666667\n2134   7.6666667\n2135   4.3333333\n2136   2.0000000\n2137   3.3333333\n2138   5.6666667\n2139   0.0000000\n2140 -10.6666667\n2141   2.3333333\n2142  -1.6666667\n2143   0.3333333\n2144   0.0000000\n2145   1.3333333\n2146  -1.6666667\n2147  -4.0000000\n2148   3.3333333\n2149  -1.3333333\n2150  -3.3333333\n2151   5.3333333\n2152  -4.3333333\n2153  -2.0000000\n2154   3.3333333\n2155  -0.6666667\n2156   1.6666667\n2157  -2.3333333\n2158   4.3333333\n2159  -0.3333333\n2160  -1.6666667\n2161  -0.3333333\n2162   3.0000000\n2163   2.0000000\n2164  -7.0000000\n2165  -2.3333333\n2166   5.0000000\n2167  -6.6666667\n2168  -3.3333333\n2169  -5.3333333\n2170   3.0000000\n2171  -5.3333333\n2172  -0.6666667\n2173   0.3333333\n2174   3.3333333\n2175   1.3333333\n2176  -1.0000000\n2177  -1.3333333\n2178   4.6666667\n2179   2.3333333\n2180   1.6666667\n2181  -4.3333333\n2182  -1.0000000\n2183   8.3333333\n2184  -9.6666667\n2185   0.0000000\n2186   6.3333333\n2187  -1.3333333\n2188   6.6666667\n2189   2.0000000\n2190  -0.6666667\n2191   3.3333333\n2192  -2.6666667\n2193   6.0000000\n2194  -6.3333333\n2195   7.0000000\n2196  -7.6666667\n2197  -0.3333333\n2198   5.6666667\n2199  -7.0000000\n2200  -5.3333333\n2201  -2.0000000\n2202   8.0000000\n2203  -3.6666667\n2204   0.0000000\n2205   5.3333333\n2206   2.3333333\n2207  -7.3333333\n2208  -8.6666667\n2209  -3.3333333\n2210  -3.3333333\n2211  -0.6666667\n2212   2.3333333\n2213  -1.6666667\n2214   7.0000000\n2215   1.0000000\n2216   2.0000000\n2217  -4.0000000\n2218  -0.3333333\n2219   0.3333333\n2220  -7.3333333\n2221  -1.0000000\n2222  -3.3333333\n2223   6.0000000\n2224   0.0000000\n2225   6.6666667\n2226   1.0000000\n2227   2.0000000\n2228  -5.0000000\n2229  -6.0000000\n2230   0.3333333\n2231  -5.0000000\n2232   0.3333333\n2233  -7.0000000\n2234  -0.3333333\n2235   5.6666667\n2236  -0.6666667\n2237  -5.0000000\n2238   0.6666667\n2239   0.0000000\n2240   3.6666667\n2241   1.3333333\n2242   3.0000000\n2243  -1.3333333\n2244   2.6666667\n2245  -6.6666667\n2246   7.6666667\n2247   1.0000000\n2248  -5.3333333\n2249   0.6666667\n2250  -0.6666667\n2251   4.3333333\n2252   0.0000000\n2253  -4.0000000\n2254   1.6666667\n2255  -2.3333333\n2256  -8.0000000\n2257   2.0000000\n2258  -1.6666667\n2259   0.6666667\n2260  -3.6666667\n2261  -3.6666667\n2262  -8.0000000\n2263   2.3333333\n2264   2.3333333\n2265  -1.3333333\n2266  -1.6666667\n2267   0.3333333\n2268   9.0000000\n2269   1.6666667\n2270   0.6666667\n2271   2.0000000\n2272   4.3333333\n2273   7.0000000\n2274  -4.0000000\n2275   3.3333333\n2276  -6.6666667\n2277  -4.0000000\n2278  -5.3333333\n2279   1.0000000\n2280  -5.0000000\n2281   4.3333333\n2282  -6.0000000\n2283  -0.6666667\n2284  -0.3333333\n2285  -6.0000000\n2286   3.3333333\n2287  -2.6666667\n2288  -3.3333333\n2289   5.0000000\n2290  -4.0000000\n2291   9.6666667\n2292   1.3333333\n2293   4.0000000\n2294  -1.0000000\n2295   5.3333333\n2296   2.6666667\n2297  -5.6666667\n2298  -1.6666667\n2299   7.3333333\n2300   5.6666667\n2301   0.6666667\n2302   1.6666667\n2303   5.6666667\n2304  -0.6666667\n2305   2.6666667\n2306   3.6666667\n2307   0.6666667\n2308  -3.0000000\n2309  -6.6666667\n2310   6.0000000\n2311   0.3333333\n2312   5.3333333\n2313  -3.6666667\n2314   0.3333333\n2315   6.0000000\n2316  -1.6666667\n2317   3.6666667\n2318   5.0000000\n2319  -4.0000000\n2320   0.6666667\n2321  -5.6666667\n2322   4.6666667\n2323   2.6666667\n2324   1.6666667\n2325  -8.6666667\n2326   3.0000000\n2327   8.6666667\n2328   5.0000000\n2329  -0.6666667\n2330   6.6666667\n2331  -2.6666667\n2332  -2.3333333\n2333   5.6666667\n2334   4.0000000\n2335  -6.6666667\n2336  -2.0000000\n2337   4.3333333\n2338  -3.3333333\n2339  -2.3333333\n2340  -7.3333333\n2341   0.6666667\n2342  -3.0000000\n2343   4.6666667\n2344  -6.0000000\n2345  -0.3333333\n2346  -0.6666667\n2347   4.6666667\n2348  10.3333333\n2349   6.0000000\n2350   2.0000000\n2351  -6.6666667\n2352  -3.3333333\n2353  -1.0000000\n2354  -3.6666667\n2355  11.6666667\n2356   3.3333333\n2357  -1.3333333\n2358  -2.0000000\n2359   2.6666667\n2360  -3.0000000\n2361   4.6666667\n2362   2.0000000\n2363   0.0000000\n2364   3.0000000\n2365  -1.0000000\n2366  -4.0000000\n2367   1.6666667\n2368   2.3333333\n2369   3.0000000\n2370  13.6666667\n2371  -4.0000000\n2372   1.3333333\n2373   0.6666667\n2374   5.6666667\n2375  -5.3333333\n2376   7.6666667\n2377  -2.6666667\n2378   6.6666667\n2379  -3.6666667\n2380   4.0000000\n2381  -9.6666667\n2382  -7.0000000\n2383   8.3333333\n2384   3.0000000\n2385  -1.0000000\n2386  -8.3333333\n2387   5.3333333\n2388   5.0000000\n2389  -3.3333333\n2390   0.3333333\n2391  -1.0000000\n2392  -3.3333333\n2393   6.6666667\n2394   1.0000000\n2395   7.0000000\n2396  -0.3333333\n2397  -5.3333333\n2398  -3.3333333\n2399  -3.3333333\n2400  -6.0000000\n2401   3.6666667\n2402   6.3333333\n2403   4.0000000\n2404  -2.3333333\n2405  -6.3333333\n2406  -0.3333333\n2407   2.6666667\n2408   2.6666667\n2409  -2.6666667\n2410   5.3333333\n2411  -2.0000000\n2412   6.3333333\n2413   3.6666667\n2414   4.0000000\n2415   5.3333333\n2416   3.0000000\n2417  -3.6666667\n2418   0.0000000\n2419   2.3333333\n2420   1.3333333\n2421  -8.3333333\n2422  -4.3333333\n2423  -7.6666667\n2424   7.0000000\n2425   4.6666667\n2426  -3.0000000\n2427   6.6666667\n2428  -2.6666667\n2429  -7.3333333\n2430  -3.0000000\n2431  -0.6666667\n2432  -0.6666667\n2433  -3.0000000\n2434   5.6666667\n2435   4.6666667\n2436  -1.6666667\n2437  -1.0000000\n2438  -5.6666667\n2439  -7.0000000\n2440   3.0000000\n2441   5.0000000\n2442   7.3333333\n2443   6.3333333\n2444   1.6666667\n2445  -6.3333333\n2446  -9.6666667\n2447   5.3333333\n2448  -0.6666667\n2449   4.6666667\n2450  -2.0000000\n2451  -0.6666667\n2452  -5.6666667\n2453   6.0000000\n2454  -1.0000000\n2455   0.3333333\n2456   7.3333333\n2457  -0.6666667\n2458  -3.3333333\n2459   9.0000000\n2460  -2.3333333\n2461  -2.6666667\n2462   1.3333333\n2463   2.0000000\n2464 -10.0000000\n2465   4.3333333\n2466  -4.3333333\n2467   0.3333333\n2468  -6.6666667\n2469  -2.3333333\n2470   2.6666667\n2471   7.3333333\n2472  -3.6666667\n2473  -5.6666667\n2474   3.3333333\n2475  -2.3333333\n2476  -5.0000000\n2477   2.0000000\n2478  -8.6666667\n2479   2.3333333\n2480   3.0000000\n2481   1.6666667\n2482  -1.6666667\n2483   0.0000000\n2484  -0.3333333\n2485   2.6666667\n2486   0.3333333\n2487   9.3333333\n2488  -1.6666667\n2489  -2.6666667\n2490 -11.0000000\n2491  -5.3333333\n2492   5.6666667\n2493   5.0000000\n2494   5.0000000\n2495   1.0000000\n2496  -5.6666667\n2497   6.6666667\n2498  -2.3333333\n2499   5.3333333\n2500   1.3333333\n2501   3.0000000\n2502   3.0000000\n2503  -5.6666667\n2504  -4.0000000\n2505  -2.3333333\n2506  -3.3333333\n2507  -7.0000000\n2508   3.3333333\n2509  -4.0000000\n2510  -1.0000000\n2511   4.3333333\n2512  -7.6666667\n2513   4.0000000\n2514   7.6666667\n2515  -0.6666667\n2516   3.6666667\n2517   3.3333333\n2518   4.3333333\n2519   5.0000000\n2520   4.3333333\n2521  -1.6666667\n2522   3.3333333\n2523  -4.3333333\n2524  -5.6666667\n2525  -1.6666667\n2526  -2.0000000\n2527  11.6666667\n2528   3.6666667\n2529  -3.0000000\n2530   6.3333333\n2531  -4.6666667\n2532  -0.6666667\n2533  -1.6666667\n2534  -3.0000000\n2535  -4.3333333\n2536  -4.3333333\n2537  -4.0000000\n2538  -3.6666667\n2539   7.6666667\n2540   8.3333333\n2541   2.0000000\n2542   7.0000000\n2543   1.6666667\n2544  -2.3333333\n2545   0.3333333\n2546   4.6666667\n2547  -6.0000000\n2548   0.6666667\n2549  -3.0000000\n2550  -0.3333333\n2551   4.0000000\n2552  -2.0000000\n2553  -1.6666667\n2554  -6.3333333\n2555   5.6666667\n2556   3.0000000\n2557   6.0000000\n2558   0.0000000\n2559   0.6666667\n2560  -7.0000000\n2561  -5.0000000\n2562   9.3333333\n2563   0.0000000\n2564   4.0000000\n2565  -0.6666667\n2566   1.6666667\n2567   9.0000000\n2568   1.3333333\n2569  -1.0000000\n2570  -4.3333333\n2571   9.6666667\n2572   9.6666667\n2573  -5.3333333\n2574   3.0000000\n2575   4.3333333\n2576   5.0000000\n2577  -3.0000000\n2578   5.0000000\n2579   1.0000000\n2580  -0.3333333\n2581  -8.0000000\n2582   4.6666667\n2583  -1.3333333\n2584  -0.3333333\n2585   4.3333333\n2586   0.0000000\n2587   7.3333333\n2588  -0.3333333\n2589   1.6666667\n2590  -2.0000000\n2591   1.3333333\n2592   5.6666667\n2593   1.6666667\n2594  -5.6666667\n2595   8.6666667\n2596   3.0000000\n2597  -4.0000000\n2598  -5.0000000\n2599  -2.0000000\n2600   3.6666667\n2601  -9.3333333\n2602   0.0000000\n2603   7.0000000\n2604   0.0000000\n2605  -3.3333333\n2606  -6.3333333\n2607  -3.0000000\n2608  -2.0000000\n2609   4.0000000\n2610   3.0000000\n2611  -6.3333333\n2612  -7.6666667\n2613  -2.3333333\n2614   1.3333333\n2615   5.3333333\n2616  -6.6666667\n2617   3.3333333\n2618  -0.3333333\n2619   0.3333333\n2620  -8.0000000\n2621   4.3333333\n2622  -0.3333333\n2623   9.3333333\n2624  -6.0000000\n2625  10.6666667\n2626  -1.0000000\n2627  -4.3333333\n2628   5.0000000\n2629  -8.3333333\n2630   3.6666667\n2631   0.6666667\n2632   4.3333333\n2633   6.0000000\n2634  -2.0000000\n2635  -4.6666667\n2636  -1.6666667\n2637  -2.3333333\n2638   1.0000000\n2639  -6.3333333\n2640  -2.3333333\n2641   9.0000000\n2642   4.3333333\n2643  -4.6666667\n2644   0.3333333\n2645  -5.0000000\n2646   0.3333333\n2647  -6.0000000\n2648  -3.3333333\n2649  -1.0000000\n2650   1.6666667\n2651  11.3333333\n2652   2.0000000\n2653   5.3333333\n2654  -5.6666667\n2655  -9.0000000\n2656   0.0000000\n2657   2.6666667\n2658  -1.0000000\n2659   3.0000000\n2660  -1.0000000\n2661   7.6666667\n2662   4.6666667\n2663   1.0000000\n2664  -4.3333333\n2665   1.3333333\n2666  -0.6666667\n2667   1.6666667\n2668  -8.6666667\n2669   5.3333333\n2670   1.3333333\n2671   2.3333333\n2672  -1.6666667\n2673  10.6666667\n2674  -3.6666667\n2675   4.3333333\n2676   1.3333333\n2677   0.3333333\n2678   3.6666667\n2679   3.3333333\n2680  -5.6666667\n2681   3.0000000\n2682   0.3333333\n2683  -7.0000000\n2684  -1.0000000\n2685   1.3333333\n2686  -2.3333333\n2687   3.3333333\n2688   0.0000000\n2689   1.6666667\n2690  -2.6666667\n2691   1.3333333\n2692  -0.3333333\n2693   0.0000000\n2694   2.0000000\n2695   1.6666667\n2696   0.6666667\n2697  -9.0000000\n2698   3.3333333\n2699  -4.3333333\n2700  -1.3333333\n2701   4.0000000\n2702   3.3333333\n2703  -1.6666667\n2704  -4.3333333\n2705   9.6666667\n2706   1.6666667\n2707   2.3333333\n2708   0.6666667\n2709   1.3333333\n2710  -1.0000000\n2711   0.6666667\n2712  -3.3333333\n2713  -5.6666667\n2714  -4.6666667\n2715  -2.6666667\n2716  -4.6666667\n2717   2.6666667\n2718   2.6666667\n2719  -3.0000000\n2720   0.6666667\n2721   1.0000000\n2722  -6.0000000\n2723  -2.3333333\n2724  -6.3333333\n2725  -2.6666667\n2726   0.6666667\n2727  -8.6666667\n2728  -0.6666667\n2729  -5.3333333\n2730   0.0000000\n2731   3.0000000\n2732  -9.0000000\n2733   4.0000000\n2734  -7.3333333\n2735   0.3333333\n2736  -2.0000000\n2737  -0.3333333\n2738  -8.3333333\n2739   8.0000000\n2740  -3.6666667\n2741   7.0000000\n2742   2.6666667\n2743  -2.0000000\n2744  -0.6666667\n2745  -9.3333333\n2746  -0.3333333\n2747  -2.3333333\n2748   0.0000000\n2749   1.0000000\n2750   2.0000000\n2751   5.3333333\n2752  -3.3333333\n2753  -3.0000000\n2754  -2.6666667\n2755   1.6666667\n2756   5.6666667\n2757   1.0000000\n2758   4.3333333\n2759  -6.0000000\n2760  -4.3333333\n2761 -10.0000000\n2762  -1.3333333\n2763  -9.0000000\n2764   8.6666667\n2765  -1.3333333\n2766  -5.3333333\n2767  -0.3333333\n2768   2.0000000\n2769  -1.0000000\n2770   0.3333333\n2771   1.3333333\n2772   6.6666667\n2773  -8.0000000\n2774  -3.0000000\n2775   2.0000000\n2776   3.6666667\n2777  -2.3333333\n2778  -6.6666667\n2779  -2.6666667\n2780   3.6666667\n2781  -2.0000000\n2782   5.3333333\n2783   0.6666667\n2784  -2.0000000\n2785  -3.0000000\n2786  -8.0000000\n2787  -0.3333333\n2788  -2.3333333\n2789  -1.0000000\n2790  -4.6666667\n2791   1.3333333\n2792   0.6666667\n2793   3.6666667\n2794  -3.6666667\n2795  -9.6666667\n2796   2.6666667\n2797   1.6666667\n2798   7.6666667\n2799   5.3333333\n2800   6.0000000\n2801   2.3333333\n2802  -1.3333333\n2803   0.3333333\n2804  -1.0000000\n2805   8.0000000\n2806  -5.0000000\n2807  -3.3333333\n2808  -8.3333333\n2809  -7.0000000\n2810   1.0000000\n2811  -5.0000000\n2812  -3.3333333\n2813  -3.3333333\n2814  -0.6666667\n2815   6.0000000\n2816  -1.6666667\n2817   5.0000000\n2818  -0.6666667\n2819   0.6666667\n2820   3.6666667\n2821   2.0000000\n2822   0.6666667\n2823  -4.3333333\n2824   0.6666667\n2825  11.6666667\n2826   1.0000000\n2827   7.3333333\n2828   8.0000000\n2829  -4.0000000\n2830  -3.0000000\n2831  -0.6666667\n2832  -3.6666667\n2833  -5.0000000\n2834  10.3333333\n2835  -3.6666667\n2836  -7.3333333\n2837  -1.0000000\n2838   5.3333333\n2839  -8.6666667\n2840   4.0000000\n2841   2.6666667\n2842  -7.3333333\n2843   5.6666667\n2844   8.0000000\n2845  -6.0000000\n2846   5.0000000\n2847   7.6666667\n2848  -4.0000000\n2849   4.3333333\n2850   2.3333333\n2851  -6.3333333\n2852   5.3333333\n2853   3.0000000\n2854  -9.3333333\n2855  -6.6666667\n2856   4.6666667\n2857  10.6666667\n2858   3.6666667\n2859   0.0000000\n2860   5.0000000\n2861  -3.3333333\n2862   1.3333333\n2863  -6.3333333\n2864   4.0000000\n2865  -5.3333333\n2866   1.0000000\n2867   6.3333333\n2868  -2.0000000\n2869  -0.6666667\n2870  -1.6666667\n2871   7.0000000\n2872  -4.6666667\n2873  -5.3333333\n2874  -3.0000000\n2875   3.3333333\n2876   9.3333333\n2877  -0.6666667\n2878   0.3333333\n2879   6.6666667\n2880  -2.0000000\n2881  -1.6666667\n2882  -2.6666667\n2883  -0.3333333\n2884  -2.6666667\n2885  -6.3333333\n2886  -0.6666667\n2887  -3.3333333\n2888   0.6666667\n2889  -2.6666667\n2890  -5.6666667\n2891   0.3333333\n2892   2.0000000\n2893  -7.3333333\n2894  -6.0000000\n2895  -6.0000000\n2896  -4.0000000\n2897   6.6666667\n2898  -8.0000000\n2899   4.3333333\n2900  -4.0000000\n2901  -1.0000000\n2902   3.6666667\n2903  -6.6666667\n2904   3.3333333\n2905   1.3333333\n2906  -2.3333333\n2907  -5.6666667\n2908  10.3333333\n2909  -7.0000000\n2910   1.6666667\n2911   8.6666667\n2912   0.6666667\n2913 -10.0000000\n2914   2.0000000\n2915   5.6666667\n2916   6.3333333\n2917   3.6666667\n2918  -2.0000000\n2919   0.3333333\n2920  -2.6666667\n2921  -1.0000000\n2922   1.0000000\n2923   4.0000000\n2924  -1.0000000\n2925   6.6666667\n2926  -3.0000000\n2927  -4.6666667\n2928   1.3333333\n2929  -3.0000000\n2930  -2.3333333\n2931   6.6666667\n2932   2.3333333\n2933  -6.6666667\n2934  -3.6666667\n2935   3.3333333\n2936  -6.6666667\n2937   7.0000000\n2938  -2.0000000\n2939  -4.3333333\n2940   4.6666667\n2941  -1.3333333\n2942  -9.3333333\n2943  -6.3333333\n2944   2.0000000\n2945   1.6666667\n2946  13.3333333\n2947  -6.3333333\n2948  -5.0000000\n2949  -5.3333333\n2950  -3.3333333\n2951  -4.0000000\n2952   0.3333333\n2953   5.3333333\n2954  -7.6666667\n2955  -1.3333333\n2956   7.6666667\n2957  -1.0000000\n2958  -6.6666667\n2959  -3.0000000\n2960   6.0000000\n2961  -4.3333333\n2962  -6.6666667\n2963  -3.0000000\n2964   0.0000000\n2965   6.0000000\n2966  -2.0000000\n2967  -2.6666667\n2968   3.3333333\n2969  -1.3333333\n2970  -6.3333333\n2971  -2.0000000\n2972  -3.3333333\n2973  -0.6666667\n2974   6.3333333\n2975   6.3333333\n2976   6.0000000\n2977   0.0000000\n2978  -1.3333333\n2979   2.0000000\n2980   8.0000000\n2981  -2.3333333\n2982   8.0000000\n2983   2.3333333\n2984  -7.3333333\n2985  -2.0000000\n2986   6.0000000\n2987   2.3333333\n2988   2.6666667\n2989  -2.6666667\n2990   2.6666667\n2991   5.0000000\n2992  -5.3333333\n2993  -7.6666667\n2994  -5.6666667\n2995   5.3333333\n2996  -7.3333333\n2997  -2.6666667\n2998   1.0000000\n2999  -7.3333333\n3000   3.3333333\n3001   0.0000000\n3002  -5.0000000\n3003  -0.6666667\n3004   7.3333333\n3005   6.6666667\n3006  -3.0000000\n3007   5.6666667\n3008   5.6666667\n3009   3.3333333\n3010   0.6666667\n3011   1.3333333\n3012  -5.6666667\n3013   2.6666667\n3014   8.6666667\n3015  -4.0000000\n3016   0.0000000\n3017   2.6666667\n3018  -3.6666667\n3019  -5.0000000\n3020  -2.3333333\n3021   7.3333333\n3022   6.0000000\n3023  -1.0000000\n3024  -8.0000000\n3025   6.6666667\n3026  -6.6666667\n3027   8.6666667\n3028  -7.6666667\n3029   7.0000000\n3030   2.3333333\n3031  -0.3333333\n3032  -3.0000000\n3033  -3.3333333\n3034   2.6666667\n3035   2.3333333\n3036  -2.6666667\n3037  -6.0000000\n3038  -0.6666667\n3039   3.3333333\n3040   3.0000000\n3041  -5.6666667\n3042   5.3333333\n3043   4.0000000\n3044   0.0000000\n3045   0.3333333\n3046   4.0000000\n3047 -10.0000000\n3048  -3.3333333\n3049   0.0000000\n3050   8.3333333\n3051   1.3333333\n3052   1.0000000\n3053  -1.0000000\n3054   7.6666667\n3055  -1.3333333\n3056   4.3333333\n3057   5.0000000\n3058   4.3333333\n3059  -3.3333333\n3060   3.0000000\n3061   7.3333333\n3062   7.3333333\n3063  -3.6666667\n3064  -4.0000000\n3065  -3.0000000\n3066  -1.0000000\n3067  -7.0000000\n3068   8.6666667\n3069  -3.6666667\n3070   3.0000000\n3071  -5.0000000\n3072  -1.3333333\n3073   0.0000000\n3074  -1.3333333\n3075   3.0000000\n3076   6.6666667\n3077  -1.3333333\n3078  -6.0000000\n3079  -9.6666667\n3080   3.6666667\n3081  -5.0000000\n3082  -3.0000000\n3083  -2.3333333\n3084   2.3333333\n3085  -0.6666667\n3086   1.3333333\n3087  -3.6666667\n3088  -4.6666667\n3089  -2.6666667\n3090   0.6666667\n3091   3.3333333\n3092   2.0000000\n3093  -4.3333333\n3094  -0.6666667\n3095   8.3333333\n3096  -1.3333333\n3097  -3.3333333\n3098  -1.6666667\n3099  -6.3333333\n3100   4.0000000\n3101  -3.6666667\n3102   9.6666667\n3103  -2.6666667\n3104  -0.6666667\n3105   6.3333333\n3106   3.6666667\n3107   5.0000000\n3108  -3.3333333\n3109  -2.0000000\n3110  -3.0000000\n3111   4.3333333\n3112   8.3333333\n3113  -5.3333333\n3114  -2.0000000\n3115  -3.3333333\n3116   2.3333333\n3117   2.0000000\n3118   1.3333333\n3119  -7.0000000\n3120   9.3333333\n3121  -3.3333333\n3122  -1.3333333\n3123  -0.3333333\n3124  -7.0000000\n3125   2.6666667\n3126   1.6666667\n3127  -2.3333333\n3128   1.6666667\n3129   5.0000000\n3130  -4.3333333\n3131  -5.3333333\n3132   5.3333333\n3133   0.0000000\n3134   1.6666667\n3135   6.0000000\n3136  -0.6666667\n3137   0.3333333\n3138   6.0000000\n3139   0.3333333\n3140  -4.0000000\n3141  -3.0000000\n3142   5.0000000\n3143   3.0000000\n3144 -11.0000000\n3145  -0.3333333\n3146  -3.6666667\n3147  -5.6666667\n3148  -5.0000000\n3149  -7.6666667\n3150   3.3333333\n3151 -11.0000000\n3152   6.6666667\n3153  -4.0000000\n3154  -0.3333333\n3155  -8.6666667\n3156  -5.3333333\n3157  -3.6666667\n3158  -5.0000000\n3159  -8.0000000\n3160  -0.6666667\n3161  -7.3333333\n3162   5.6666667\n3163   5.3333333\n3164  -5.3333333\n3165   0.3333333\n3166  -7.0000000\n3167   3.3333333\n3168  -4.6666667\n3169   0.0000000\n3170  -3.3333333\n3171   0.6666667\n3172  10.6666667\n3173   2.0000000\n3174  -3.3333333\n3175   8.6666667\n3176   4.3333333\n3177   6.3333333\n3178   3.6666667\n3179   2.0000000\n3180   3.6666667\n3181   1.6666667\n3182  -4.0000000\n3183  -4.3333333\n3184  -8.3333333\n3185  -5.6666667\n3186  -2.6666667\n3187   3.0000000\n3188   0.6666667\n3189   8.0000000\n3190  -4.0000000\n3191  -5.6666667\n3192   5.0000000\n3193  -4.6666667\n3194  -1.6666667\n3195  10.3333333\n3196   1.0000000\n3197  -3.3333333\n3198   0.6666667\n3199   4.0000000\n3200   4.6666667\n3201  -1.0000000\n3202   3.3333333\n3203   0.6666667\n3204   5.0000000\n3205   3.6666667\n3206  -2.3333333\n3207   6.0000000\n3208   2.0000000\n3209  -2.3333333\n3210  -6.6666667\n3211   0.6666667\n3212  -7.3333333\n3213   4.6666667\n3214   0.0000000\n3215  -6.6666667\n3216  -0.6666667\n3217  -6.0000000\n3218   1.0000000\n3219   1.6666667\n3220  -3.0000000\n3221   2.0000000\n3222  -1.6666667\n3223  -0.6666667\n3224   7.0000000\n3225   1.0000000\n3226   0.3333333\n3227   4.0000000\n3228   1.0000000\n3229   3.0000000\n3230  -6.0000000\n3231   4.0000000\n3232  -5.0000000\n3233  -0.3333333\n3234   1.3333333\n3235   0.0000000\n3236  -4.3333333\n3237   0.0000000\n3238   1.0000000\n3239  11.0000000\n3240   5.6666667\n3241  -6.3333333\n3242   5.3333333\n3243  -1.6666667\n3244  -1.0000000\n3245  -1.6666667\n3246   1.3333333\n3247  -3.6666667\n3248  -9.0000000\n3249  -7.3333333\n3250   0.6666667\n3251  -2.3333333\n3252   6.3333333\n3253  -4.6666667\n3254   2.3333333\n3255  -9.6666667\n3256  -5.0000000\n3257   4.0000000\n3258  -0.6666667\n3259  -3.6666667\n3260  -5.6666667\n3261  -6.6666667\n3262   2.6666667\n3263   6.0000000\n3264   0.6666667\n3265   2.0000000\n3266   1.0000000\n3267  -4.0000000\n3268   5.3333333\n3269  -1.3333333\n3270   0.0000000\n3271 -11.3333333\n3272   6.6666667\n3273  -4.3333333\n3274  -3.0000000\n3275  -4.0000000\n3276  -4.0000000\n3277  -6.0000000\n3278   0.0000000\n3279   3.6666667\n3280   4.3333333\n3281  -4.3333333\n3282  -1.6666667\n3283  -3.3333333\n3284  -7.0000000\n3285   4.0000000\n3286  -8.6666667\n3287  -1.0000000\n3288  -1.6666667\n3289   1.0000000\n3290   0.3333333\n3291  -6.0000000\n3292  -6.3333333\n3293   0.0000000\n3294  -3.6666667\n3295   0.3333333\n3296   2.0000000\n3297   7.0000000\n3298  -6.3333333\n3299   1.6666667\n3300   3.6666667\n3301   0.0000000\n3302   3.0000000\n3303   2.3333333\n3304   7.0000000\n3305  -4.0000000\n3306  -2.0000000\n3307  -1.0000000\n3308  -1.3333333\n3309   0.0000000\n3310  -3.6666667\n3311   1.6666667\n3312   3.3333333\n3313   4.6666667\n3314  -3.6666667\n3315  -0.6666667\n3316   0.0000000\n3317  -2.6666667\n3318  -0.3333333\n3319   6.3333333\n3320   0.3333333\n3321   2.6666667\n3322   0.0000000\n3323   3.0000000\n3324   4.0000000\n3325  -2.6666667\n3326   6.0000000\n3327  -3.0000000\n3328   6.6666667\n3329   6.0000000\n3330   2.6666667\n3331   3.3333333\n3332   6.3333333\n3333   0.0000000\n3334   4.3333333\n3335   2.6666667\n3336   5.3333333\n3337   2.3333333\n3338   5.0000000\n3339   4.0000000\n3340   2.6666667\n3341  -7.3333333\n3342   3.3333333\n3343  -3.3333333\n3344   5.0000000\n3345   0.6666667\n3346  -2.3333333\n3347   1.6666667\n3348  -3.3333333\n3349  -4.6666667\n3350  -5.3333333\n3351  -6.0000000\n3352   8.0000000\n3353   0.6666667\n3354   3.3333333\n3355  -1.3333333\n3356   7.3333333\n3357  -3.0000000\n3358  -3.6666667\n3359  -5.3333333\n3360  -0.6666667\n3361   3.3333333\n3362   2.0000000\n3363  -1.6666667\n3364   6.0000000\n3365  -2.0000000\n3366   6.6666667\n3367   1.3333333\n3368  -5.6666667\n3369  -3.0000000\n3370  -2.0000000\n3371   0.3333333\n3372  -0.3333333\n3373   2.6666667\n3374  -2.3333333\n3375  -7.0000000\n3376  -4.6666667\n3377  -2.6666667\n3378  -6.0000000\n3379  -9.0000000\n3380   0.6666667\n3381  -0.3333333\n3382   5.3333333\n3383  -1.6666667\n3384   1.0000000\n3385   0.6666667\n3386  -8.0000000\n3387  -2.6666667\n3388   5.3333333\n3389   3.6666667\n3390  -5.6666667\n3391  -1.6666667\n3392  -9.0000000\n3393  -4.6666667\n3394   3.3333333\n3395  -1.0000000\n3396  -1.3333333\n3397  -4.3333333\n3398   9.0000000\n3399  -6.0000000\n3400  -4.6666667\n3401   0.6666667\n3402   1.0000000\n3403   5.6666667\n3404   2.0000000\n3405   1.0000000\n3406  -4.0000000\n3407   4.6666667\n3408  -3.3333333\n3409   0.0000000\n3410   2.3333333\n3411  -0.6666667\n3412 -10.6666667\n3413   4.3333333\n3414   3.3333333\n3415  -1.3333333\n3416  -1.0000000\n3417  -9.0000000\n3418   1.6666667\n3419   3.6666667\n3420   2.6666667\n3421  -3.3333333\n3422   1.0000000\n3423   1.6666667\n3424   0.0000000\n3425  -3.6666667\n3426  -4.0000000\n3427   0.0000000\n3428  -3.3333333\n3429   4.0000000\n3430   2.0000000\n3431   5.3333333\n3432  -5.6666667\n3433   9.0000000\n3434   4.6666667\n3435  -2.3333333\n3436  -4.3333333\n3437  -8.3333333\n3438  -1.0000000\n3439  -1.3333333\n3440   8.6666667\n3441  -1.3333333\n3442  -0.3333333\n3443  -2.6666667\n3444  10.0000000\n3445   2.0000000\n3446   5.0000000\n3447  -1.3333333\n3448   2.6666667\n3449  -2.6666667\n3450   0.6666667\n3451   9.3333333\n3452   3.3333333\n3453   5.6666667\n3454  -0.3333333\n3455  -4.3333333\n3456   0.0000000\n3457  -3.0000000\n3458   2.0000000\n3459   1.6666667\n3460   3.6666667\n3461  -6.0000000\n3462   8.0000000\n3463   7.3333333\n3464   3.3333333\n3465  -5.0000000\n3466   2.3333333\n3467   1.6666667\n3468  -6.0000000\n3469   4.6666667\n3470   2.3333333\n3471  -3.0000000\n3472   6.3333333\n3473   1.3333333\n3474  -3.6666667\n3475  -4.6666667\n3476  -1.0000000\n3477  -1.0000000\n3478  -1.6666667\n3479   4.3333333\n3480  -9.6666667\n3481   1.6666667\n3482   0.0000000\n3483   0.3333333\n3484  -1.3333333\n3485  -1.3333333\n3486  -4.6666667\n3487  -5.6666667\n3488   5.0000000\n3489  -1.6666667\n3490  -3.6666667\n3491  -6.3333333\n3492  -6.0000000\n3493  -0.6666667\n3494  -1.6666667\n3495   0.0000000\n3496  -1.3333333\n3497  -7.6666667\n3498  -5.0000000\n3499   5.3333333\n3500   6.3333333\n3501  -1.0000000\n3502 -10.3333333\n3503   0.0000000\n3504   1.3333333\n3505   4.3333333\n3506   0.3333333\n3507   1.6666667\n3508  -0.3333333\n3509  -4.6666667\n3510  -2.3333333\n3511  -5.0000000\n3512   5.3333333\n3513   0.0000000\n3514  -5.3333333\n3515   4.0000000\n3516  -0.6666667\n3517  -1.6666667\n3518   1.6666667\n3519   6.6666667\n3520   3.6666667\n3521   0.0000000\n3522   6.6666667\n3523  -3.0000000\n3524  -2.6666667\n3525   1.6666667\n3526   1.0000000\n3527  -2.0000000\n3528  -2.3333333\n3529   3.3333333\n3530   5.6666667\n3531   2.3333333\n3532   3.0000000\n3533  -8.3333333\n3534  -1.3333333\n3535   2.3333333\n3536   2.3333333\n3537  -2.6666667\n3538   7.0000000\n3539  -1.6666667\n3540   2.6666667\n3541  -1.3333333\n3542   6.3333333\n3543  -6.0000000\n3544   8.6666667\n3545  -8.3333333\n3546  -3.6666667\n3547  -5.0000000\n3548  -2.0000000\n3549   1.6666667\n3550  -7.0000000\n3551   2.0000000\n3552   4.6666667\n3553  -1.3333333\n3554  -8.0000000\n3555  -5.3333333\n3556   0.6666667\n3557  -6.0000000\n3558   4.0000000\n3559   0.0000000\n3560  -3.3333333\n3561   6.6666667\n3562  -2.6666667\n3563  -0.3333333\n3564   3.0000000\n3565   0.3333333\n3566   4.0000000\n3567  11.6666667\n3568   4.6666667\n3569   8.0000000\n3570   7.3333333\n3571  -7.6666667\n3572   5.6666667\n3573  -3.3333333\n3574  -1.0000000\n3575   5.0000000\n3576   4.6666667\n3577   6.0000000\n3578  -2.3333333\n3579   1.6666667\n3580   1.6666667\n3581  -2.6666667\n3582   2.0000000\n3583   2.6666667\n3584  -4.0000000\n3585   2.6666667\n3586  -3.3333333\n3587  -7.6666667\n3588  -5.3333333\n3589   3.6666667\n3590   4.0000000\n3591   2.3333333\n3592  -3.3333333\n3593   0.3333333\n3594  -2.6666667\n3595   5.0000000\n3596  -5.0000000\n3597  -1.0000000\n3598   4.0000000\n3599   4.3333333\n3600  -3.3333333\n3601   1.6666667\n3602   5.6666667\n3603   0.6666667\n3604   3.6666667\n3605   3.3333333\n3606   4.0000000\n3607   0.3333333\n3608   0.0000000\n3609  -3.0000000\n3610  -1.6666667\n3611  -3.3333333\n3612   8.6666667\n3613   4.3333333\n3614   5.0000000\n3615   2.6666667\n3616  -1.6666667\n3617  -3.6666667\n3618  -4.0000000\n3619   3.0000000\n3620  -9.6666667\n3621   3.0000000\n3622   0.6666667\n3623  -2.3333333\n3624  -4.6666667\n3625  -0.3333333\n3626   1.3333333\n3627  -5.6666667\n3628  -6.6666667\n3629   2.0000000\n3630  -1.3333333\n3631  -2.0000000\n3632   3.3333333\n3633   7.3333333\n3634   1.6666667\n3635   2.0000000\n3636  -7.3333333\n3637   2.3333333\n3638  -2.3333333\n3639  -3.6666667\n3640   3.6666667\n3641   9.6666667\n3642  -1.6666667\n3643   2.6666667\n3644  -7.6666667\n3645  -2.3333333\n3646   2.6666667\n3647  -7.6666667\n3648  -7.6666667\n3649   5.6666667\n3650   4.3333333\n3651   1.0000000\n3652   0.6666667\n3653   3.3333333\n3654  -6.3333333\n3655   1.0000000\n3656  -7.6666667\n3657   5.3333333\n3658  -3.0000000\n3659   2.0000000\n3660   1.3333333\n3661  -0.6666667\n3662  -4.6666667\n3663   5.0000000\n3664  -2.3333333\n3665   2.6666667\n3666   1.0000000\n3667   4.0000000\n3668  -2.0000000\n3669   2.6666667\n3670  -0.3333333\n3671   2.6666667\n3672  -1.6666667\n3673   1.6666667\n3674   3.6666667\n3675  -5.6666667\n3676  -3.0000000\n3677  -0.6666667\n3678   1.3333333\n3679   0.3333333\n3680  -6.3333333\n3681  -0.3333333\n3682  -4.6666667\n3683  -2.0000000\n3684  -3.6666667\n3685  -1.3333333\n3686   2.3333333\n3687   1.3333333\n3688  -2.3333333\n3689   1.0000000\n3690  -2.3333333\n3691  -3.0000000\n3692  -3.6666667\n3693   8.6666667\n3694  -0.3333333\n3695   4.3333333\n3696   3.3333333\n3697   1.0000000\n3698   6.6666667\n3699   7.3333333\n3700  -4.3333333\n3701  -2.0000000\n3702  -3.3333333\n3703   3.6666667\n3704   5.0000000\n3705  -6.3333333\n3706  -2.3333333\n3707  -4.6666667\n3708  -2.3333333\n3709   4.6666667\n3710   7.0000000\n3711   2.0000000\n3712   6.6666667\n3713  -2.0000000\n3714   5.6666667\n3715   0.3333333\n3716  -1.6666667\n3717  -3.3333333\n3718   0.3333333\n3719  -3.0000000\n3720   2.6666667\n3721   4.3333333\n3722   3.0000000\n3723   4.6666667\n3724  -9.6666667\n3725   0.6666667\n3726  -3.6666667\n3727   1.6666667\n3728  -4.6666667\n3729   7.6666667\n3730   4.3333333\n3731 -13.6666667\n3732  -6.6666667\n3733   3.3333333\n3734   3.3333333\n3735  11.0000000\n3736   1.3333333\n3737   3.0000000\n3738  -2.6666667\n3739   3.6666667\n3740   1.6666667\n3741   1.6666667\n3742  -3.3333333\n3743   4.0000000\n3744   6.3333333\n3745  -6.6666667\n3746   3.3333333\n3747  -3.0000000\n3748   5.0000000\n3749   5.0000000\n3750  -0.3333333\n3751   7.3333333\n3752  -4.0000000\n3753   1.6666667\n3754  -3.3333333\n3755  -4.0000000\n3756   1.3333333\n3757  -9.3333333\n3758  -8.0000000\n3759   6.3333333\n3760   3.6666667\n3761   3.6666667\n3762   6.6666667\n3763   0.0000000\n3764  -6.3333333\n3765  -4.6666667\n3766   0.0000000\n3767   6.0000000\n3768   4.3333333\n3769   3.0000000\n3770   6.0000000\n3771  -1.3333333\n3772  -3.0000000\n3773   3.6666667\n3774   2.0000000\n3775   3.3333333\n3776   4.0000000\n3777   1.6666667\n3778  -4.6666667\n3779   3.0000000\n3780   3.3333333\n3781   5.3333333\n3782  -4.6666667\n3783  11.6666667\n3784   6.0000000\n3785   6.0000000\n3786 -10.0000000\n3787   2.3333333\n3788 -11.3333333\n3789  -0.6666667\n3790   6.6666667\n3791   1.3333333\n3792   2.6666667\n3793  -4.6666667\n3794   4.6666667\n3795  -1.6666667\n3796   0.6666667\n3797   6.0000000\n3798  -2.6666667\n3799   6.0000000\n3800   3.6666667\n3801   6.3333333\n3802  -6.6666667\n3803  -1.0000000\n3804  -0.6666667\n3805   0.6666667\n3806   3.0000000\n3807   5.3333333\n3808   0.0000000\n3809  -5.6666667\n3810  -1.3333333\n3811  -2.6666667\n3812   5.0000000\n3813   1.3333333\n3814   0.0000000\n3815  -2.6666667\n3816  -6.3333333\n3817  -5.6666667\n3818   3.0000000\n3819   6.3333333\n3820  -2.0000000\n3821   1.0000000\n3822  -0.6666667\n3823   4.0000000\n3824  -3.6666667\n3825   2.6666667\n3826   6.6666667\n3827  -5.0000000\n3828   6.3333333\n3829   1.3333333\n3830  -8.3333333\n3831   5.0000000\n3832  -1.0000000\n3833  -0.6666667\n3834   1.0000000\n3835  -1.6666667\n3836  -0.6666667\n3837  -1.6666667\n3838   2.0000000\n3839   7.6666667\n3840   3.3333333\n3841  -3.6666667\n3842   4.3333333\n3843   6.3333333\n3844  -5.0000000\n3845   1.3333333\n3846  -6.3333333\n3847   6.6666667\n3848  -6.0000000\n3849  -2.6666667\n3850  -4.3333333\n3851   1.6666667\n3852  -2.3333333\n3853  -8.6666667\n3854   4.6666667\n3855   0.6666667\n3856  -4.0000000\n3857   0.3333333\n3858   4.6666667\n3859   0.0000000\n3860   8.3333333\n3861  -1.3333333\n3862  -8.0000000\n3863   1.6666667\n3864  10.3333333\n3865 -10.3333333\n3866   3.0000000\n3867   1.0000000\n3868  -0.6666667\n3869   4.6666667\n3870   3.6666667\n3871   3.0000000\n3872  -1.6666667\n3873  -2.3333333\n3874   1.3333333\n3875  -6.0000000\n3876  -7.3333333\n3877   8.0000000\n3878  -3.3333333\n3879  -4.3333333\n3880   2.3333333\n3881  -6.0000000\n3882  -2.3333333\n3883   4.3333333\n3884   2.0000000\n3885  -3.6666667\n3886  -2.3333333\n3887  -3.6666667\n3888  -1.6666667\n3889   8.6666667\n3890   0.6666667\n3891   1.3333333\n3892  -6.3333333\n3893   7.0000000\n3894   4.3333333\n3895  -4.6666667\n3896  -2.3333333\n3897  10.0000000\n3898  -1.3333333\n3899  -6.3333333\n3900  -1.3333333\n3901   3.6666667\n3902  -2.6666667\n3903   8.0000000\n3904  -2.0000000\n3905   2.0000000\n3906  -0.3333333\n3907   4.3333333\n3908  10.6666667\n3909  -0.3333333\n3910  -4.3333333\n3911   5.0000000\n3912  -8.0000000\n3913   3.6666667\n3914  -1.3333333\n3915   6.3333333\n3916   6.3333333\n3917 -11.0000000\n3918   6.0000000\n3919   1.6666667\n3920   6.0000000\n3921  -4.6666667\n3922  -3.0000000\n3923  -1.6666667\n3924  -1.6666667\n3925   3.3333333\n3926 -12.0000000\n3927  -0.6666667\n3928   2.0000000\n3929  -3.0000000\n3930  -5.3333333\n3931  -6.6666667\n3932   5.6666667\n3933  -2.6666667\n3934  -1.3333333\n3935   0.3333333\n3936   7.6666667\n3937   6.0000000\n3938  -2.6666667\n3939  -7.3333333\n3940  -3.3333333\n3941  -7.6666667\n3942  -3.6666667\n3943  -1.6666667\n3944   6.0000000\n3945   2.0000000\n3946   3.0000000\n3947   5.6666667\n3948   1.0000000\n3949  10.6666667\n3950   1.3333333\n3951   0.6666667\n3952  -3.6666667\n3953  -6.6666667\n3954  -1.6666667\n3955  -4.3333333\n3956   6.0000000\n3957   1.3333333\n3958   5.0000000\n3959   3.0000000\n3960  -7.3333333\n3961   0.6666667\n3962   5.6666667\n3963   5.0000000\n3964   1.3333333\n3965  -6.3333333\n3966  -2.6666667\n3967  -2.0000000\n3968  -5.3333333\n3969  -2.6666667\n3970   5.6666667\n3971  -0.6666667\n3972   1.3333333\n3973  -0.6666667\n3974  -5.0000000\n3975   2.6666667\n3976  -6.0000000\n3977   0.6666667\n3978   2.0000000\n3979   1.3333333\n3980  10.0000000\n3981  -1.3333333\n3982   6.6666667\n3983   0.3333333\n3984   7.3333333\n3985  -3.3333333\n3986  -3.3333333\n3987  -1.3333333\n3988   2.3333333\n3989  11.3333333\n3990   6.6666667\n3991  -0.6666667\n3992   0.3333333\n3993  -5.6666667\n3994   1.0000000\n3995  -0.3333333\n3996   0.6666667\n3997   0.3333333\n3998  -6.3333333\n3999   1.6666667\n4000   8.3333333\n4001   3.3333333\n4002   8.6666667\n4003  -3.0000000\n4004   5.3333333\n4005  -3.3333333\n4006   6.6666667\n4007  -1.3333333\n4008   7.0000000\n4009  -8.6666667\n4010  -1.3333333\n4011  -2.6666667\n4012   4.6666667\n4013  -3.3333333\n4014   3.3333333\n4015   0.6666667\n4016   5.3333333\n4017  -5.0000000\n4018   5.0000000\n4019  -4.3333333\n4020   2.3333333\n4021  -7.3333333\n4022   0.0000000\n4023  -6.6666667\n4024  -7.0000000\n4025  -7.0000000\n4026  -2.6666667\n4027  -0.3333333\n4028  -5.3333333\n4029   7.6666667\n4030   0.0000000\n4031  -5.0000000\n4032  -7.6666667\n4033  -8.6666667\n4034  -4.6666667\n4035  -1.3333333\n4036   4.6666667\n4037   4.0000000\n4038  -2.0000000\n4039 -11.0000000\n4040   1.6666667\n4041   1.0000000\n4042  -1.3333333\n4043   2.0000000\n4044  -4.6666667\n4045  -0.6666667\n4046  -1.6666667\n4047   0.3333333\n4048   0.6666667\n4049   2.3333333\n4050   0.3333333\n4051   5.3333333\n4052  -3.6666667\n4053   1.0000000\n4054  -6.6666667\n4055   3.0000000\n4056  -7.0000000\n4057  -3.6666667\n4058   5.6666667\n4059  -2.0000000\n4060   7.6666667\n4061  -2.0000000\n4062  -2.0000000\n4063  -7.3333333\n4064  -4.0000000\n4065   1.3333333\n4066  -3.0000000\n4067  -5.0000000\n4068  -3.6666667\n4069  -3.6666667\n4070   2.0000000\n4071  -1.0000000\n4072  -1.6666667\n4073  13.3333333\n4074  -2.0000000\n4075   2.3333333\n4076  -6.3333333\n4077   1.3333333\n4078   3.6666667\n4079  -0.3333333\n4080  -6.6666667\n4081  -0.6666667\n4082   6.3333333\n4083   2.6666667\n4084   8.0000000\n4085  -3.0000000\n4086   4.0000000\n4087  -2.0000000\n4088   5.0000000\n4089   8.0000000\n4090   3.6666667\n4091  -7.6666667\n4092   0.3333333\n4093  -4.0000000\n4094   1.6666667\n4095  -0.6666667\n4096   6.3333333\n4097  -5.6666667\n4098   0.0000000\n4099  -6.6666667\n4100  -0.6666667\n4101  -3.6666667\n4102   3.0000000\n4103   1.0000000\n4104   6.6666667\n4105  -2.6666667\n4106  -5.3333333\n4107   7.6666667\n4108  -4.3333333\n4109   6.6666667\n4110   1.0000000\n4111  -2.6666667\n4112   6.0000000\n4113   5.6666667\n4114   8.3333333\n4115   4.6666667\n4116  -2.3333333\n4117  -8.0000000\n4118  -3.3333333\n4119   0.6666667\n4120   0.0000000\n4121   0.0000000\n4122  -4.6666667\n4123   9.3333333\n4124  -2.0000000\n4125   4.3333333\n4126  -5.0000000\n4127  -2.0000000\n4128  -3.6666667\n4129  -8.0000000\n4130  -4.3333333\n4131   1.3333333\n4132  -7.6666667\n4133  -1.3333333\n4134   7.3333333\n4135  -0.6666667\n4136  -2.3333333\n4137  12.3333333\n4138  -3.0000000\n4139  -2.6666667\n4140   1.6666667\n4141  -3.6666667\n4142  -9.3333333\n4143   1.6666667\n4144   1.3333333\n4145  -6.6666667\n4146  -3.6666667\n4147  -2.3333333\n4148   1.6666667\n4149   3.6666667\n4150   8.6666667\n4151   1.0000000\n4152   3.6666667\n4153  -3.6666667\n4154  -2.0000000\n4155   4.0000000\n4156   0.3333333\n4157   2.3333333\n4158   7.0000000\n4159  -3.3333333\n4160  -5.6666667\n4161  -6.6666667\n4162  -5.6666667\n4163   8.0000000\n4164   0.3333333\n4165   3.3333333\n4166   1.0000000\n4167   4.0000000\n4168  -1.0000000\n4169   6.0000000\n4170  -1.3333333\n4171   6.6666667\n4172   0.6666667\n4173  -3.3333333\n4174  -0.6666667\n4175  -2.6666667\n4176  -4.6666667\n4177  -8.3333333\n4178   3.6666667\n4179   3.6666667\n4180  -1.6666667\n4181  10.0000000\n4182  -4.3333333\n4183   2.0000000\n4184  -0.6666667\n4185  -1.0000000\n4186  -6.0000000\n4187  -0.6666667\n4188   1.3333333\n4189   1.6666667\n4190   2.6666667\n4191  -6.0000000\n4192  -2.6666667\n4193  -3.3333333\n4194   5.6666667\n4195   0.3333333\n4196  -4.3333333\n4197   7.6666667\n4198   6.0000000\n4199   3.6666667\n4200  -3.0000000\n4201   0.6666667\n4202  11.3333333\n4203  -1.6666667\n4204  -7.3333333\n4205  -6.3333333\n4206   1.6666667\n4207   2.6666667\n4208  -0.3333333\n4209  -3.6666667\n4210  -1.3333333\n4211   1.3333333\n4212   4.6666667\n4213  -5.6666667\n4214  -3.0000000\n4215   2.6666667\n4216   3.0000000\n4217   9.6666667\n4218   0.3333333\n4219  -2.0000000\n4220  -2.3333333\n4221  -9.6666667\n4222  -2.6666667\n4223   3.0000000\n4224   1.0000000\n4225   4.0000000\n4226  -2.0000000\n4227  -1.6666667\n4228  -2.6666667\n4229  -4.3333333\n4230  -4.0000000\n4231  10.6666667\n4232  -7.6666667\n4233   5.0000000\n4234   1.0000000\n4235   0.3333333\n4236   8.0000000\n4237  -7.0000000\n4238   6.0000000\n4239  -4.0000000\n4240   0.6666667\n4241  -3.3333333\n4242  -2.0000000\n4243   6.3333333\n4244   2.3333333\n4245   2.0000000\n4246 -11.3333333\n4247  -2.3333333\n4248  -2.6666667\n4249   2.3333333\n4250   2.0000000\n4251  -0.3333333\n4252  -4.3333333\n4253   6.6666667\n4254  -2.6666667\n4255   3.0000000\n4256   5.0000000\n4257 -12.0000000\n4258   3.0000000\n4259   7.0000000\n4260  -8.3333333\n4261   2.0000000\n4262  -8.3333333\n4263   2.6666667\n4264   5.3333333\n4265  -7.6666667\n4266   2.0000000\n4267   2.0000000\n4268  -3.6666667\n4269  -2.0000000\n4270  -8.3333333\n4271   2.6666667\n4272   4.0000000\n4273   1.3333333\n4274  -4.6666667\n4275  -5.6666667\n4276   1.3333333\n4277   0.3333333\n4278   4.3333333\n4279  -1.3333333\n4280  -4.0000000\n4281  -5.6666667\n4282  -2.0000000\n4283  -4.6666667\n4284   1.3333333\n4285   7.6666667\n4286   4.3333333\n4287  -3.6666667\n4288  -2.3333333\n4289   1.6666667\n4290  -0.3333333\n4291   2.6666667\n4292  -2.3333333\n4293   2.0000000\n4294   6.0000000\n4295  -4.0000000\n4296   7.3333333\n4297  -2.0000000\n4298   7.3333333\n4299  -1.3333333\n4300   3.6666667\n4301   4.0000000\n4302   5.6666667\n4303  -7.0000000\n4304   8.3333333\n4305  -0.6666667\n4306   3.0000000\n4307   3.3333333\n4308   0.3333333\n4309  -0.6666667\n4310  -1.3333333\n4311  -3.3333333\n4312   4.0000000\n4313   7.3333333\n4314  -0.6666667\n4315  -0.3333333\n4316  -0.6666667\n4317   1.0000000\n4318   2.3333333\n4319  -0.6666667\n4320  -3.0000000\n4321  -3.0000000\n4322   0.3333333\n4323   6.6666667\n4324   2.0000000\n4325  -3.6666667\n4326  -5.3333333\n4327  -4.0000000\n4328   3.6666667\n4329   0.0000000\n4330  -2.6666667\n4331   2.3333333\n4332   0.3333333\n4333  -4.0000000\n4334   2.0000000\n4335  -2.6666667\n4336   4.6666667\n4337   8.3333333\n4338   5.0000000\n4339   4.0000000\n4340  -3.6666667\n4341   0.6666667\n4342   1.0000000\n4343   2.6666667\n4344  -2.0000000\n4345   4.3333333\n4346   4.0000000\n4347   2.0000000\n4348   2.0000000\n4349   5.3333333\n4350  -3.0000000\n4351  -7.3333333\n4352  -2.3333333\n4353   3.0000000\n4354   0.3333333\n4355  -2.6666667\n4356   2.0000000\n4357  -5.0000000\n4358   5.3333333\n4359   2.0000000\n4360   7.0000000\n4361   3.3333333\n4362  -0.6666667\n4363   2.3333333\n4364   4.0000000\n4365   4.3333333\n4366   0.0000000\n4367   3.0000000\n4368  13.0000000\n4369  -3.3333333\n4370  -2.0000000\n4371   6.3333333\n4372  -5.6666667\n4373   1.0000000\n4374   1.3333333\n4375  -5.0000000\n4376  -0.3333333\n4377   0.3333333\n4378  -1.3333333\n4379   8.3333333\n4380   3.0000000\n4381   5.6666667\n4382   2.6666667\n4383   5.6666667\n4384   2.0000000\n4385   4.6666667\n4386  -3.3333333\n4387  -1.0000000\n4388   3.3333333\n4389   5.3333333\n4390  -5.0000000\n4391   5.3333333\n4392  -1.0000000\n4393  -2.3333333\n4394  -4.6666667\n4395   5.6666667\n4396  -5.0000000\n4397  -0.3333333\n4398  -4.6666667\n4399   5.3333333\n4400  -5.0000000\n4401   2.0000000\n4402   3.6666667\n4403   3.0000000\n4404  -2.6666667\n4405   1.3333333\n4406   5.0000000\n4407   3.0000000\n4408   1.6666667\n4409   3.3333333\n4410   6.0000000\n4411  -5.3333333\n4412   4.3333333\n4413   2.6666667\n4414  -5.0000000\n4415  -0.3333333\n4416   7.0000000\n4417   3.0000000\n4418   2.3333333\n4419   7.3333333\n4420  -2.3333333\n4421   1.6666667\n4422  -1.3333333\n4423  -8.6666667\n4424   3.0000000\n4425   6.0000000\n4426   1.0000000\n4427   2.0000000\n4428  -7.6666667\n4429   8.3333333\n4430  -2.0000000\n4431  -0.6666667\n4432  -6.0000000\n4433   5.0000000\n4434   6.6666667\n4435   7.0000000\n4436   8.3333333\n4437   1.0000000\n4438   3.0000000\n4439  -1.0000000\n4440  -0.3333333\n4441  -7.3333333\n4442  -9.0000000\n4443   7.3333333\n4444   6.3333333\n4445  -0.6666667\n4446   5.0000000\n4447   4.3333333\n4448  -2.6666667\n4449  -6.3333333\n4450  -5.3333333\n4451  -1.0000000\n4452  -1.6666667\n4453  -6.3333333\n4454  -3.0000000\n4455  -0.3333333\n4456   4.3333333\n4457   2.3333333\n4458   5.6666667\n4459  -0.6666667\n4460   1.6666667\n4461  -2.6666667\n4462  -0.6666667\n4463   0.0000000\n4464  -3.0000000\n4465   5.0000000\n4466 -10.3333333\n4467  -4.6666667\n4468  -2.0000000\n4469   5.0000000\n4470  -0.6666667\n4471   5.6666667\n4472  -3.3333333\n4473   1.6666667\n4474  -2.0000000\n4475  -0.3333333\n4476  -4.6666667\n4477  -7.0000000\n4478   4.0000000\n4479   1.0000000\n4480  11.0000000\n4481   7.3333333\n4482  -9.0000000\n4483  -5.6666667\n4484   3.0000000\n4485  -4.6666667\n4486  -3.3333333\n4487   4.0000000\n4488  -3.3333333\n4489   0.3333333\n4490  -1.3333333\n4491   1.0000000\n4492   0.0000000\n4493   3.0000000\n4494  -0.3333333\n4495   2.3333333\n4496   7.3333333\n4497   0.3333333\n4498   0.0000000\n4499   0.6666667\n4500   0.6666667\n4501   2.0000000\n4502   1.3333333\n4503   0.0000000\n4504   5.0000000\n4505  -1.3333333\n4506   4.3333333\n4507  -0.6666667\n4508   5.0000000\n4509  -7.6666667\n4510  -4.0000000\n4511   1.6666667\n4512  -5.6666667\n4513   3.6666667\n4514   2.0000000\n4515   5.3333333\n4516   0.6666667\n4517   7.3333333\n4518   3.3333333\n4519   8.0000000\n4520   0.6666667\n4521   3.0000000\n4522  -0.6666667\n4523   1.6666667\n4524  -3.3333333\n4525 -10.3333333\n4526   2.3333333\n4527  -2.3333333\n4528   9.0000000\n4529   4.3333333\n4530  -9.3333333\n4531 -10.0000000\n4532  -4.6666667\n4533   6.3333333\n4534  -1.3333333\n4535  -5.0000000\n4536   1.0000000\n4537   1.0000000\n4538  -2.6666667\n4539  -6.3333333\n4540  15.0000000\n4541   1.0000000\n4542   5.0000000\n4543   3.3333333\n4544  -0.3333333\n4545   4.3333333\n4546  -1.0000000\n4547   0.3333333\n4548  -3.0000000\n4549   0.0000000\n4550   3.0000000\n4551  -1.3333333\n4552   3.0000000\n4553  -8.3333333\n4554  -1.0000000\n4555   2.6666667\n4556   0.6666667\n4557   4.3333333\n4558  -1.6666667\n4559  -4.0000000\n4560   9.3333333\n4561   7.6666667\n4562   6.3333333\n4563  -9.6666667\n4564  -4.3333333\n4565   2.3333333\n4566   7.6666667\n4567  -4.3333333\n4568   2.3333333\n4569   3.0000000\n4570  -1.0000000\n4571   1.6666667\n4572   1.0000000\n4573   5.0000000\n4574  -9.0000000\n4575   1.3333333\n4576   0.3333333\n4577  -2.3333333\n4578   5.0000000\n4579   2.6666667\n4580  -7.0000000\n4581  -3.0000000\n4582  -5.0000000\n4583   0.3333333\n4584   3.3333333\n4585   2.3333333\n4586   1.6666667\n4587  -7.0000000\n4588   2.0000000\n4589   6.0000000\n4590  -0.3333333\n4591   1.0000000\n4592  -0.3333333\n4593   2.3333333\n4594   5.3333333\n4595  -5.6666667\n4596   0.0000000\n4597  -4.3333333\n4598   7.3333333\n4599  -2.3333333\n4600   6.0000000\n4601   5.3333333\n4602   0.6666667\n4603  -3.0000000\n4604   6.6666667\n4605   0.3333333\n4606   2.6666667\n4607   0.6666667\n4608   2.0000000\n4609  -0.6666667\n4610   5.3333333\n4611   6.0000000\n4612   6.0000000\n4613   1.0000000\n4614  -1.3333333\n4615  -1.0000000\n4616   4.6666667\n4617  -3.6666667\n4618  -2.0000000\n4619   0.0000000\n4620  -3.6666667\n4621  -3.0000000\n4622  -4.0000000\n4623  -3.0000000\n4624  -4.3333333\n4625  -8.0000000\n4626   0.0000000\n4627   0.6666667\n4628   0.0000000\n4629   2.0000000\n4630   2.0000000\n4631   3.6666667\n4632  -4.3333333\n4633   0.6666667\n4634   4.0000000\n4635  -4.0000000\n4636  -5.6666667\n4637  -0.3333333\n4638  11.3333333\n4639  -2.0000000\n4640   3.6666667\n4641  -2.0000000\n4642   5.3333333\n4643   1.3333333\n4644  -3.6666667\n4645   6.6666667\n4646   7.3333333\n4647  -4.0000000\n4648  -3.0000000\n4649   0.3333333\n4650 -11.3333333\n4651   0.6666667\n4652   6.3333333\n4653  -1.3333333\n4654   0.3333333\n4655  -4.0000000\n4656  -8.6666667\n4657  -6.0000000\n4658   2.3333333\n4659   0.3333333\n4660  -0.6666667\n4661   1.3333333\n4662   5.3333333\n4663   1.0000000\n4664  -2.6666667\n4665   2.6666667\n4666   7.6666667\n4667   6.3333333\n4668   2.3333333\n4669   0.3333333\n4670  -5.0000000\n4671   4.0000000\n4672   6.6666667\n4673   0.3333333\n4674   3.3333333\n4675  -1.6666667\n4676   1.3333333\n4677   1.3333333\n4678   1.6666667\n4679  -2.6666667\n4680   1.3333333\n4681  -2.0000000\n4682   3.3333333\n4683   6.3333333\n4684  -4.0000000\n4685  -9.3333333\n4686   3.0000000\n4687  -6.3333333\n4688   2.3333333\n4689  -3.3333333\n4690   6.0000000\n4691   2.6666667\n4692 -12.3333333\n4693   5.0000000\n4694   3.0000000\n4695   4.3333333\n4696  -1.6666667\n4697  -3.3333333\n4698  -1.0000000\n4699  -1.6666667\n4700   1.6666667\n4701  -2.6666667\n4702  -0.3333333\n4703  -2.3333333\n4704  -2.6666667\n4705   4.6666667\n4706   9.3333333\n4707   5.3333333\n4708  -4.0000000\n4709  -1.3333333\n4710  -6.6666667\n4711  -3.3333333\n4712   0.3333333\n4713   7.3333333\n4714   2.6666667\n4715  -2.6666667\n4716  -7.6666667\n4717  -1.3333333\n4718   2.6666667\n4719  -2.3333333\n4720  -3.0000000\n4721   0.3333333\n4722   3.3333333\n4723   5.3333333\n4724   3.0000000\n4725  -3.6666667\n4726  -0.6666667\n4727   8.3333333\n4728  -0.6666667\n4729  -5.3333333\n4730  -1.3333333\n4731   7.0000000\n4732  -6.6666667\n4733   5.3333333\n4734  -6.0000000\n4735   2.6666667\n4736   4.3333333\n4737   1.3333333\n4738  -4.0000000\n4739  -2.3333333\n4740   1.3333333\n4741   1.0000000\n4742  -0.3333333\n4743  -2.6666667\n4744   0.6666667\n4745   1.3333333\n4746  -9.6666667\n4747  -0.3333333\n4748   1.0000000\n4749  -8.6666667\n4750   0.6666667\n4751  -6.0000000\n4752   3.3333333\n4753   2.6666667\n4754  -6.6666667\n4755  -6.6666667\n4756   5.0000000\n4757  -3.0000000\n4758   1.0000000\n4759   2.0000000\n4760   2.0000000\n4761  -3.0000000\n4762   3.6666667\n4763  -5.3333333\n4764   3.3333333\n4765  -1.6666667\n4766   1.6666667\n4767   6.6666667\n4768  -4.3333333\n4769   0.6666667\n4770  -4.6666667\n4771  -0.3333333\n4772  -2.6666667\n4773  -4.3333333\n4774  -1.6666667\n4775   4.3333333\n4776   5.3333333\n4777   5.3333333\n4778   3.0000000\n4779   4.0000000\n4780   0.6666667\n4781   2.6666667\n4782  -2.3333333\n4783   5.3333333\n4784   1.0000000\n4785   5.6666667\n4786  -4.0000000\n4787  -1.6666667\n4788  -3.0000000\n4789   4.0000000\n4790  -1.6666667\n4791  -2.0000000\n4792  -1.3333333\n4793  -8.3333333\n4794   3.0000000\n4795  -3.6666667\n4796  -0.3333333\n4797   0.0000000\n4798  -2.0000000\n4799  -2.0000000\n4800  -5.0000000\n4801  10.0000000\n4802   1.3333333\n4803  -6.6666667\n4804   3.6666667\n4805  -0.6666667\n4806   6.0000000\n4807   4.0000000\n4808  -1.6666667\n4809  -1.3333333\n4810  -1.3333333\n4811  -5.3333333\n4812   3.3333333\n4813  -0.6666667\n4814  -8.6666667\n4815   9.3333333\n4816  -8.3333333\n4817   4.3333333\n4818  -1.0000000\n4819  -3.3333333\n4820   2.3333333\n4821  -7.3333333\n4822   3.3333333\n4823   1.3333333\n4824   0.3333333\n4825   5.0000000\n4826   1.3333333\n4827  -3.3333333\n4828  -1.6666667\n4829  -4.6666667\n4830   6.3333333\n4831  -4.3333333\n4832   3.0000000\n4833  -0.6666667\n4834   3.0000000\n4835  11.0000000\n4836   6.3333333\n4837   1.0000000\n4838  -2.0000000\n4839  -0.3333333\n4840   6.6666667\n4841   2.3333333\n4842   3.0000000\n4843  -0.6666667\n4844   4.0000000\n4845   5.3333333\n4846   7.6666667\n4847  -2.6666667\n4848   6.0000000\n4849   0.0000000\n4850   6.3333333\n4851  -8.0000000\n4852  -6.3333333\n4853   3.3333333\n4854  -5.6666667\n4855  -3.0000000\n4856  -5.3333333\n4857  -0.3333333\n4858  -4.0000000\n4859  -4.3333333\n4860  -2.0000000\n4861   8.0000000\n4862   1.3333333\n4863   2.0000000\n4864   3.3333333\n4865   2.6666667\n4866  -1.3333333\n4867   6.3333333\n4868  -3.0000000\n4869   0.0000000\n4870   0.3333333\n4871  -5.3333333\n4872  -6.3333333\n4873  -4.3333333\n4874  -3.3333333\n4875   0.0000000\n4876  -3.6666667\n4877   6.6666667\n4878   6.0000000\n4879   4.6666667\n4880  -0.6666667\n4881  -2.0000000\n4882  -0.3333333\n4883  -2.3333333\n4884   0.6666667\n4885  -6.6666667\n4886   5.6666667\n4887   5.3333333\n4888   6.6666667\n4889  -2.3333333\n4890  -1.6666667\n4891  -8.3333333\n4892  -0.3333333\n4893  -6.3333333\n4894  -1.6666667\n4895   3.3333333\n4896   7.0000000\n4897  -5.3333333\n4898  -3.0000000\n4899   0.0000000\n4900  -9.0000000\n4901   2.6666667\n4902   7.3333333\n4903   0.0000000\n4904  -4.3333333\n4905  -1.0000000\n4906  -0.6666667\n4907   1.3333333\n4908  -1.6666667\n4909   0.3333333\n4910   3.6666667\n4911   6.0000000\n4912  -7.6666667\n4913  -4.6666667\n4914   0.3333333\n4915   0.0000000\n4916  -1.6666667\n4917  -5.0000000\n4918   5.6666667\n4919  -1.3333333\n4920   3.0000000\n4921   0.6666667\n4922  -0.6666667\n4923   4.0000000\n4924   4.6666667\n4925   9.6666667\n4926   4.0000000\n4927  -7.6666667\n4928  -2.3333333\n4929   0.6666667\n4930   1.0000000\n4931  -5.6666667\n4932  -3.6666667\n4933  -2.0000000\n4934  -2.3333333\n4935  -0.6666667\n4936   6.0000000\n4937   1.0000000\n4938  -2.3333333\n4939  -1.6666667\n4940   6.6666667\n4941  -2.0000000\n4942  -0.6666667\n4943   6.0000000\n4944  -1.3333333\n4945   7.3333333\n4946  -2.6666667\n4947  -4.6666667\n4948  -4.6666667\n4949   0.3333333\n4950  -5.6666667\n4951   1.6666667\n4952   0.6666667\n4953   1.0000000\n4954  -7.6666667\n4955   3.0000000\n4956  -6.6666667\n4957  -0.3333333\n4958   2.3333333\n4959  -4.6666667\n4960   0.0000000\n4961   4.6666667\n4962  -0.6666667\n4963  -4.3333333\n4964   2.0000000\n4965   2.0000000\n4966  -2.3333333\n4967  -6.3333333\n4968  -9.0000000\n4969   4.6666667\n4970  -4.6666667\n4971  -4.3333333\n4972   3.6666667\n4973   2.6666667\n4974   2.0000000\n4975   2.3333333\n4976   0.0000000\n4977  -9.3333333\n4978  -2.0000000\n4979   7.0000000\n4980   9.0000000\n4981   3.0000000\n4982  -1.3333333\n4983  -3.3333333\n4984   0.0000000\n4985  -4.3333333\n4986   0.3333333\n4987  -8.3333333\n4988  -6.3333333\n4989  -8.3333333\n4990  -5.6666667\n4991   2.6666667\n4992  -1.3333333\n4993   6.3333333\n4994   1.6666667\n4995   3.0000000\n4996  -1.6666667\n4997  -7.0000000\n4998   4.0000000\n4999   1.6666667\n```\n\n\n:::\n\n```{.r .cell-code}\n#Everytime I run it, the values are different since the data is shuffled.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set graph theme\ntheme_set(new = theme_classic())\n#\ngf_histogram(data = null_dist_tip, ~ diffmean, bins = 25) %>%\n  gf_vline(xintercept = obs_diff_tip, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Histogram\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n###\ngf_ecdf(data = null_dist_tip, ~ diffmean, \n        linewidth = 1) %>%\n  gf_vline(xintercept = obs_diff_tip, \n           colour = \"red\", linewidth = 1,\n           title = \"Null Distribution by Permutation\", \n           subtitle = \"Cumulative Density\") %>% \n  gf_labs(x = \"Difference in Means\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\nInference:-\n\n-   The **histogram** shows the differences between the two groups (Veg and Non-veg) when the data is shuffled randomly. The red line shows the actual difference that was observed (-2.33).\n\n-   Since the red line falls in the middle of the random results,so the difference is not unusual- it could just be due to random chance.\n\n-   The **cumulative plot** (the second graph) backs this up. It shows that the observed difference is well within what I’d expect if there was no real difference.\n\n**Conclusion**: There's no strong evidence that the difference in tips between Veg and Non-veg preferences is meaningful, it could easily be due to chance. I initially thought the tips dataset might be useless because of the lack of significant differences between the groups. However, during class, i realised that even with no significant results, the data can still provide valuable insights into patterns and trends in tipping behavior. So, it's definitely not useless!\n:::\n\nsample data\\\nmean\\\nshapiro\\\nt-test\\\nif necessary winc\n\n<https://av-quarto.netlify.app/content/courses/analytics/inference/modules/110-twomeans/#observed-and-test-statistic>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}