<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gayatri Jadhav">

<title>A3 - Tips Dataset – My_OG_Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="../../site_libs/tabwid-1.1.3/tabwid.js"></script>



<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My_OG_Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A3 - Tips Dataset</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Gayatri Jadhav </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This dataset looks at <strong>tips</strong> left by restaurant customers and includes details like their <strong>gender</strong> and whether they prefer <strong>Veg</strong> or <strong>Non-Veg</strong> food. It helps see if there are any patterns, like whether people who eat certain types of food tip more or if certain groups tend to give bigger tips.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># Data Processing in R</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic) <span class="co"># Our workhorse for stats, sampling</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(crosstable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'crosstable'

The following object is masked from 'package:purrr':

    compact</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>tip <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../Data/tip.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 60 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Name, Gender, Preferance
dbl (1): Tip

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 60
Columns: 4
$ Name       &lt;chr&gt; "Aanya", "Adit", "Aditi", "Akash", "Akshita", "Anandita", "…
$ Gender     &lt;chr&gt; "Female", "Male", "Female", "Male", "Female", "Female", "Fe…
$ Preferance &lt;chr&gt; "Veg", "Veg", "Veg", "Non-veg", "Non-veg", "Non-veg", "Non-…
$ Tip        &lt;dbl&gt; 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crosstabulating the Tip variable against Preferance (categorical variable) to summarize the relationship</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This helped me understand how tips are distributed across the two preferences (Veg/Non-veg)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>tip <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">crosstable</span>(Tip <span class="sc">~</span> Preferance) <span class="sc">%&gt;%</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_flextable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-b3229e66{table-layout:auto;}.cl-b3148718{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b3148736{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b31d34b2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b31d34bc{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b31d5956{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d5960{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d596a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d596b{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b31d5974{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-b3229e66"><thead><tr style="overflow-wrap:break-word;"><th rowspan="2" class="cl-b31d5956"><p class="cl-b31d34b2"><span class="cl-b3148718">label</span></p></th><th rowspan="2" class="cl-b31d5956"><p class="cl-b31d34b2"><span class="cl-b3148718">variable</span></p></th><th colspan="2" class="cl-b31d5960"><p class="cl-b31d34b2"><span class="cl-b3148718">Preferance</span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-b31d596a"><p class="cl-b31d34b2"><span class="cl-b3148718">Non-veg</span></p></th><th class="cl-b31d596a"><p class="cl-b31d34b2"><span class="cl-b3148718">Veg</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td rowspan="4" class="cl-b31d596b"><p class="cl-b31d34bc"><span class="cl-b3148736">Tip</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">Min / Max</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">0 / 50.0</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">0 / 100.0</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">Med [IQR]</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">0 [0;20.0]</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">0 [0;20.0]</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">Mean (std)</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">10.0 (12.9)</span></p></td><td class="cl-b31d5974"><p class="cl-b31d34bc"><span class="cl-b3148736">12.3 (21.9)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-b31d596b"><p class="cl-b31d34bc"><span class="cl-b3148736">N (NA)</span></p></td><td class="cl-b31d596b"><p class="cl-b31d34bc"><span class="cl-b3148736">30 (0)</span></p></td><td class="cl-b31d596b"><p class="cl-b31d34bc"><span class="cl-b3148736">30 (0)</span></p></td></tr></tbody></table></div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutating by converting Gender and Preferance into factors</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>tips_modified <span class="ot">&lt;-</span> tip <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gender =</span> <span class="fu">as_factor</span>(Gender),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Preferance =</span> <span class="fu">as_factor</span>(Preferance)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tips_modified)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 60
Columns: 4
$ Name       &lt;chr&gt; "Aanya", "Adit", "Aditi", "Akash", "Akshita", "Anandita", "…
$ Gender     &lt;fct&gt; Female, Male, Female, Male, Female, Female, Female, Female,…
$ Preferance &lt;fct&gt; Veg, Veg, Veg, Non-veg, Non-veg, Non-veg, Non-veg, Veg, Veg…
$ Tip        &lt;dbl&gt; 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a histogram to see the distribution of Tips by Preferance</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tips_modified <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>Tip<span class="sc">|</span>Preferance, <span class="at">fill =</span> <span class="sc">~</span>Preferance,<span class="at">position=</span> <span class="st">"dodge"</span> ,<span class="at">data =</span> tips_modified) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Veg <span class="ot">&lt;-</span> tips_modified <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Preferance <span class="sc">==</span> <span class="st">"Veg"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Tip)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>Nonveg <span class="ot">&lt;-</span> tips_modified <span class="sc">%&gt;%</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Preferance <span class="sc">==</span> <span class="st">"Non-veg"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Tip)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Veg<span class="sc">$</span>Tip) <span class="co"># Performing the Shapiro-Wilk test for normality on the "Veg" group's Tip values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Veg$Tip
W = 0.6286, p-value = 1.661e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Nonveg<span class="sc">$</span>Tip)<span class="co"># Performing the Shapiro-Wilk test for normality on the "Non-veg" group's Tip values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Nonveg$Tip
W = 0.71661, p-value = 2.747e-06</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The p-values are extremely small, indicating that neither the Veg nor the Non-veg Tip data is normally distributed.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">t_test</span>( Tip <span class="sc">~</span> Preferance, <span class="at">data =</span> tips_modified ) <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     2.33      12.3        10     0.503   0.617      46.9    -6.99      11.7
# ℹ 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since neither the Veg nor Non-veg Tip data is normally distributed, using a t-test wouldn’t be the right choice. Instead, it’s better to use the <strong>Wilcoxon test</strong>, which is a non-parametric method that’s ideal for comparing the medians when the data isn’t normally distributed.</p>
</div>
</div>
<p>Splitting the dataset by Preferance into Veg and Nonveg groups-</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecting only the Tip column for further testing</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>tips_modified <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Preferance <span class="sc">==</span> <span class="st">"Veg"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Tip) <span class="ot">-&gt;</span> Veg</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the "Veg" group Tip values</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>Veg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 1
     Tip
   &lt;dbl&gt;
 1     0
 2     0
 3    20
 4    35
 5    40
 6     0
 7     0
 8     0
 9    15
10   100
# ℹ 20 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the Tip values for the "Non-veg" group</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>tips_modified <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Preferance <span class="sc">==</span> <span class="st">"Non-veg"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Tip) <span class="ot">-&gt;</span> Nonveg</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the "Non-veg" group Tip values</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>Nonveg </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 1
     Tip
   &lt;dbl&gt;
 1     0
 2     0
 3     0
 4    20
 5     0
 6     0
 7     0
 8     0
 9     0
10    20
# ℹ 20 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Tip <span class="sc">~</span> Preferance , <span class="at">data =</span> tips_modified) <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic p.value method                                           alternative
      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                                            &lt;chr&gt;      
1       437   0.833 Wilcoxon rank sum test with continuity correcti… two.sided  </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Wilcoxon test gave a result of 437 for the statistic and a <strong>p-value of 0.83</strong>. This high p-value means there’s no significant difference between the tips left by the Veg and Non-veg groups. IBoth groups leave about the same amount in tips.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>obs_diff_tip <span class="ot">&lt;-</span> <span class="fu">diffmean</span>( Tip <span class="sc">~</span> Preferance, <span class="at">data =</span> tips_modified) </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>obs_diff_tip</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> diffmean 
-2.333333 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>diffmean</strong> result is <strong>-2.33</strong>, which means that, on average, the Non-veg group left 2.33 less in tips than the Veg group. But because the Wilcoxon test has not showed any significant difference, this small difference doesn’t actually matter much.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating a null distribution for the difference in means through permutation testing (5000 permutations)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>null_dist_tip <span class="ot">&lt;-</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>(<span class="dv">4999</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(<span class="at">data =</span> tips_modified, Tip <span class="sc">~</span> <span class="fu">shuffle</span>(Preferance))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>null_dist_tip</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        diffmean
1     -1.6666667
2    -10.3333333
3     -8.3333333
4      3.0000000
5      2.0000000
6      1.3333333
7      7.0000000
8      7.3333333
9     -2.6666667
10    -1.3333333
11    -4.0000000
12    -5.6666667
13     0.0000000
14     5.6666667
15    -1.3333333
16    -1.3333333
17     4.3333333
18     6.3333333
19     3.3333333
20     2.3333333
21    -0.6666667
22    -3.0000000
23    -7.3333333
24    -6.0000000
25    -1.3333333
26    -4.3333333
27     1.3333333
28    -2.6666667
29    -2.0000000
30    -1.6666667
31     0.0000000
32     2.0000000
33    -1.0000000
34   -10.3333333
35    -2.0000000
36    -3.0000000
37     0.6666667
38    -3.3333333
39    -6.6666667
40    -4.3333333
41     6.6666667
42    -3.3333333
43     0.6666667
44     5.3333333
45     0.6666667
46     4.6666667
47    -5.6666667
48     5.3333333
49     4.3333333
50     6.3333333
51     2.0000000
52    11.0000000
53     3.3333333
54     1.3333333
55    -3.0000000
56    -5.6666667
57    -5.3333333
58    -0.3333333
59     5.0000000
60     3.0000000
61    -0.6666667
62    -3.3333333
63     0.6666667
64    -5.0000000
65     5.0000000
66     7.0000000
67    -2.0000000
68    -2.6666667
69     3.0000000
70     3.6666667
71    -5.3333333
72     0.3333333
73    -1.6666667
74     0.3333333
75     7.0000000
76    -0.6666667
77     2.0000000
78     0.3333333
79     1.6666667
80     1.6666667
81    -5.6666667
82     5.3333333
83    -0.3333333
84     2.6666667
85     1.6666667
86    -3.0000000
87    -4.0000000
88    -2.3333333
89     6.0000000
90    -3.3333333
91     4.0000000
92    -3.0000000
93    -1.3333333
94     6.3333333
95    -1.6666667
96     3.3333333
97     9.6666667
98     1.3333333
99    -5.6666667
100    3.3333333
101    0.0000000
102    7.3333333
103    3.0000000
104   -0.3333333
105   -4.3333333
106    1.6666667
107   -4.6666667
108    4.3333333
109    3.3333333
110    4.3333333
111    2.6666667
112   -2.0000000
113   -0.3333333
114    6.0000000
115   -5.6666667
116   -5.3333333
117   -6.0000000
118    3.6666667
119   -0.6666667
120    0.0000000
121    3.0000000
122    2.3333333
123   -3.6666667
124    0.6666667
125   -2.6666667
126    2.6666667
127    3.3333333
128    9.6666667
129   -0.6666667
130    7.3333333
131    5.3333333
132   -3.6666667
133   -0.3333333
134    4.0000000
135   -5.6666667
136   10.0000000
137   -8.3333333
138   -1.0000000
139   -2.0000000
140    1.3333333
141    6.3333333
142   -5.0000000
143    2.6666667
144   -4.6666667
145    2.6666667
146   -5.3333333
147    5.6666667
148    3.0000000
149   -0.3333333
150    8.0000000
151   -3.6666667
152   -7.0000000
153    1.0000000
154   -5.0000000
155  -10.6666667
156    5.3333333
157    7.6666667
158   -8.0000000
159    3.6666667
160   -0.3333333
161   -3.3333333
162   -0.3333333
163   -4.0000000
164   -4.6666667
165    1.6666667
166    2.6666667
167    0.6666667
168   -5.6666667
169    6.3333333
170   -5.6666667
171    1.6666667
172  -10.0000000
173    7.3333333
174   -3.3333333
175    4.3333333
176   -1.0000000
177    5.6666667
178   -7.0000000
179    8.6666667
180   -2.6666667
181    7.0000000
182   -7.3333333
183    5.3333333
184    1.6666667
185   -8.6666667
186    1.0000000
187    4.0000000
188    7.3333333
189    2.0000000
190    6.0000000
191    1.3333333
192    5.6666667
193   -3.3333333
194   -1.6666667
195   -6.0000000
196   -4.6666667
197    4.3333333
198   -5.0000000
199    3.0000000
200    3.3333333
201   -0.3333333
202    4.3333333
203   -3.0000000
204   -3.0000000
205   -4.6666667
206   -1.0000000
207    2.0000000
208   -1.6666667
209   -5.0000000
210   -0.3333333
211    1.6666667
212    1.6666667
213   -8.3333333
214   -1.3333333
215   -3.3333333
216   -2.3333333
217    3.0000000
218    4.0000000
219    0.3333333
220   -4.0000000
221   -0.6666667
222    7.6666667
223   -1.0000000
224   -5.6666667
225    6.0000000
226   -4.0000000
227   -1.0000000
228    2.3333333
229   -5.3333333
230    7.0000000
231   -0.3333333
232   -1.0000000
233    1.0000000
234   -6.6666667
235    2.6666667
236    1.0000000
237    0.0000000
238   -3.0000000
239   -7.0000000
240   -1.0000000
241    5.6666667
242   -1.6666667
243    9.3333333
244    1.3333333
245   -2.3333333
246    1.6666667
247   -5.0000000
248   -0.6666667
249   -3.0000000
250   12.3333333
251   -1.3333333
252    6.3333333
253    1.3333333
254    2.0000000
255    3.3333333
256    0.3333333
257    3.6666667
258   -6.0000000
259    1.3333333
260    7.6666667
261    6.6666667
262   -4.0000000
263    5.6666667
264   -4.0000000
265    4.3333333
266    4.3333333
267   -8.6666667
268   -5.3333333
269   -2.6666667
270   -3.6666667
271    8.6666667
272   -7.0000000
273   11.3333333
274    4.0000000
275   -3.0000000
276   -5.0000000
277   -7.6666667
278    3.0000000
279   -5.0000000
280    0.3333333
281   -5.3333333
282   -1.6666667
283    5.3333333
284    5.0000000
285   -7.3333333
286    5.3333333
287    3.6666667
288    0.3333333
289    5.3333333
290   -7.6666667
291    1.6666667
292   -1.3333333
293    9.3333333
294   -0.3333333
295   -2.0000000
296   -2.3333333
297    2.6666667
298    5.6666667
299   -6.0000000
300    0.6666667
301   -4.3333333
302   -3.3333333
303    5.3333333
304    0.0000000
305   -1.0000000
306    5.3333333
307    4.6666667
308    2.6666667
309    4.0000000
310    5.6666667
311   -0.6666667
312   -3.0000000
313    3.3333333
314    2.3333333
315   -6.6666667
316   -5.0000000
317    4.3333333
318    5.0000000
319   -1.6666667
320   -2.3333333
321   -1.0000000
322    5.3333333
323   -3.0000000
324   -6.3333333
325    1.6666667
326   -2.0000000
327    0.3333333
328    2.0000000
329   -5.6666667
330   -7.6666667
331    0.3333333
332    9.3333333
333   -4.0000000
334    7.6666667
335    8.0000000
336   -9.6666667
337    6.6666667
338    8.0000000
339    0.0000000
340   -7.0000000
341   -0.3333333
342   -1.6666667
343   -6.0000000
344    4.6666667
345    4.6666667
346   -8.6666667
347    8.0000000
348   -8.3333333
349   -3.6666667
350    0.3333333
351    1.0000000
352    0.3333333
353    0.0000000
354    3.3333333
355   -0.3333333
356   -4.6666667
357    6.3333333
358   -3.3333333
359   -5.6666667
360    3.0000000
361   -4.0000000
362    2.6666667
363   -8.3333333
364    8.0000000
365   -1.3333333
366    4.6666667
367    7.3333333
368   -1.3333333
369    4.3333333
370    0.6666667
371   -2.3333333
372    2.0000000
373    3.0000000
374    9.6666667
375   -6.3333333
376   -7.0000000
377   -4.0000000
378   -2.3333333
379    9.0000000
380   -1.0000000
381   -5.0000000
382   -9.3333333
383   -3.6666667
384   -2.3333333
385    0.0000000
386   -4.0000000
387   -8.3333333
388    1.6666667
389    6.0000000
390   -2.6666667
391    3.6666667
392    7.3333333
393   -2.0000000
394   -5.3333333
395    1.0000000
396    6.3333333
397    4.3333333
398   -2.6666667
399   -5.0000000
400    6.3333333
401    1.3333333
402   -4.0000000
403    7.0000000
404   -0.6666667
405    2.3333333
406    4.3333333
407    4.6666667
408    2.3333333
409    3.0000000
410   -5.0000000
411    3.3333333
412   -3.0000000
413    0.6666667
414    3.0000000
415    2.0000000
416    0.3333333
417   -5.0000000
418   -4.0000000
419    0.0000000
420    7.3333333
421   -0.3333333
422    0.0000000
423    4.0000000
424    0.0000000
425   -0.6666667
426  -10.0000000
427    0.0000000
428    7.6666667
429    8.3333333
430   -5.3333333
431   -7.3333333
432    3.0000000
433    6.6666667
434    0.0000000
435    0.3333333
436    9.3333333
437   -5.0000000
438   -7.6666667
439   -4.3333333
440   -4.6666667
441    1.3333333
442   -4.0000000
443    7.6666667
444    3.6666667
445    5.3333333
446    9.3333333
447    5.3333333
448   -2.3333333
449   -4.3333333
450   -1.3333333
451   -9.6666667
452    2.6666667
453   -7.6666667
454    5.0000000
455   -4.0000000
456   -6.0000000
457    3.0000000
458    2.3333333
459    1.6666667
460    7.3333333
461    2.6666667
462    5.6666667
463   -1.0000000
464    5.0000000
465    2.3333333
466    9.0000000
467   -0.6666667
468    0.3333333
469   -6.0000000
470    6.6666667
471    3.6666667
472    2.6666667
473   -8.3333333
474    0.3333333
475    4.3333333
476   -5.6666667
477   -8.6666667
478    2.0000000
479    3.0000000
480    0.3333333
481    3.6666667
482   -5.6666667
483   -3.3333333
484   -6.0000000
485    1.3333333
486   -2.3333333
487   -8.0000000
488   -3.0000000
489   -1.0000000
490   -1.3333333
491    1.6666667
492   -3.6666667
493  -10.0000000
494    1.0000000
495    1.3333333
496    7.3333333
497   -1.0000000
498   -6.0000000
499    2.6666667
500   -4.0000000
501    3.6666667
502   10.3333333
503   -1.3333333
504    3.3333333
505   -1.3333333
506    1.6666667
507    0.0000000
508    0.0000000
509   -6.3333333
510   -2.0000000
511  -11.0000000
512    2.0000000
513   -2.3333333
514    8.3333333
515    1.6666667
516    2.6666667
517   -1.3333333
518   -0.3333333
519   -5.3333333
520    0.0000000
521    2.0000000
522    6.6666667
523    3.3333333
524    1.6666667
525   -0.6666667
526   -1.0000000
527    6.3333333
528    2.0000000
529    4.0000000
530   -7.0000000
531    3.6666667
532   -7.0000000
533    3.3333333
534   -2.3333333
535   -0.3333333
536   -0.3333333
537    2.6666667
538    2.6666667
539   -9.6666667
540    0.3333333
541   -1.3333333
542   -4.3333333
543    1.0000000
544    1.6666667
545   -2.3333333
546    4.6666667
547   -6.3333333
548    2.0000000
549   -2.0000000
550   -2.0000000
551    1.6666667
552    3.0000000
553    4.0000000
554    1.6666667
555    0.3333333
556    2.3333333
557   -1.3333333
558   -5.3333333
559   -5.0000000
560    3.0000000
561    1.0000000
562    4.3333333
563   -2.0000000
564    0.3333333
565    0.3333333
566   -1.6666667
567   -1.6666667
568   -6.3333333
569   -8.0000000
570    3.3333333
571    5.0000000
572    2.0000000
573    0.3333333
574    3.6666667
575    4.6666667
576   -2.3333333
577    0.3333333
578   -4.6666667
579   -4.6666667
580    4.3333333
581    5.0000000
582    1.3333333
583    7.0000000
584   -3.0000000
585   -8.6666667
586   -1.3333333
587   -4.0000000
588    1.3333333
589    0.6666667
590   -4.6666667
591   -4.6666667
592   -0.3333333
593    2.6666667
594    4.6666667
595    1.0000000
596   -5.3333333
597   -6.6666667
598   -3.6666667
599    6.6666667
600   -3.0000000
601    4.3333333
602    3.0000000
603   -4.6666667
604    1.3333333
605    2.6666667
606    0.3333333
607   -8.0000000
608    3.0000000
609   -3.3333333
610    2.6666667
611   -5.0000000
612   -4.0000000
613   -2.6666667
614   -1.0000000
615    2.3333333
616    3.3333333
617   -4.0000000
618  -12.0000000
619   -4.3333333
620   -2.6666667
621    0.0000000
622   -1.0000000
623    1.6666667
624    3.0000000
625   -3.3333333
626    1.0000000
627    1.6666667
628    8.0000000
629    5.0000000
630    7.0000000
631    5.6666667
632    6.0000000
633   -9.6666667
634   -4.6666667
635    0.0000000
636   -1.3333333
637    1.6666667
638    1.6666667
639   -3.0000000
640    1.3333333
641   -2.0000000
642   -5.0000000
643   -1.3333333
644   -5.0000000
645    0.6666667
646    2.6666667
647   -1.0000000
648    2.0000000
649   -1.6666667
650   -5.3333333
651   -0.6666667
652    3.6666667
653    2.0000000
654    7.6666667
655   -3.0000000
656   -0.3333333
657    6.0000000
658   -3.3333333
659    0.6666667
660   -3.0000000
661    3.3333333
662   -0.6666667
663   -3.0000000
664    0.3333333
665    3.3333333
666   -0.3333333
667   -3.6666667
668    5.6666667
669   -2.0000000
670   -4.0000000
671   -6.6666667
672    4.3333333
673   -3.0000000
674   -1.3333333
675    0.3333333
676   -6.0000000
677    0.0000000
678    6.0000000
679   -2.6666667
680    1.0000000
681    2.6666667
682    3.0000000
683   -6.0000000
684    3.3333333
685    1.6666667
686   -2.3333333
687   -4.6666667
688    3.0000000
689    6.0000000
690   -1.0000000
691   -1.3333333
692   10.6666667
693    0.6666667
694    0.3333333
695    4.6666667
696   -5.0000000
697    0.0000000
698    3.3333333
699   -2.6666667
700    2.6666667
701   -4.3333333
702    4.6666667
703    4.3333333
704   -1.3333333
705    4.3333333
706    1.0000000
707   -0.3333333
708    0.0000000
709    6.0000000
710   -4.3333333
711    0.0000000
712    5.3333333
713   -0.3333333
714   -4.6666667
715   -1.6666667
716   -4.3333333
717   -2.3333333
718    2.0000000
719   -2.6666667
720  -11.6666667
721    3.0000000
722   -1.6666667
723   -1.6666667
724   -0.6666667
725    6.3333333
726   -5.3333333
727    4.6666667
728   -0.3333333
729    8.3333333
730    5.3333333
731   -1.6666667
732    3.3333333
733   -4.0000000
734   -5.0000000
735    5.3333333
736    5.0000000
737    3.0000000
738    2.3333333
739   -0.6666667
740    9.6666667
741    0.3333333
742   -3.6666667
743   -1.6666667
744   -3.6666667
745   -8.6666667
746    0.3333333
747    1.6666667
748   -0.6666667
749   -1.0000000
750   -7.0000000
751   -7.0000000
752   -1.3333333
753   -7.3333333
754    2.3333333
755    6.6666667
756   -2.3333333
757    0.6666667
758    1.6666667
759   -4.3333333
760   10.0000000
761   -5.3333333
762    2.6666667
763   -8.0000000
764    1.6666667
765    5.6666667
766   -0.6666667
767    8.3333333
768  -10.0000000
769    1.6666667
770    0.6666667
771    0.0000000
772   -2.0000000
773   -3.0000000
774    6.0000000
775   -2.3333333
776    3.6666667
777   -4.3333333
778    4.0000000
779   -3.0000000
780   -3.3333333
781   -2.0000000
782   -8.6666667
783    3.6666667
784    3.3333333
785   -3.0000000
786    5.3333333
787   -0.6666667
788    2.0000000
789    1.3333333
790    6.0000000
791    3.6666667
792   -2.6666667
793   -0.6666667
794   -2.6666667
795    1.6666667
796    4.6666667
797   -1.6666667
798   10.0000000
799   -1.3333333
800    4.3333333
801   -1.6666667
802    4.6666667
803    8.6666667
804   -7.6666667
805    6.3333333
806   -4.6666667
807    6.3333333
808    2.6666667
809    4.0000000
810   -1.6666667
811   -4.6666667
812    3.6666667
813    1.0000000
814    2.6666667
815    1.6666667
816   -1.0000000
817   -3.3333333
818    6.6666667
819    3.3333333
820    3.3333333
821   -3.6666667
822    1.0000000
823   -1.3333333
824    2.3333333
825    2.0000000
826    0.3333333
827   10.0000000
828    0.6666667
829    5.3333333
830    3.3333333
831   -1.3333333
832   -4.3333333
833   -4.3333333
834   -3.3333333
835    7.0000000
836    9.0000000
837    2.6666667
838   -0.3333333
839    6.0000000
840   -2.0000000
841   -1.0000000
842    1.0000000
843    3.6666667
844   -7.3333333
845   -2.3333333
846    1.0000000
847   -3.0000000
848   -3.3333333
849   -2.0000000
850    2.6666667
851   -5.0000000
852   -2.0000000
853    7.3333333
854    4.6666667
855   -3.0000000
856   -3.6666667
857    6.3333333
858    6.3333333
859    6.6666667
860   -1.6666667
861    6.3333333
862   -4.0000000
863    0.0000000
864    6.6666667
865    4.0000000
866    4.6666667
867    8.6666667
868   -1.0000000
869    2.6666667
870    8.0000000
871   -1.6666667
872   -4.3333333
873   -8.6666667
874   -6.0000000
875    6.3333333
876    1.6666667
877   -2.0000000
878    2.0000000
879    3.0000000
880   -8.0000000
881    6.3333333
882    4.0000000
883   -5.0000000
884   -3.0000000
885    4.0000000
886    7.0000000
887    1.3333333
888    2.6666667
889   -4.0000000
890   -0.3333333
891   -3.6666667
892   -0.3333333
893   -2.6666667
894   -3.3333333
895    3.0000000
896    7.0000000
897    7.6666667
898   -1.0000000
899    6.0000000
900    3.3333333
901   -6.0000000
902   -0.3333333
903    2.6666667
904   -0.6666667
905    0.6666667
906   -8.3333333
907    4.0000000
908    7.0000000
909   -4.0000000
910    0.0000000
911   -3.3333333
912   -4.3333333
913   -2.6666667
914   -3.3333333
915   -3.3333333
916    3.3333333
917    2.3333333
918   -1.0000000
919    1.6666667
920    5.0000000
921   -2.6666667
922   11.6666667
923   -2.6666667
924    3.0000000
925   -4.0000000
926    1.3333333
927   -3.0000000
928   -1.0000000
929   -1.3333333
930    1.6666667
931    1.6666667
932    5.3333333
933    3.3333333
934    4.3333333
935    8.6666667
936    9.0000000
937    4.3333333
938    8.6666667
939    1.0000000
940    2.6666667
941   -1.0000000
942    3.6666667
943    0.3333333
944    6.6666667
945   -6.3333333
946   -0.6666667
947   -3.0000000
948   -4.6666667
949    1.3333333
950    0.0000000
951    7.0000000
952   -5.6666667
953    8.3333333
954   -2.6666667
955    6.6666667
956   -8.3333333
957    1.3333333
958   -1.3333333
959   -3.6666667
960    3.6666667
961    8.3333333
962    3.6666667
963   -3.6666667
964    3.0000000
965    5.3333333
966    1.3333333
967   -5.3333333
968    9.3333333
969    2.3333333
970   -0.6666667
971    1.6666667
972  -11.0000000
973   -2.6666667
974   -3.6666667
975   -7.0000000
976   -6.0000000
977    6.6666667
978    0.6666667
979   -3.0000000
980    1.3333333
981    2.0000000
982   -3.6666667
983    8.0000000
984   -2.3333333
985   -4.6666667
986    3.0000000
987    6.6666667
988   -4.0000000
989    3.6666667
990    4.6666667
991    5.0000000
992    4.6666667
993    8.6666667
994    5.3333333
995   -1.6666667
996    6.0000000
997    1.3333333
998   -1.3333333
999   -3.3333333
1000  -0.3333333
1001  -4.0000000
1002  -2.6666667
1003   4.6666667
1004  -1.0000000
1005   3.0000000
1006  -4.0000000
1007  -8.3333333
1008   6.6666667
1009  -1.3333333
1010   6.3333333
1011   4.0000000
1012   5.0000000
1013   6.6666667
1014   5.3333333
1015   1.6666667
1016   0.0000000
1017   1.3333333
1018   2.0000000
1019   1.3333333
1020  -1.0000000
1021   5.3333333
1022  -0.3333333
1023   4.3333333
1024  -0.6666667
1025  -7.0000000
1026   0.3333333
1027  -5.3333333
1028  -2.6666667
1029  -4.0000000
1030  -5.0000000
1031   4.0000000
1032   4.6666667
1033   0.0000000
1034  -3.6666667
1035  -3.0000000
1036   5.3333333
1037  -2.0000000
1038   2.0000000
1039  -1.0000000
1040  -0.6666667
1041   1.6666667
1042  -2.0000000
1043  -2.6666667
1044  -3.0000000
1045  -1.0000000
1046   4.0000000
1047   0.3333333
1048   3.6666667
1049  -3.0000000
1050  -3.0000000
1051   1.0000000
1052  -1.0000000
1053   2.3333333
1054   5.6666667
1055   1.3333333
1056  -8.3333333
1057   0.3333333
1058   7.3333333
1059  -1.6666667
1060   0.6666667
1061  -6.3333333
1062  -4.3333333
1063  -2.3333333
1064   8.3333333
1065   5.0000000
1066  -5.6666667
1067  -2.6666667
1068   5.3333333
1069   0.6666667
1070   8.6666667
1071   6.6666667
1072   2.0000000
1073   9.0000000
1074   4.3333333
1075   4.3333333
1076  -1.0000000
1077   3.3333333
1078   0.6666667
1079  -7.0000000
1080   1.0000000
1081   6.0000000
1082  -4.3333333
1083   1.6666667
1084  -1.0000000
1085   0.6666667
1086   3.3333333
1087   7.6666667
1088   8.6666667
1089   1.0000000
1090   1.3333333
1091  -0.6666667
1092  -1.0000000
1093  -5.6666667
1094   5.3333333
1095  -3.0000000
1096   2.3333333
1097   1.3333333
1098  -3.0000000
1099  -0.6666667
1100  -6.0000000
1101   3.0000000
1102   4.3333333
1103  -0.3333333
1104  -1.6666667
1105  -5.0000000
1106  -2.0000000
1107   1.6666667
1108   4.6666667
1109   0.0000000
1110  -4.0000000
1111  -1.3333333
1112   1.6666667
1113   2.6666667
1114   2.3333333
1115   2.0000000
1116  -5.6666667
1117   8.0000000
1118   1.0000000
1119   0.6666667
1120  -3.0000000
1121  -7.0000000
1122  -3.0000000
1123   3.3333333
1124   4.3333333
1125   4.6666667
1126  -0.6666667
1127  -7.3333333
1128   4.0000000
1129  -6.0000000
1130   0.3333333
1131  -3.0000000
1132  15.0000000
1133  -1.6666667
1134  -5.6666667
1135  -1.6666667
1136   0.6666667
1137  -2.3333333
1138  -4.6666667
1139  11.0000000
1140   0.0000000
1141   2.0000000
1142   6.3333333
1143  -3.0000000
1144  -4.3333333
1145  -5.3333333
1146   6.0000000
1147   5.3333333
1148  -4.0000000
1149   1.3333333
1150  -3.6666667
1151   4.0000000
1152  -2.3333333
1153  -1.0000000
1154   5.0000000
1155   5.6666667
1156  -0.3333333
1157  -8.3333333
1158  -1.3333333
1159   2.6666667
1160   2.3333333
1161  -6.6666667
1162  -3.3333333
1163  -4.3333333
1164   0.6666667
1165   4.0000000
1166   5.3333333
1167  -2.3333333
1168   8.3333333
1169   7.6666667
1170   0.0000000
1171  -4.0000000
1172   2.0000000
1173  -1.0000000
1174  -1.0000000
1175   8.3333333
1176   0.0000000
1177  -1.6666667
1178  -1.6666667
1179  -4.6666667
1180   3.3333333
1181   0.3333333
1182   4.0000000
1183  -7.0000000
1184  -5.0000000
1185   5.3333333
1186   5.0000000
1187   5.0000000
1188  -7.6666667
1189   0.3333333
1190  -2.3333333
1191   3.3333333
1192  -1.0000000
1193   0.0000000
1194   1.0000000
1195   6.6666667
1196  -3.6666667
1197   4.3333333
1198   4.6666667
1199   8.3333333
1200   3.3333333
1201  -1.6666667
1202   1.6666667
1203   0.6666667
1204   4.6666667
1205   1.0000000
1206  -5.3333333
1207   4.0000000
1208  -1.0000000
1209  -4.0000000
1210   6.3333333
1211  -6.6666667
1212  -5.0000000
1213   1.3333333
1214   3.0000000
1215   0.6666667
1216   7.3333333
1217  -3.0000000
1218   6.3333333
1219  -9.0000000
1220  -1.0000000
1221  -5.0000000
1222  -8.0000000
1223   6.6666667
1224   4.3333333
1225   7.3333333
1226   7.6666667
1227   4.6666667
1228  -3.0000000
1229  -0.3333333
1230  -0.6666667
1231 -10.0000000
1232  -2.0000000
1233   0.6666667
1234  -6.3333333
1235   6.0000000
1236  -3.3333333
1237  -3.0000000
1238   4.0000000
1239   2.6666667
1240  -2.0000000
1241   6.0000000
1242   1.6666667
1243  -2.3333333
1244   2.0000000
1245  -0.6666667
1246   7.3333333
1247  -2.6666667
1248  -0.6666667
1249   1.3333333
1250   3.3333333
1251   6.0000000
1252   2.6666667
1253   1.3333333
1254   6.6666667
1255  -8.6666667
1256  -3.3333333
1257  -4.0000000
1258  -2.6666667
1259  -3.0000000
1260   2.0000000
1261  -0.3333333
1262  -5.0000000
1263  -7.6666667
1264  -0.3333333
1265  -9.0000000
1266   1.3333333
1267  -2.6666667
1268   2.0000000
1269   5.3333333
1270   5.3333333
1271  -5.0000000
1272   4.0000000
1273   2.0000000
1274  -1.3333333
1275  -5.3333333
1276  -0.6666667
1277   6.3333333
1278  -0.6666667
1279  -4.3333333
1280   3.6666667
1281   0.0000000
1282   0.3333333
1283  -2.3333333
1284   4.3333333
1285  -9.0000000
1286   5.6666667
1287   2.3333333
1288  -0.3333333
1289   4.3333333
1290  -1.6666667
1291   4.0000000
1292  -2.6666667
1293  -3.0000000
1294  -3.0000000
1295   3.0000000
1296  -4.0000000
1297   0.6666667
1298   4.6666667
1299   4.6666667
1300   9.3333333
1301  -6.6666667
1302   4.3333333
1303  -6.0000000
1304  -0.6666667
1305  -0.3333333
1306   3.0000000
1307  -2.6666667
1308   5.3333333
1309  -0.3333333
1310  -9.3333333
1311  -2.0000000
1312   3.6666667
1313   2.0000000
1314  -1.0000000
1315  -0.6666667
1316  -6.3333333
1317   0.0000000
1318  -6.3333333
1319  -8.6666667
1320   5.0000000
1321  -7.3333333
1322   6.3333333
1323  -5.3333333
1324   3.3333333
1325  -3.0000000
1326   0.0000000
1327   4.0000000
1328  -4.6666667
1329 -10.0000000
1330   7.3333333
1331   4.0000000
1332   1.6666667
1333   0.6666667
1334   2.3333333
1335   3.3333333
1336  -5.3333333
1337   0.0000000
1338  -5.3333333
1339   5.0000000
1340   1.0000000
1341  -4.0000000
1342   7.3333333
1343   2.6666667
1344  -3.0000000
1345  -4.0000000
1346  -9.3333333
1347  -1.6666667
1348  -3.0000000
1349   2.6666667
1350  -0.6666667
1351   5.6666667
1352   8.0000000
1353   4.3333333
1354   1.0000000
1355  -0.3333333
1356  -5.3333333
1357  -3.3333333
1358   1.0000000
1359   0.3333333
1360   1.3333333
1361  -9.3333333
1362   6.0000000
1363 -10.6666667
1364  -5.0000000
1365   2.6666667
1366   5.3333333
1367   1.6666667
1368   1.3333333
1369  -5.3333333
1370   5.0000000
1371  -6.3333333
1372   7.3333333
1373  -5.3333333
1374   5.6666667
1375   8.6666667
1376   3.6666667
1377   3.3333333
1378   6.3333333
1379  -0.6666667
1380   1.3333333
1381   5.0000000
1382   0.6666667
1383   0.0000000
1384  -1.0000000
1385   0.3333333
1386  -3.3333333
1387  -5.0000000
1388  -2.6666667
1389   5.0000000
1390  -4.0000000
1391   8.0000000
1392  -4.0000000
1393  -1.6666667
1394   0.3333333
1395   5.3333333
1396 -10.3333333
1397  -4.6666667
1398   2.6666667
1399   1.3333333
1400   2.3333333
1401  -7.6666667
1402  -5.0000000
1403   4.3333333
1404  -4.3333333
1405   0.6666667
1406   2.6666667
1407   1.0000000
1408  -4.6666667
1409 -11.3333333
1410  -0.3333333
1411   2.6666667
1412   0.0000000
1413  -4.3333333
1414   7.6666667
1415   6.3333333
1416   6.3333333
1417   8.0000000
1418  -4.6666667
1419  -3.3333333
1420  -1.6666667
1421   0.6666667
1422   4.0000000
1423   2.6666667
1424   1.6666667
1425   6.6666667
1426   8.6666667
1427  -6.0000000
1428  -9.3333333
1429  -9.3333333
1430  -1.0000000
1431   0.6666667
1432  -6.6666667
1433   0.3333333
1434 -10.6666667
1435  -4.0000000
1436  -2.0000000
1437  -9.6666667
1438  -4.0000000
1439   6.6666667
1440 -10.0000000
1441  -4.6666667
1442   2.6666667
1443   0.6666667
1444  -1.0000000
1445  -3.6666667
1446   5.3333333
1447   4.0000000
1448   4.0000000
1449  -1.0000000
1450  -3.3333333
1451  -1.3333333
1452  -0.3333333
1453   0.3333333
1454  -1.0000000
1455   1.3333333
1456  -9.6666667
1457  -0.6666667
1458  -5.3333333
1459   1.6666667
1460   5.3333333
1461   3.0000000
1462   3.3333333
1463  -1.6666667
1464  -8.3333333
1465  -4.3333333
1466   5.6666667
1467   2.3333333
1468   4.3333333
1469   2.6666667
1470   2.3333333
1471  -0.6666667
1472  -3.6666667
1473   1.6666667
1474   0.3333333
1475 -11.6666667
1476   2.6666667
1477   7.6666667
1478  -2.0000000
1479   9.3333333
1480   2.3333333
1481  -7.3333333
1482  -3.0000000
1483  -4.0000000
1484   3.6666667
1485   2.0000000
1486   0.6666667
1487   5.6666667
1488   2.6666667
1489   2.6666667
1490   0.3333333
1491   8.3333333
1492   6.6666667
1493  -9.0000000
1494  -3.0000000
1495   0.3333333
1496  -4.0000000
1497  -4.6666667
1498   3.3333333
1499   4.6666667
1500   4.3333333
1501   2.6666667
1502   0.3333333
1503  -3.0000000
1504  -2.3333333
1505   2.6666667
1506  -4.3333333
1507  -2.3333333
1508  -1.6666667
1509  -3.0000000
1510  -3.0000000
1511   1.6666667
1512   8.0000000
1513  -4.3333333
1514   4.0000000
1515  -2.3333333
1516   6.3333333
1517  -3.6666667
1518  -4.6666667
1519  -1.0000000
1520  -2.6666667
1521  -0.6666667
1522   0.6666667
1523   4.0000000
1524  -0.6666667
1525  -3.6666667
1526   5.6666667
1527   0.0000000
1528  -3.0000000
1529   5.0000000
1530   2.6666667
1531   7.3333333
1532  -1.0000000
1533  -1.6666667
1534   0.0000000
1535   2.3333333
1536   4.6666667
1537   1.6666667
1538   8.6666667
1539  -2.6666667
1540   2.6666667
1541  -2.6666667
1542  -4.6666667
1543  -1.6666667
1544   0.0000000
1545  -3.6666667
1546   3.6666667
1547   5.0000000
1548   2.3333333
1549   8.0000000
1550  -6.0000000
1551   1.0000000
1552  -3.0000000
1553   1.0000000
1554  -6.3333333
1555   1.6666667
1556   4.6666667
1557   6.0000000
1558  -0.3333333
1559  -5.6666667
1560   2.0000000
1561   0.6666667
1562  -4.3333333
1563   0.0000000
1564   4.0000000
1565  -8.3333333
1566  -0.3333333
1567   4.6666667
1568   0.0000000
1569   6.0000000
1570  -0.3333333
1571  -2.3333333
1572  -2.3333333
1573  -4.3333333
1574  -5.6666667
1575   4.3333333
1576  -5.6666667
1577  -4.3333333
1578   8.0000000
1579  -2.0000000
1580  -8.0000000
1581   5.6666667
1582   2.3333333
1583  -3.3333333
1584  -0.3333333
1585   3.0000000
1586   9.6666667
1587  -5.6666667
1588  -5.0000000
1589   1.3333333
1590  -0.6666667
1591   8.6666667
1592   3.6666667
1593   1.0000000
1594   7.3333333
1595  -1.0000000
1596   0.6666667
1597   2.3333333
1598   0.6666667
1599  -0.6666667
1600  -5.6666667
1601  -0.6666667
1602  -3.6666667
1603   2.3333333
1604   0.6666667
1605   5.3333333
1606   0.0000000
1607  -0.6666667
1608  -2.3333333
1609   3.3333333
1610   2.3333333
1611   4.0000000
1612   6.0000000
1613  -0.3333333
1614  -6.3333333
1615   8.3333333
1616  -5.0000000
1617  -5.3333333
1618  -1.0000000
1619   1.3333333
1620   1.3333333
1621   3.6666667
1622  -8.0000000
1623   1.3333333
1624  -3.0000000
1625  -1.0000000
1626  -0.3333333
1627   0.0000000
1628  -4.0000000
1629  -3.6666667
1630   6.0000000
1631   9.3333333
1632   2.0000000
1633   8.0000000
1634  10.0000000
1635  -7.0000000
1636  -0.3333333
1637   0.0000000
1638   7.3333333
1639   1.3333333
1640   1.6666667
1641   7.6666667
1642  -5.6666667
1643  -0.6666667
1644   6.6666667
1645  -1.0000000
1646  -7.0000000
1647   4.0000000
1648  -4.3333333
1649  -5.3333333
1650  -0.6666667
1651   9.0000000
1652   7.3333333
1653  -4.3333333
1654   1.0000000
1655   5.3333333
1656  -7.3333333
1657  -3.3333333
1658   2.6666667
1659   9.3333333
1660   5.6666667
1661   2.6666667
1662  -0.6666667
1663   6.6666667
1664  -3.3333333
1665   3.3333333
1666  -2.6666667
1667   5.0000000
1668   2.6666667
1669  -8.6666667
1670   1.3333333
1671  -5.6666667
1672   7.6666667
1673   0.6666667
1674  -4.0000000
1675   0.0000000
1676  -2.6666667
1677   2.3333333
1678  -1.6666667
1679   0.0000000
1680  -0.3333333
1681   3.6666667
1682   2.0000000
1683  -7.6666667
1684  -2.0000000
1685   2.6666667
1686  -5.6666667
1687  -1.0000000
1688   1.6666667
1689   3.3333333
1690   1.6666667
1691   7.3333333
1692  -1.3333333
1693   7.6666667
1694   2.0000000
1695   0.0000000
1696   1.0000000
1697   2.0000000
1698   3.3333333
1699  10.0000000
1700   7.6666667
1701   8.0000000
1702  -6.0000000
1703  -2.3333333
1704   7.0000000
1705   1.0000000
1706  -2.6666667
1707  -1.0000000
1708   3.3333333
1709   4.3333333
1710   8.6666667
1711  -3.0000000
1712   0.3333333
1713  -0.3333333
1714  -8.3333333
1715   1.3333333
1716 -11.6666667
1717  -3.0000000
1718   7.0000000
1719   4.3333333
1720  -5.0000000
1721   5.3333333
1722  -7.6666667
1723   2.0000000
1724  -6.0000000
1725   2.0000000
1726  -4.0000000
1727  -5.0000000
1728   2.6666667
1729  -2.3333333
1730   2.0000000
1731  -4.0000000
1732  -1.6666667
1733  -3.0000000
1734  -1.6666667
1735   0.3333333
1736   3.0000000
1737  -7.6666667
1738  -6.6666667
1739  -1.6666667
1740  -3.0000000
1741   1.0000000
1742 -11.0000000
1743  -0.6666667
1744   5.6666667
1745  -2.3333333
1746   5.6666667
1747   3.0000000
1748  -5.6666667
1749   3.6666667
1750   1.0000000
1751  -1.6666667
1752   6.6666667
1753  -5.6666667
1754  -2.3333333
1755   0.3333333
1756   1.6666667
1757  -7.0000000
1758  -1.0000000
1759   1.6666667
1760   2.0000000
1761   3.0000000
1762  -0.6666667
1763   7.3333333
1764  -8.0000000
1765   4.0000000
1766  -2.3333333
1767  -4.3333333
1768  -2.0000000
1769  -2.6666667
1770  11.6666667
1771  -2.3333333
1772  -8.0000000
1773   5.3333333
1774  -3.6666667
1775   6.3333333
1776   3.3333333
1777  -2.0000000
1778   3.0000000
1779   5.6666667
1780  -2.0000000
1781  -6.0000000
1782  -1.3333333
1783   7.3333333
1784   3.3333333
1785  -1.0000000
1786  -8.0000000
1787  -2.3333333
1788  -5.3333333
1789   2.6666667
1790   0.0000000
1791   0.3333333
1792  -1.6666667
1793  -5.3333333
1794  -0.6666667
1795   0.3333333
1796   6.0000000
1797   1.6666667
1798   2.6666667
1799   1.3333333
1800   2.6666667
1801   1.0000000
1802   2.6666667
1803   2.3333333
1804  -1.6666667
1805 -11.6666667
1806   5.0000000
1807  -2.0000000
1808   6.6666667
1809  -2.3333333
1810  -2.0000000
1811   1.3333333
1812  -2.0000000
1813   9.0000000
1814   0.3333333
1815   0.0000000
1816  -3.0000000
1817  -2.6666667
1818  -4.6666667
1819  -4.3333333
1820  -5.0000000
1821  -6.0000000
1822   0.3333333
1823  -2.6666667
1824   0.3333333
1825  -4.3333333
1826  -1.0000000
1827 -10.6666667
1828  -7.3333333
1829   5.0000000
1830 -12.0000000
1831   4.0000000
1832  -8.3333333
1833  -6.6666667
1834   1.0000000
1835  -6.0000000
1836  -7.6666667
1837  -5.3333333
1838  -1.0000000
1839  -0.6666667
1840   1.3333333
1841   1.6666667
1842  -7.0000000
1843   2.6666667
1844  -3.3333333
1845  -1.3333333
1846  -3.6666667
1847   1.3333333
1848   4.0000000
1849   2.6666667
1850   0.6666667
1851   4.3333333
1852  -0.6666667
1853  -1.6666667
1854   6.6666667
1855  -1.0000000
1856   3.3333333
1857   2.6666667
1858   5.0000000
1859   6.6666667
1860  -0.3333333
1861   1.3333333
1862   5.0000000
1863  -4.0000000
1864  -0.3333333
1865   7.6666667
1866  -6.0000000
1867   1.6666667
1868  -8.0000000
1869   1.6666667
1870  -0.3333333
1871   4.6666667
1872   2.3333333
1873   2.0000000
1874   3.6666667
1875  -4.3333333
1876  -6.6666667
1877  -2.0000000
1878  -4.3333333
1879   7.3333333
1880  -4.6666667
1881  -1.0000000
1882   5.6666667
1883   7.0000000
1884   5.3333333
1885   1.3333333
1886  -2.3333333
1887   1.0000000
1888  -3.6666667
1889   8.0000000
1890   7.0000000
1891   4.6666667
1892   7.6666667
1893  -4.0000000
1894   2.6666667
1895  -4.6666667
1896  -7.3333333
1897  -3.6666667
1898   5.0000000
1899  -3.0000000
1900  -1.3333333
1901   5.0000000
1902   6.6666667
1903  -2.0000000
1904   1.6666667
1905   2.3333333
1906   5.0000000
1907   0.3333333
1908   9.3333333
1909  -0.6666667
1910   5.3333333
1911   1.6666667
1912   5.0000000
1913   3.0000000
1914   7.3333333
1915  -2.3333333
1916  -2.6666667
1917  -3.3333333
1918   1.3333333
1919   4.6666667
1920   5.6666667
1921   1.0000000
1922   1.0000000
1923   2.0000000
1924  -2.0000000
1925  -1.0000000
1926   1.0000000
1927  -4.6666667
1928  -4.3333333
1929   2.0000000
1930 -10.0000000
1931  -5.3333333
1932  -3.0000000
1933  -1.0000000
1934   2.3333333
1935   3.6666667
1936  -0.6666667
1937  -6.3333333
1938   1.6666667
1939  -5.3333333
1940  -8.6666667
1941   3.3333333
1942   7.0000000
1943  -2.3333333
1944   0.3333333
1945   6.0000000
1946   1.6666667
1947  11.3333333
1948   0.0000000
1949   3.3333333
1950  -5.0000000
1951   6.6666667
1952  -6.6666667
1953   7.0000000
1954  -1.6666667
1955   0.0000000
1956 -10.0000000
1957  -0.3333333
1958   2.0000000
1959   2.0000000
1960  -5.6666667
1961  -2.3333333
1962   3.6666667
1963   2.0000000
1964   4.3333333
1965  -4.6666667
1966  -6.0000000
1967  10.0000000
1968   3.0000000
1969   8.6666667
1970   6.3333333
1971   6.3333333
1972  -0.6666667
1973   6.3333333
1974  -5.6666667
1975  -6.3333333
1976  -1.3333333
1977  -5.0000000
1978  -2.6666667
1979  -0.6666667
1980   4.3333333
1981   0.3333333
1982  -7.3333333
1983   2.3333333
1984  -4.0000000
1985  -0.3333333
1986  -6.3333333
1987   7.6666667
1988   7.0000000
1989  -7.3333333
1990 -15.6666667
1991  13.3333333
1992   0.3333333
1993   5.6666667
1994  -0.6666667
1995  -1.6666667
1996 -11.6666667
1997   0.3333333
1998  -1.0000000
1999   2.6666667
2000  -4.6666667
2001  -2.6666667
2002  -5.6666667
2003   7.0000000
2004  -0.6666667
2005   3.6666667
2006   0.3333333
2007   4.6666667
2008   1.6666667
2009  -2.6666667
2010   2.0000000
2011   0.6666667
2012   2.6666667
2013   1.0000000
2014  -0.6666667
2015   2.6666667
2016   2.3333333
2017  -5.3333333
2018  -0.3333333
2019  -0.3333333
2020   0.3333333
2021   6.6666667
2022   6.6666667
2023  -6.3333333
2024   5.3333333
2025  -1.6666667
2026  -5.0000000
2027  -8.3333333
2028  -6.0000000
2029   1.6666667
2030  -3.6666667
2031  -4.0000000
2032  -4.3333333
2033  -2.3333333
2034   1.0000000
2035   0.6666667
2036   4.3333333
2037   1.3333333
2038  -5.3333333
2039   3.6666667
2040  -6.3333333
2041   0.6666667
2042   4.3333333
2043  -4.3333333
2044  -4.0000000
2045  -3.6666667
2046   1.3333333
2047  -3.6666667
2048   4.0000000
2049   3.0000000
2050  -2.6666667
2051   3.6666667
2052  -3.6666667
2053 -10.3333333
2054   4.0000000
2055  -4.3333333
2056   4.6666667
2057  -1.3333333
2058   3.3333333
2059   0.6666667
2060  -7.6666667
2061   2.0000000
2062   3.6666667
2063   9.6666667
2064  -7.3333333
2065   1.0000000
2066   0.6666667
2067  -1.6666667
2068  -3.0000000
2069   3.3333333
2070  -6.6666667
2071   3.0000000
2072  -3.3333333
2073   6.0000000
2074  -5.3333333
2075  -0.6666667
2076   5.6666667
2077   0.6666667
2078   3.6666667
2079  -5.0000000
2080  -4.6666667
2081  -6.6666667
2082  -4.6666667
2083   1.6666667
2084  -4.6666667
2085  -1.3333333
2086  -5.0000000
2087  -2.3333333
2088  -8.6666667
2089  -6.3333333
2090   4.3333333
2091   9.0000000
2092   3.6666667
2093   1.0000000
2094  -2.6666667
2095 -10.6666667
2096   7.3333333
2097   5.0000000
2098   8.0000000
2099  -4.3333333
2100   3.0000000
2101   6.0000000
2102   3.3333333
2103   0.0000000
2104   3.0000000
2105  -1.0000000
2106   1.6666667
2107  -7.0000000
2108   6.6666667
2109  -3.3333333
2110   7.6666667
2111  -2.0000000
2112  -6.3333333
2113   4.6666667
2114   2.3333333
2115   5.3333333
2116  -3.0000000
2117  -4.6666667
2118   0.3333333
2119   3.6666667
2120  -8.0000000
2121   8.3333333
2122   1.3333333
2123   5.6666667
2124   5.3333333
2125  -2.0000000
2126  -1.6666667
2127   5.0000000
2128  -2.0000000
2129  -4.6666667
2130   1.0000000
2131   7.0000000
2132  -7.0000000
2133  -3.6666667
2134   7.6666667
2135   4.3333333
2136   2.0000000
2137   3.3333333
2138   5.6666667
2139   0.0000000
2140 -10.6666667
2141   2.3333333
2142  -1.6666667
2143   0.3333333
2144   0.0000000
2145   1.3333333
2146  -1.6666667
2147  -4.0000000
2148   3.3333333
2149  -1.3333333
2150  -3.3333333
2151   5.3333333
2152  -4.3333333
2153  -2.0000000
2154   3.3333333
2155  -0.6666667
2156   1.6666667
2157  -2.3333333
2158   4.3333333
2159  -0.3333333
2160  -1.6666667
2161  -0.3333333
2162   3.0000000
2163   2.0000000
2164  -7.0000000
2165  -2.3333333
2166   5.0000000
2167  -6.6666667
2168  -3.3333333
2169  -5.3333333
2170   3.0000000
2171  -5.3333333
2172  -0.6666667
2173   0.3333333
2174   3.3333333
2175   1.3333333
2176  -1.0000000
2177  -1.3333333
2178   4.6666667
2179   2.3333333
2180   1.6666667
2181  -4.3333333
2182  -1.0000000
2183   8.3333333
2184  -9.6666667
2185   0.0000000
2186   6.3333333
2187  -1.3333333
2188   6.6666667
2189   2.0000000
2190  -0.6666667
2191   3.3333333
2192  -2.6666667
2193   6.0000000
2194  -6.3333333
2195   7.0000000
2196  -7.6666667
2197  -0.3333333
2198   5.6666667
2199  -7.0000000
2200  -5.3333333
2201  -2.0000000
2202   8.0000000
2203  -3.6666667
2204   0.0000000
2205   5.3333333
2206   2.3333333
2207  -7.3333333
2208  -8.6666667
2209  -3.3333333
2210  -3.3333333
2211  -0.6666667
2212   2.3333333
2213  -1.6666667
2214   7.0000000
2215   1.0000000
2216   2.0000000
2217  -4.0000000
2218  -0.3333333
2219   0.3333333
2220  -7.3333333
2221  -1.0000000
2222  -3.3333333
2223   6.0000000
2224   0.0000000
2225   6.6666667
2226   1.0000000
2227   2.0000000
2228  -5.0000000
2229  -6.0000000
2230   0.3333333
2231  -5.0000000
2232   0.3333333
2233  -7.0000000
2234  -0.3333333
2235   5.6666667
2236  -0.6666667
2237  -5.0000000
2238   0.6666667
2239   0.0000000
2240   3.6666667
2241   1.3333333
2242   3.0000000
2243  -1.3333333
2244   2.6666667
2245  -6.6666667
2246   7.6666667
2247   1.0000000
2248  -5.3333333
2249   0.6666667
2250  -0.6666667
2251   4.3333333
2252   0.0000000
2253  -4.0000000
2254   1.6666667
2255  -2.3333333
2256  -8.0000000
2257   2.0000000
2258  -1.6666667
2259   0.6666667
2260  -3.6666667
2261  -3.6666667
2262  -8.0000000
2263   2.3333333
2264   2.3333333
2265  -1.3333333
2266  -1.6666667
2267   0.3333333
2268   9.0000000
2269   1.6666667
2270   0.6666667
2271   2.0000000
2272   4.3333333
2273   7.0000000
2274  -4.0000000
2275   3.3333333
2276  -6.6666667
2277  -4.0000000
2278  -5.3333333
2279   1.0000000
2280  -5.0000000
2281   4.3333333
2282  -6.0000000
2283  -0.6666667
2284  -0.3333333
2285  -6.0000000
2286   3.3333333
2287  -2.6666667
2288  -3.3333333
2289   5.0000000
2290  -4.0000000
2291   9.6666667
2292   1.3333333
2293   4.0000000
2294  -1.0000000
2295   5.3333333
2296   2.6666667
2297  -5.6666667
2298  -1.6666667
2299   7.3333333
2300   5.6666667
2301   0.6666667
2302   1.6666667
2303   5.6666667
2304  -0.6666667
2305   2.6666667
2306   3.6666667
2307   0.6666667
2308  -3.0000000
2309  -6.6666667
2310   6.0000000
2311   0.3333333
2312   5.3333333
2313  -3.6666667
2314   0.3333333
2315   6.0000000
2316  -1.6666667
2317   3.6666667
2318   5.0000000
2319  -4.0000000
2320   0.6666667
2321  -5.6666667
2322   4.6666667
2323   2.6666667
2324   1.6666667
2325  -8.6666667
2326   3.0000000
2327   8.6666667
2328   5.0000000
2329  -0.6666667
2330   6.6666667
2331  -2.6666667
2332  -2.3333333
2333   5.6666667
2334   4.0000000
2335  -6.6666667
2336  -2.0000000
2337   4.3333333
2338  -3.3333333
2339  -2.3333333
2340  -7.3333333
2341   0.6666667
2342  -3.0000000
2343   4.6666667
2344  -6.0000000
2345  -0.3333333
2346  -0.6666667
2347   4.6666667
2348  10.3333333
2349   6.0000000
2350   2.0000000
2351  -6.6666667
2352  -3.3333333
2353  -1.0000000
2354  -3.6666667
2355  11.6666667
2356   3.3333333
2357  -1.3333333
2358  -2.0000000
2359   2.6666667
2360  -3.0000000
2361   4.6666667
2362   2.0000000
2363   0.0000000
2364   3.0000000
2365  -1.0000000
2366  -4.0000000
2367   1.6666667
2368   2.3333333
2369   3.0000000
2370  13.6666667
2371  -4.0000000
2372   1.3333333
2373   0.6666667
2374   5.6666667
2375  -5.3333333
2376   7.6666667
2377  -2.6666667
2378   6.6666667
2379  -3.6666667
2380   4.0000000
2381  -9.6666667
2382  -7.0000000
2383   8.3333333
2384   3.0000000
2385  -1.0000000
2386  -8.3333333
2387   5.3333333
2388   5.0000000
2389  -3.3333333
2390   0.3333333
2391  -1.0000000
2392  -3.3333333
2393   6.6666667
2394   1.0000000
2395   7.0000000
2396  -0.3333333
2397  -5.3333333
2398  -3.3333333
2399  -3.3333333
2400  -6.0000000
2401   3.6666667
2402   6.3333333
2403   4.0000000
2404  -2.3333333
2405  -6.3333333
2406  -0.3333333
2407   2.6666667
2408   2.6666667
2409  -2.6666667
2410   5.3333333
2411  -2.0000000
2412   6.3333333
2413   3.6666667
2414   4.0000000
2415   5.3333333
2416   3.0000000
2417  -3.6666667
2418   0.0000000
2419   2.3333333
2420   1.3333333
2421  -8.3333333
2422  -4.3333333
2423  -7.6666667
2424   7.0000000
2425   4.6666667
2426  -3.0000000
2427   6.6666667
2428  -2.6666667
2429  -7.3333333
2430  -3.0000000
2431  -0.6666667
2432  -0.6666667
2433  -3.0000000
2434   5.6666667
2435   4.6666667
2436  -1.6666667
2437  -1.0000000
2438  -5.6666667
2439  -7.0000000
2440   3.0000000
2441   5.0000000
2442   7.3333333
2443   6.3333333
2444   1.6666667
2445  -6.3333333
2446  -9.6666667
2447   5.3333333
2448  -0.6666667
2449   4.6666667
2450  -2.0000000
2451  -0.6666667
2452  -5.6666667
2453   6.0000000
2454  -1.0000000
2455   0.3333333
2456   7.3333333
2457  -0.6666667
2458  -3.3333333
2459   9.0000000
2460  -2.3333333
2461  -2.6666667
2462   1.3333333
2463   2.0000000
2464 -10.0000000
2465   4.3333333
2466  -4.3333333
2467   0.3333333
2468  -6.6666667
2469  -2.3333333
2470   2.6666667
2471   7.3333333
2472  -3.6666667
2473  -5.6666667
2474   3.3333333
2475  -2.3333333
2476  -5.0000000
2477   2.0000000
2478  -8.6666667
2479   2.3333333
2480   3.0000000
2481   1.6666667
2482  -1.6666667
2483   0.0000000
2484  -0.3333333
2485   2.6666667
2486   0.3333333
2487   9.3333333
2488  -1.6666667
2489  -2.6666667
2490 -11.0000000
2491  -5.3333333
2492   5.6666667
2493   5.0000000
2494   5.0000000
2495   1.0000000
2496  -5.6666667
2497   6.6666667
2498  -2.3333333
2499   5.3333333
2500   1.3333333
2501   3.0000000
2502   3.0000000
2503  -5.6666667
2504  -4.0000000
2505  -2.3333333
2506  -3.3333333
2507  -7.0000000
2508   3.3333333
2509  -4.0000000
2510  -1.0000000
2511   4.3333333
2512  -7.6666667
2513   4.0000000
2514   7.6666667
2515  -0.6666667
2516   3.6666667
2517   3.3333333
2518   4.3333333
2519   5.0000000
2520   4.3333333
2521  -1.6666667
2522   3.3333333
2523  -4.3333333
2524  -5.6666667
2525  -1.6666667
2526  -2.0000000
2527  11.6666667
2528   3.6666667
2529  -3.0000000
2530   6.3333333
2531  -4.6666667
2532  -0.6666667
2533  -1.6666667
2534  -3.0000000
2535  -4.3333333
2536  -4.3333333
2537  -4.0000000
2538  -3.6666667
2539   7.6666667
2540   8.3333333
2541   2.0000000
2542   7.0000000
2543   1.6666667
2544  -2.3333333
2545   0.3333333
2546   4.6666667
2547  -6.0000000
2548   0.6666667
2549  -3.0000000
2550  -0.3333333
2551   4.0000000
2552  -2.0000000
2553  -1.6666667
2554  -6.3333333
2555   5.6666667
2556   3.0000000
2557   6.0000000
2558   0.0000000
2559   0.6666667
2560  -7.0000000
2561  -5.0000000
2562   9.3333333
2563   0.0000000
2564   4.0000000
2565  -0.6666667
2566   1.6666667
2567   9.0000000
2568   1.3333333
2569  -1.0000000
2570  -4.3333333
2571   9.6666667
2572   9.6666667
2573  -5.3333333
2574   3.0000000
2575   4.3333333
2576   5.0000000
2577  -3.0000000
2578   5.0000000
2579   1.0000000
2580  -0.3333333
2581  -8.0000000
2582   4.6666667
2583  -1.3333333
2584  -0.3333333
2585   4.3333333
2586   0.0000000
2587   7.3333333
2588  -0.3333333
2589   1.6666667
2590  -2.0000000
2591   1.3333333
2592   5.6666667
2593   1.6666667
2594  -5.6666667
2595   8.6666667
2596   3.0000000
2597  -4.0000000
2598  -5.0000000
2599  -2.0000000
2600   3.6666667
2601  -9.3333333
2602   0.0000000
2603   7.0000000
2604   0.0000000
2605  -3.3333333
2606  -6.3333333
2607  -3.0000000
2608  -2.0000000
2609   4.0000000
2610   3.0000000
2611  -6.3333333
2612  -7.6666667
2613  -2.3333333
2614   1.3333333
2615   5.3333333
2616  -6.6666667
2617   3.3333333
2618  -0.3333333
2619   0.3333333
2620  -8.0000000
2621   4.3333333
2622  -0.3333333
2623   9.3333333
2624  -6.0000000
2625  10.6666667
2626  -1.0000000
2627  -4.3333333
2628   5.0000000
2629  -8.3333333
2630   3.6666667
2631   0.6666667
2632   4.3333333
2633   6.0000000
2634  -2.0000000
2635  -4.6666667
2636  -1.6666667
2637  -2.3333333
2638   1.0000000
2639  -6.3333333
2640  -2.3333333
2641   9.0000000
2642   4.3333333
2643  -4.6666667
2644   0.3333333
2645  -5.0000000
2646   0.3333333
2647  -6.0000000
2648  -3.3333333
2649  -1.0000000
2650   1.6666667
2651  11.3333333
2652   2.0000000
2653   5.3333333
2654  -5.6666667
2655  -9.0000000
2656   0.0000000
2657   2.6666667
2658  -1.0000000
2659   3.0000000
2660  -1.0000000
2661   7.6666667
2662   4.6666667
2663   1.0000000
2664  -4.3333333
2665   1.3333333
2666  -0.6666667
2667   1.6666667
2668  -8.6666667
2669   5.3333333
2670   1.3333333
2671   2.3333333
2672  -1.6666667
2673  10.6666667
2674  -3.6666667
2675   4.3333333
2676   1.3333333
2677   0.3333333
2678   3.6666667
2679   3.3333333
2680  -5.6666667
2681   3.0000000
2682   0.3333333
2683  -7.0000000
2684  -1.0000000
2685   1.3333333
2686  -2.3333333
2687   3.3333333
2688   0.0000000
2689   1.6666667
2690  -2.6666667
2691   1.3333333
2692  -0.3333333
2693   0.0000000
2694   2.0000000
2695   1.6666667
2696   0.6666667
2697  -9.0000000
2698   3.3333333
2699  -4.3333333
2700  -1.3333333
2701   4.0000000
2702   3.3333333
2703  -1.6666667
2704  -4.3333333
2705   9.6666667
2706   1.6666667
2707   2.3333333
2708   0.6666667
2709   1.3333333
2710  -1.0000000
2711   0.6666667
2712  -3.3333333
2713  -5.6666667
2714  -4.6666667
2715  -2.6666667
2716  -4.6666667
2717   2.6666667
2718   2.6666667
2719  -3.0000000
2720   0.6666667
2721   1.0000000
2722  -6.0000000
2723  -2.3333333
2724  -6.3333333
2725  -2.6666667
2726   0.6666667
2727  -8.6666667
2728  -0.6666667
2729  -5.3333333
2730   0.0000000
2731   3.0000000
2732  -9.0000000
2733   4.0000000
2734  -7.3333333
2735   0.3333333
2736  -2.0000000
2737  -0.3333333
2738  -8.3333333
2739   8.0000000
2740  -3.6666667
2741   7.0000000
2742   2.6666667
2743  -2.0000000
2744  -0.6666667
2745  -9.3333333
2746  -0.3333333
2747  -2.3333333
2748   0.0000000
2749   1.0000000
2750   2.0000000
2751   5.3333333
2752  -3.3333333
2753  -3.0000000
2754  -2.6666667
2755   1.6666667
2756   5.6666667
2757   1.0000000
2758   4.3333333
2759  -6.0000000
2760  -4.3333333
2761 -10.0000000
2762  -1.3333333
2763  -9.0000000
2764   8.6666667
2765  -1.3333333
2766  -5.3333333
2767  -0.3333333
2768   2.0000000
2769  -1.0000000
2770   0.3333333
2771   1.3333333
2772   6.6666667
2773  -8.0000000
2774  -3.0000000
2775   2.0000000
2776   3.6666667
2777  -2.3333333
2778  -6.6666667
2779  -2.6666667
2780   3.6666667
2781  -2.0000000
2782   5.3333333
2783   0.6666667
2784  -2.0000000
2785  -3.0000000
2786  -8.0000000
2787  -0.3333333
2788  -2.3333333
2789  -1.0000000
2790  -4.6666667
2791   1.3333333
2792   0.6666667
2793   3.6666667
2794  -3.6666667
2795  -9.6666667
2796   2.6666667
2797   1.6666667
2798   7.6666667
2799   5.3333333
2800   6.0000000
2801   2.3333333
2802  -1.3333333
2803   0.3333333
2804  -1.0000000
2805   8.0000000
2806  -5.0000000
2807  -3.3333333
2808  -8.3333333
2809  -7.0000000
2810   1.0000000
2811  -5.0000000
2812  -3.3333333
2813  -3.3333333
2814  -0.6666667
2815   6.0000000
2816  -1.6666667
2817   5.0000000
2818  -0.6666667
2819   0.6666667
2820   3.6666667
2821   2.0000000
2822   0.6666667
2823  -4.3333333
2824   0.6666667
2825  11.6666667
2826   1.0000000
2827   7.3333333
2828   8.0000000
2829  -4.0000000
2830  -3.0000000
2831  -0.6666667
2832  -3.6666667
2833  -5.0000000
2834  10.3333333
2835  -3.6666667
2836  -7.3333333
2837  -1.0000000
2838   5.3333333
2839  -8.6666667
2840   4.0000000
2841   2.6666667
2842  -7.3333333
2843   5.6666667
2844   8.0000000
2845  -6.0000000
2846   5.0000000
2847   7.6666667
2848  -4.0000000
2849   4.3333333
2850   2.3333333
2851  -6.3333333
2852   5.3333333
2853   3.0000000
2854  -9.3333333
2855  -6.6666667
2856   4.6666667
2857  10.6666667
2858   3.6666667
2859   0.0000000
2860   5.0000000
2861  -3.3333333
2862   1.3333333
2863  -6.3333333
2864   4.0000000
2865  -5.3333333
2866   1.0000000
2867   6.3333333
2868  -2.0000000
2869  -0.6666667
2870  -1.6666667
2871   7.0000000
2872  -4.6666667
2873  -5.3333333
2874  -3.0000000
2875   3.3333333
2876   9.3333333
2877  -0.6666667
2878   0.3333333
2879   6.6666667
2880  -2.0000000
2881  -1.6666667
2882  -2.6666667
2883  -0.3333333
2884  -2.6666667
2885  -6.3333333
2886  -0.6666667
2887  -3.3333333
2888   0.6666667
2889  -2.6666667
2890  -5.6666667
2891   0.3333333
2892   2.0000000
2893  -7.3333333
2894  -6.0000000
2895  -6.0000000
2896  -4.0000000
2897   6.6666667
2898  -8.0000000
2899   4.3333333
2900  -4.0000000
2901  -1.0000000
2902   3.6666667
2903  -6.6666667
2904   3.3333333
2905   1.3333333
2906  -2.3333333
2907  -5.6666667
2908  10.3333333
2909  -7.0000000
2910   1.6666667
2911   8.6666667
2912   0.6666667
2913 -10.0000000
2914   2.0000000
2915   5.6666667
2916   6.3333333
2917   3.6666667
2918  -2.0000000
2919   0.3333333
2920  -2.6666667
2921  -1.0000000
2922   1.0000000
2923   4.0000000
2924  -1.0000000
2925   6.6666667
2926  -3.0000000
2927  -4.6666667
2928   1.3333333
2929  -3.0000000
2930  -2.3333333
2931   6.6666667
2932   2.3333333
2933  -6.6666667
2934  -3.6666667
2935   3.3333333
2936  -6.6666667
2937   7.0000000
2938  -2.0000000
2939  -4.3333333
2940   4.6666667
2941  -1.3333333
2942  -9.3333333
2943  -6.3333333
2944   2.0000000
2945   1.6666667
2946  13.3333333
2947  -6.3333333
2948  -5.0000000
2949  -5.3333333
2950  -3.3333333
2951  -4.0000000
2952   0.3333333
2953   5.3333333
2954  -7.6666667
2955  -1.3333333
2956   7.6666667
2957  -1.0000000
2958  -6.6666667
2959  -3.0000000
2960   6.0000000
2961  -4.3333333
2962  -6.6666667
2963  -3.0000000
2964   0.0000000
2965   6.0000000
2966  -2.0000000
2967  -2.6666667
2968   3.3333333
2969  -1.3333333
2970  -6.3333333
2971  -2.0000000
2972  -3.3333333
2973  -0.6666667
2974   6.3333333
2975   6.3333333
2976   6.0000000
2977   0.0000000
2978  -1.3333333
2979   2.0000000
2980   8.0000000
2981  -2.3333333
2982   8.0000000
2983   2.3333333
2984  -7.3333333
2985  -2.0000000
2986   6.0000000
2987   2.3333333
2988   2.6666667
2989  -2.6666667
2990   2.6666667
2991   5.0000000
2992  -5.3333333
2993  -7.6666667
2994  -5.6666667
2995   5.3333333
2996  -7.3333333
2997  -2.6666667
2998   1.0000000
2999  -7.3333333
3000   3.3333333
3001   0.0000000
3002  -5.0000000
3003  -0.6666667
3004   7.3333333
3005   6.6666667
3006  -3.0000000
3007   5.6666667
3008   5.6666667
3009   3.3333333
3010   0.6666667
3011   1.3333333
3012  -5.6666667
3013   2.6666667
3014   8.6666667
3015  -4.0000000
3016   0.0000000
3017   2.6666667
3018  -3.6666667
3019  -5.0000000
3020  -2.3333333
3021   7.3333333
3022   6.0000000
3023  -1.0000000
3024  -8.0000000
3025   6.6666667
3026  -6.6666667
3027   8.6666667
3028  -7.6666667
3029   7.0000000
3030   2.3333333
3031  -0.3333333
3032  -3.0000000
3033  -3.3333333
3034   2.6666667
3035   2.3333333
3036  -2.6666667
3037  -6.0000000
3038  -0.6666667
3039   3.3333333
3040   3.0000000
3041  -5.6666667
3042   5.3333333
3043   4.0000000
3044   0.0000000
3045   0.3333333
3046   4.0000000
3047 -10.0000000
3048  -3.3333333
3049   0.0000000
3050   8.3333333
3051   1.3333333
3052   1.0000000
3053  -1.0000000
3054   7.6666667
3055  -1.3333333
3056   4.3333333
3057   5.0000000
3058   4.3333333
3059  -3.3333333
3060   3.0000000
3061   7.3333333
3062   7.3333333
3063  -3.6666667
3064  -4.0000000
3065  -3.0000000
3066  -1.0000000
3067  -7.0000000
3068   8.6666667
3069  -3.6666667
3070   3.0000000
3071  -5.0000000
3072  -1.3333333
3073   0.0000000
3074  -1.3333333
3075   3.0000000
3076   6.6666667
3077  -1.3333333
3078  -6.0000000
3079  -9.6666667
3080   3.6666667
3081  -5.0000000
3082  -3.0000000
3083  -2.3333333
3084   2.3333333
3085  -0.6666667
3086   1.3333333
3087  -3.6666667
3088  -4.6666667
3089  -2.6666667
3090   0.6666667
3091   3.3333333
3092   2.0000000
3093  -4.3333333
3094  -0.6666667
3095   8.3333333
3096  -1.3333333
3097  -3.3333333
3098  -1.6666667
3099  -6.3333333
3100   4.0000000
3101  -3.6666667
3102   9.6666667
3103  -2.6666667
3104  -0.6666667
3105   6.3333333
3106   3.6666667
3107   5.0000000
3108  -3.3333333
3109  -2.0000000
3110  -3.0000000
3111   4.3333333
3112   8.3333333
3113  -5.3333333
3114  -2.0000000
3115  -3.3333333
3116   2.3333333
3117   2.0000000
3118   1.3333333
3119  -7.0000000
3120   9.3333333
3121  -3.3333333
3122  -1.3333333
3123  -0.3333333
3124  -7.0000000
3125   2.6666667
3126   1.6666667
3127  -2.3333333
3128   1.6666667
3129   5.0000000
3130  -4.3333333
3131  -5.3333333
3132   5.3333333
3133   0.0000000
3134   1.6666667
3135   6.0000000
3136  -0.6666667
3137   0.3333333
3138   6.0000000
3139   0.3333333
3140  -4.0000000
3141  -3.0000000
3142   5.0000000
3143   3.0000000
3144 -11.0000000
3145  -0.3333333
3146  -3.6666667
3147  -5.6666667
3148  -5.0000000
3149  -7.6666667
3150   3.3333333
3151 -11.0000000
3152   6.6666667
3153  -4.0000000
3154  -0.3333333
3155  -8.6666667
3156  -5.3333333
3157  -3.6666667
3158  -5.0000000
3159  -8.0000000
3160  -0.6666667
3161  -7.3333333
3162   5.6666667
3163   5.3333333
3164  -5.3333333
3165   0.3333333
3166  -7.0000000
3167   3.3333333
3168  -4.6666667
3169   0.0000000
3170  -3.3333333
3171   0.6666667
3172  10.6666667
3173   2.0000000
3174  -3.3333333
3175   8.6666667
3176   4.3333333
3177   6.3333333
3178   3.6666667
3179   2.0000000
3180   3.6666667
3181   1.6666667
3182  -4.0000000
3183  -4.3333333
3184  -8.3333333
3185  -5.6666667
3186  -2.6666667
3187   3.0000000
3188   0.6666667
3189   8.0000000
3190  -4.0000000
3191  -5.6666667
3192   5.0000000
3193  -4.6666667
3194  -1.6666667
3195  10.3333333
3196   1.0000000
3197  -3.3333333
3198   0.6666667
3199   4.0000000
3200   4.6666667
3201  -1.0000000
3202   3.3333333
3203   0.6666667
3204   5.0000000
3205   3.6666667
3206  -2.3333333
3207   6.0000000
3208   2.0000000
3209  -2.3333333
3210  -6.6666667
3211   0.6666667
3212  -7.3333333
3213   4.6666667
3214   0.0000000
3215  -6.6666667
3216  -0.6666667
3217  -6.0000000
3218   1.0000000
3219   1.6666667
3220  -3.0000000
3221   2.0000000
3222  -1.6666667
3223  -0.6666667
3224   7.0000000
3225   1.0000000
3226   0.3333333
3227   4.0000000
3228   1.0000000
3229   3.0000000
3230  -6.0000000
3231   4.0000000
3232  -5.0000000
3233  -0.3333333
3234   1.3333333
3235   0.0000000
3236  -4.3333333
3237   0.0000000
3238   1.0000000
3239  11.0000000
3240   5.6666667
3241  -6.3333333
3242   5.3333333
3243  -1.6666667
3244  -1.0000000
3245  -1.6666667
3246   1.3333333
3247  -3.6666667
3248  -9.0000000
3249  -7.3333333
3250   0.6666667
3251  -2.3333333
3252   6.3333333
3253  -4.6666667
3254   2.3333333
3255  -9.6666667
3256  -5.0000000
3257   4.0000000
3258  -0.6666667
3259  -3.6666667
3260  -5.6666667
3261  -6.6666667
3262   2.6666667
3263   6.0000000
3264   0.6666667
3265   2.0000000
3266   1.0000000
3267  -4.0000000
3268   5.3333333
3269  -1.3333333
3270   0.0000000
3271 -11.3333333
3272   6.6666667
3273  -4.3333333
3274  -3.0000000
3275  -4.0000000
3276  -4.0000000
3277  -6.0000000
3278   0.0000000
3279   3.6666667
3280   4.3333333
3281  -4.3333333
3282  -1.6666667
3283  -3.3333333
3284  -7.0000000
3285   4.0000000
3286  -8.6666667
3287  -1.0000000
3288  -1.6666667
3289   1.0000000
3290   0.3333333
3291  -6.0000000
3292  -6.3333333
3293   0.0000000
3294  -3.6666667
3295   0.3333333
3296   2.0000000
3297   7.0000000
3298  -6.3333333
3299   1.6666667
3300   3.6666667
3301   0.0000000
3302   3.0000000
3303   2.3333333
3304   7.0000000
3305  -4.0000000
3306  -2.0000000
3307  -1.0000000
3308  -1.3333333
3309   0.0000000
3310  -3.6666667
3311   1.6666667
3312   3.3333333
3313   4.6666667
3314  -3.6666667
3315  -0.6666667
3316   0.0000000
3317  -2.6666667
3318  -0.3333333
3319   6.3333333
3320   0.3333333
3321   2.6666667
3322   0.0000000
3323   3.0000000
3324   4.0000000
3325  -2.6666667
3326   6.0000000
3327  -3.0000000
3328   6.6666667
3329   6.0000000
3330   2.6666667
3331   3.3333333
3332   6.3333333
3333   0.0000000
3334   4.3333333
3335   2.6666667
3336   5.3333333
3337   2.3333333
3338   5.0000000
3339   4.0000000
3340   2.6666667
3341  -7.3333333
3342   3.3333333
3343  -3.3333333
3344   5.0000000
3345   0.6666667
3346  -2.3333333
3347   1.6666667
3348  -3.3333333
3349  -4.6666667
3350  -5.3333333
3351  -6.0000000
3352   8.0000000
3353   0.6666667
3354   3.3333333
3355  -1.3333333
3356   7.3333333
3357  -3.0000000
3358  -3.6666667
3359  -5.3333333
3360  -0.6666667
3361   3.3333333
3362   2.0000000
3363  -1.6666667
3364   6.0000000
3365  -2.0000000
3366   6.6666667
3367   1.3333333
3368  -5.6666667
3369  -3.0000000
3370  -2.0000000
3371   0.3333333
3372  -0.3333333
3373   2.6666667
3374  -2.3333333
3375  -7.0000000
3376  -4.6666667
3377  -2.6666667
3378  -6.0000000
3379  -9.0000000
3380   0.6666667
3381  -0.3333333
3382   5.3333333
3383  -1.6666667
3384   1.0000000
3385   0.6666667
3386  -8.0000000
3387  -2.6666667
3388   5.3333333
3389   3.6666667
3390  -5.6666667
3391  -1.6666667
3392  -9.0000000
3393  -4.6666667
3394   3.3333333
3395  -1.0000000
3396  -1.3333333
3397  -4.3333333
3398   9.0000000
3399  -6.0000000
3400  -4.6666667
3401   0.6666667
3402   1.0000000
3403   5.6666667
3404   2.0000000
3405   1.0000000
3406  -4.0000000
3407   4.6666667
3408  -3.3333333
3409   0.0000000
3410   2.3333333
3411  -0.6666667
3412 -10.6666667
3413   4.3333333
3414   3.3333333
3415  -1.3333333
3416  -1.0000000
3417  -9.0000000
3418   1.6666667
3419   3.6666667
3420   2.6666667
3421  -3.3333333
3422   1.0000000
3423   1.6666667
3424   0.0000000
3425  -3.6666667
3426  -4.0000000
3427   0.0000000
3428  -3.3333333
3429   4.0000000
3430   2.0000000
3431   5.3333333
3432  -5.6666667
3433   9.0000000
3434   4.6666667
3435  -2.3333333
3436  -4.3333333
3437  -8.3333333
3438  -1.0000000
3439  -1.3333333
3440   8.6666667
3441  -1.3333333
3442  -0.3333333
3443  -2.6666667
3444  10.0000000
3445   2.0000000
3446   5.0000000
3447  -1.3333333
3448   2.6666667
3449  -2.6666667
3450   0.6666667
3451   9.3333333
3452   3.3333333
3453   5.6666667
3454  -0.3333333
3455  -4.3333333
3456   0.0000000
3457  -3.0000000
3458   2.0000000
3459   1.6666667
3460   3.6666667
3461  -6.0000000
3462   8.0000000
3463   7.3333333
3464   3.3333333
3465  -5.0000000
3466   2.3333333
3467   1.6666667
3468  -6.0000000
3469   4.6666667
3470   2.3333333
3471  -3.0000000
3472   6.3333333
3473   1.3333333
3474  -3.6666667
3475  -4.6666667
3476  -1.0000000
3477  -1.0000000
3478  -1.6666667
3479   4.3333333
3480  -9.6666667
3481   1.6666667
3482   0.0000000
3483   0.3333333
3484  -1.3333333
3485  -1.3333333
3486  -4.6666667
3487  -5.6666667
3488   5.0000000
3489  -1.6666667
3490  -3.6666667
3491  -6.3333333
3492  -6.0000000
3493  -0.6666667
3494  -1.6666667
3495   0.0000000
3496  -1.3333333
3497  -7.6666667
3498  -5.0000000
3499   5.3333333
3500   6.3333333
3501  -1.0000000
3502 -10.3333333
3503   0.0000000
3504   1.3333333
3505   4.3333333
3506   0.3333333
3507   1.6666667
3508  -0.3333333
3509  -4.6666667
3510  -2.3333333
3511  -5.0000000
3512   5.3333333
3513   0.0000000
3514  -5.3333333
3515   4.0000000
3516  -0.6666667
3517  -1.6666667
3518   1.6666667
3519   6.6666667
3520   3.6666667
3521   0.0000000
3522   6.6666667
3523  -3.0000000
3524  -2.6666667
3525   1.6666667
3526   1.0000000
3527  -2.0000000
3528  -2.3333333
3529   3.3333333
3530   5.6666667
3531   2.3333333
3532   3.0000000
3533  -8.3333333
3534  -1.3333333
3535   2.3333333
3536   2.3333333
3537  -2.6666667
3538   7.0000000
3539  -1.6666667
3540   2.6666667
3541  -1.3333333
3542   6.3333333
3543  -6.0000000
3544   8.6666667
3545  -8.3333333
3546  -3.6666667
3547  -5.0000000
3548  -2.0000000
3549   1.6666667
3550  -7.0000000
3551   2.0000000
3552   4.6666667
3553  -1.3333333
3554  -8.0000000
3555  -5.3333333
3556   0.6666667
3557  -6.0000000
3558   4.0000000
3559   0.0000000
3560  -3.3333333
3561   6.6666667
3562  -2.6666667
3563  -0.3333333
3564   3.0000000
3565   0.3333333
3566   4.0000000
3567  11.6666667
3568   4.6666667
3569   8.0000000
3570   7.3333333
3571  -7.6666667
3572   5.6666667
3573  -3.3333333
3574  -1.0000000
3575   5.0000000
3576   4.6666667
3577   6.0000000
3578  -2.3333333
3579   1.6666667
3580   1.6666667
3581  -2.6666667
3582   2.0000000
3583   2.6666667
3584  -4.0000000
3585   2.6666667
3586  -3.3333333
3587  -7.6666667
3588  -5.3333333
3589   3.6666667
3590   4.0000000
3591   2.3333333
3592  -3.3333333
3593   0.3333333
3594  -2.6666667
3595   5.0000000
3596  -5.0000000
3597  -1.0000000
3598   4.0000000
3599   4.3333333
3600  -3.3333333
3601   1.6666667
3602   5.6666667
3603   0.6666667
3604   3.6666667
3605   3.3333333
3606   4.0000000
3607   0.3333333
3608   0.0000000
3609  -3.0000000
3610  -1.6666667
3611  -3.3333333
3612   8.6666667
3613   4.3333333
3614   5.0000000
3615   2.6666667
3616  -1.6666667
3617  -3.6666667
3618  -4.0000000
3619   3.0000000
3620  -9.6666667
3621   3.0000000
3622   0.6666667
3623  -2.3333333
3624  -4.6666667
3625  -0.3333333
3626   1.3333333
3627  -5.6666667
3628  -6.6666667
3629   2.0000000
3630  -1.3333333
3631  -2.0000000
3632   3.3333333
3633   7.3333333
3634   1.6666667
3635   2.0000000
3636  -7.3333333
3637   2.3333333
3638  -2.3333333
3639  -3.6666667
3640   3.6666667
3641   9.6666667
3642  -1.6666667
3643   2.6666667
3644  -7.6666667
3645  -2.3333333
3646   2.6666667
3647  -7.6666667
3648  -7.6666667
3649   5.6666667
3650   4.3333333
3651   1.0000000
3652   0.6666667
3653   3.3333333
3654  -6.3333333
3655   1.0000000
3656  -7.6666667
3657   5.3333333
3658  -3.0000000
3659   2.0000000
3660   1.3333333
3661  -0.6666667
3662  -4.6666667
3663   5.0000000
3664  -2.3333333
3665   2.6666667
3666   1.0000000
3667   4.0000000
3668  -2.0000000
3669   2.6666667
3670  -0.3333333
3671   2.6666667
3672  -1.6666667
3673   1.6666667
3674   3.6666667
3675  -5.6666667
3676  -3.0000000
3677  -0.6666667
3678   1.3333333
3679   0.3333333
3680  -6.3333333
3681  -0.3333333
3682  -4.6666667
3683  -2.0000000
3684  -3.6666667
3685  -1.3333333
3686   2.3333333
3687   1.3333333
3688  -2.3333333
3689   1.0000000
3690  -2.3333333
3691  -3.0000000
3692  -3.6666667
3693   8.6666667
3694  -0.3333333
3695   4.3333333
3696   3.3333333
3697   1.0000000
3698   6.6666667
3699   7.3333333
3700  -4.3333333
3701  -2.0000000
3702  -3.3333333
3703   3.6666667
3704   5.0000000
3705  -6.3333333
3706  -2.3333333
3707  -4.6666667
3708  -2.3333333
3709   4.6666667
3710   7.0000000
3711   2.0000000
3712   6.6666667
3713  -2.0000000
3714   5.6666667
3715   0.3333333
3716  -1.6666667
3717  -3.3333333
3718   0.3333333
3719  -3.0000000
3720   2.6666667
3721   4.3333333
3722   3.0000000
3723   4.6666667
3724  -9.6666667
3725   0.6666667
3726  -3.6666667
3727   1.6666667
3728  -4.6666667
3729   7.6666667
3730   4.3333333
3731 -13.6666667
3732  -6.6666667
3733   3.3333333
3734   3.3333333
3735  11.0000000
3736   1.3333333
3737   3.0000000
3738  -2.6666667
3739   3.6666667
3740   1.6666667
3741   1.6666667
3742  -3.3333333
3743   4.0000000
3744   6.3333333
3745  -6.6666667
3746   3.3333333
3747  -3.0000000
3748   5.0000000
3749   5.0000000
3750  -0.3333333
3751   7.3333333
3752  -4.0000000
3753   1.6666667
3754  -3.3333333
3755  -4.0000000
3756   1.3333333
3757  -9.3333333
3758  -8.0000000
3759   6.3333333
3760   3.6666667
3761   3.6666667
3762   6.6666667
3763   0.0000000
3764  -6.3333333
3765  -4.6666667
3766   0.0000000
3767   6.0000000
3768   4.3333333
3769   3.0000000
3770   6.0000000
3771  -1.3333333
3772  -3.0000000
3773   3.6666667
3774   2.0000000
3775   3.3333333
3776   4.0000000
3777   1.6666667
3778  -4.6666667
3779   3.0000000
3780   3.3333333
3781   5.3333333
3782  -4.6666667
3783  11.6666667
3784   6.0000000
3785   6.0000000
3786 -10.0000000
3787   2.3333333
3788 -11.3333333
3789  -0.6666667
3790   6.6666667
3791   1.3333333
3792   2.6666667
3793  -4.6666667
3794   4.6666667
3795  -1.6666667
3796   0.6666667
3797   6.0000000
3798  -2.6666667
3799   6.0000000
3800   3.6666667
3801   6.3333333
3802  -6.6666667
3803  -1.0000000
3804  -0.6666667
3805   0.6666667
3806   3.0000000
3807   5.3333333
3808   0.0000000
3809  -5.6666667
3810  -1.3333333
3811  -2.6666667
3812   5.0000000
3813   1.3333333
3814   0.0000000
3815  -2.6666667
3816  -6.3333333
3817  -5.6666667
3818   3.0000000
3819   6.3333333
3820  -2.0000000
3821   1.0000000
3822  -0.6666667
3823   4.0000000
3824  -3.6666667
3825   2.6666667
3826   6.6666667
3827  -5.0000000
3828   6.3333333
3829   1.3333333
3830  -8.3333333
3831   5.0000000
3832  -1.0000000
3833  -0.6666667
3834   1.0000000
3835  -1.6666667
3836  -0.6666667
3837  -1.6666667
3838   2.0000000
3839   7.6666667
3840   3.3333333
3841  -3.6666667
3842   4.3333333
3843   6.3333333
3844  -5.0000000
3845   1.3333333
3846  -6.3333333
3847   6.6666667
3848  -6.0000000
3849  -2.6666667
3850  -4.3333333
3851   1.6666667
3852  -2.3333333
3853  -8.6666667
3854   4.6666667
3855   0.6666667
3856  -4.0000000
3857   0.3333333
3858   4.6666667
3859   0.0000000
3860   8.3333333
3861  -1.3333333
3862  -8.0000000
3863   1.6666667
3864  10.3333333
3865 -10.3333333
3866   3.0000000
3867   1.0000000
3868  -0.6666667
3869   4.6666667
3870   3.6666667
3871   3.0000000
3872  -1.6666667
3873  -2.3333333
3874   1.3333333
3875  -6.0000000
3876  -7.3333333
3877   8.0000000
3878  -3.3333333
3879  -4.3333333
3880   2.3333333
3881  -6.0000000
3882  -2.3333333
3883   4.3333333
3884   2.0000000
3885  -3.6666667
3886  -2.3333333
3887  -3.6666667
3888  -1.6666667
3889   8.6666667
3890   0.6666667
3891   1.3333333
3892  -6.3333333
3893   7.0000000
3894   4.3333333
3895  -4.6666667
3896  -2.3333333
3897  10.0000000
3898  -1.3333333
3899  -6.3333333
3900  -1.3333333
3901   3.6666667
3902  -2.6666667
3903   8.0000000
3904  -2.0000000
3905   2.0000000
3906  -0.3333333
3907   4.3333333
3908  10.6666667
3909  -0.3333333
3910  -4.3333333
3911   5.0000000
3912  -8.0000000
3913   3.6666667
3914  -1.3333333
3915   6.3333333
3916   6.3333333
3917 -11.0000000
3918   6.0000000
3919   1.6666667
3920   6.0000000
3921  -4.6666667
3922  -3.0000000
3923  -1.6666667
3924  -1.6666667
3925   3.3333333
3926 -12.0000000
3927  -0.6666667
3928   2.0000000
3929  -3.0000000
3930  -5.3333333
3931  -6.6666667
3932   5.6666667
3933  -2.6666667
3934  -1.3333333
3935   0.3333333
3936   7.6666667
3937   6.0000000
3938  -2.6666667
3939  -7.3333333
3940  -3.3333333
3941  -7.6666667
3942  -3.6666667
3943  -1.6666667
3944   6.0000000
3945   2.0000000
3946   3.0000000
3947   5.6666667
3948   1.0000000
3949  10.6666667
3950   1.3333333
3951   0.6666667
3952  -3.6666667
3953  -6.6666667
3954  -1.6666667
3955  -4.3333333
3956   6.0000000
3957   1.3333333
3958   5.0000000
3959   3.0000000
3960  -7.3333333
3961   0.6666667
3962   5.6666667
3963   5.0000000
3964   1.3333333
3965  -6.3333333
3966  -2.6666667
3967  -2.0000000
3968  -5.3333333
3969  -2.6666667
3970   5.6666667
3971  -0.6666667
3972   1.3333333
3973  -0.6666667
3974  -5.0000000
3975   2.6666667
3976  -6.0000000
3977   0.6666667
3978   2.0000000
3979   1.3333333
3980  10.0000000
3981  -1.3333333
3982   6.6666667
3983   0.3333333
3984   7.3333333
3985  -3.3333333
3986  -3.3333333
3987  -1.3333333
3988   2.3333333
3989  11.3333333
3990   6.6666667
3991  -0.6666667
3992   0.3333333
3993  -5.6666667
3994   1.0000000
3995  -0.3333333
3996   0.6666667
3997   0.3333333
3998  -6.3333333
3999   1.6666667
4000   8.3333333
4001   3.3333333
4002   8.6666667
4003  -3.0000000
4004   5.3333333
4005  -3.3333333
4006   6.6666667
4007  -1.3333333
4008   7.0000000
4009  -8.6666667
4010  -1.3333333
4011  -2.6666667
4012   4.6666667
4013  -3.3333333
4014   3.3333333
4015   0.6666667
4016   5.3333333
4017  -5.0000000
4018   5.0000000
4019  -4.3333333
4020   2.3333333
4021  -7.3333333
4022   0.0000000
4023  -6.6666667
4024  -7.0000000
4025  -7.0000000
4026  -2.6666667
4027  -0.3333333
4028  -5.3333333
4029   7.6666667
4030   0.0000000
4031  -5.0000000
4032  -7.6666667
4033  -8.6666667
4034  -4.6666667
4035  -1.3333333
4036   4.6666667
4037   4.0000000
4038  -2.0000000
4039 -11.0000000
4040   1.6666667
4041   1.0000000
4042  -1.3333333
4043   2.0000000
4044  -4.6666667
4045  -0.6666667
4046  -1.6666667
4047   0.3333333
4048   0.6666667
4049   2.3333333
4050   0.3333333
4051   5.3333333
4052  -3.6666667
4053   1.0000000
4054  -6.6666667
4055   3.0000000
4056  -7.0000000
4057  -3.6666667
4058   5.6666667
4059  -2.0000000
4060   7.6666667
4061  -2.0000000
4062  -2.0000000
4063  -7.3333333
4064  -4.0000000
4065   1.3333333
4066  -3.0000000
4067  -5.0000000
4068  -3.6666667
4069  -3.6666667
4070   2.0000000
4071  -1.0000000
4072  -1.6666667
4073  13.3333333
4074  -2.0000000
4075   2.3333333
4076  -6.3333333
4077   1.3333333
4078   3.6666667
4079  -0.3333333
4080  -6.6666667
4081  -0.6666667
4082   6.3333333
4083   2.6666667
4084   8.0000000
4085  -3.0000000
4086   4.0000000
4087  -2.0000000
4088   5.0000000
4089   8.0000000
4090   3.6666667
4091  -7.6666667
4092   0.3333333
4093  -4.0000000
4094   1.6666667
4095  -0.6666667
4096   6.3333333
4097  -5.6666667
4098   0.0000000
4099  -6.6666667
4100  -0.6666667
4101  -3.6666667
4102   3.0000000
4103   1.0000000
4104   6.6666667
4105  -2.6666667
4106  -5.3333333
4107   7.6666667
4108  -4.3333333
4109   6.6666667
4110   1.0000000
4111  -2.6666667
4112   6.0000000
4113   5.6666667
4114   8.3333333
4115   4.6666667
4116  -2.3333333
4117  -8.0000000
4118  -3.3333333
4119   0.6666667
4120   0.0000000
4121   0.0000000
4122  -4.6666667
4123   9.3333333
4124  -2.0000000
4125   4.3333333
4126  -5.0000000
4127  -2.0000000
4128  -3.6666667
4129  -8.0000000
4130  -4.3333333
4131   1.3333333
4132  -7.6666667
4133  -1.3333333
4134   7.3333333
4135  -0.6666667
4136  -2.3333333
4137  12.3333333
4138  -3.0000000
4139  -2.6666667
4140   1.6666667
4141  -3.6666667
4142  -9.3333333
4143   1.6666667
4144   1.3333333
4145  -6.6666667
4146  -3.6666667
4147  -2.3333333
4148   1.6666667
4149   3.6666667
4150   8.6666667
4151   1.0000000
4152   3.6666667
4153  -3.6666667
4154  -2.0000000
4155   4.0000000
4156   0.3333333
4157   2.3333333
4158   7.0000000
4159  -3.3333333
4160  -5.6666667
4161  -6.6666667
4162  -5.6666667
4163   8.0000000
4164   0.3333333
4165   3.3333333
4166   1.0000000
4167   4.0000000
4168  -1.0000000
4169   6.0000000
4170  -1.3333333
4171   6.6666667
4172   0.6666667
4173  -3.3333333
4174  -0.6666667
4175  -2.6666667
4176  -4.6666667
4177  -8.3333333
4178   3.6666667
4179   3.6666667
4180  -1.6666667
4181  10.0000000
4182  -4.3333333
4183   2.0000000
4184  -0.6666667
4185  -1.0000000
4186  -6.0000000
4187  -0.6666667
4188   1.3333333
4189   1.6666667
4190   2.6666667
4191  -6.0000000
4192  -2.6666667
4193  -3.3333333
4194   5.6666667
4195   0.3333333
4196  -4.3333333
4197   7.6666667
4198   6.0000000
4199   3.6666667
4200  -3.0000000
4201   0.6666667
4202  11.3333333
4203  -1.6666667
4204  -7.3333333
4205  -6.3333333
4206   1.6666667
4207   2.6666667
4208  -0.3333333
4209  -3.6666667
4210  -1.3333333
4211   1.3333333
4212   4.6666667
4213  -5.6666667
4214  -3.0000000
4215   2.6666667
4216   3.0000000
4217   9.6666667
4218   0.3333333
4219  -2.0000000
4220  -2.3333333
4221  -9.6666667
4222  -2.6666667
4223   3.0000000
4224   1.0000000
4225   4.0000000
4226  -2.0000000
4227  -1.6666667
4228  -2.6666667
4229  -4.3333333
4230  -4.0000000
4231  10.6666667
4232  -7.6666667
4233   5.0000000
4234   1.0000000
4235   0.3333333
4236   8.0000000
4237  -7.0000000
4238   6.0000000
4239  -4.0000000
4240   0.6666667
4241  -3.3333333
4242  -2.0000000
4243   6.3333333
4244   2.3333333
4245   2.0000000
4246 -11.3333333
4247  -2.3333333
4248  -2.6666667
4249   2.3333333
4250   2.0000000
4251  -0.3333333
4252  -4.3333333
4253   6.6666667
4254  -2.6666667
4255   3.0000000
4256   5.0000000
4257 -12.0000000
4258   3.0000000
4259   7.0000000
4260  -8.3333333
4261   2.0000000
4262  -8.3333333
4263   2.6666667
4264   5.3333333
4265  -7.6666667
4266   2.0000000
4267   2.0000000
4268  -3.6666667
4269  -2.0000000
4270  -8.3333333
4271   2.6666667
4272   4.0000000
4273   1.3333333
4274  -4.6666667
4275  -5.6666667
4276   1.3333333
4277   0.3333333
4278   4.3333333
4279  -1.3333333
4280  -4.0000000
4281  -5.6666667
4282  -2.0000000
4283  -4.6666667
4284   1.3333333
4285   7.6666667
4286   4.3333333
4287  -3.6666667
4288  -2.3333333
4289   1.6666667
4290  -0.3333333
4291   2.6666667
4292  -2.3333333
4293   2.0000000
4294   6.0000000
4295  -4.0000000
4296   7.3333333
4297  -2.0000000
4298   7.3333333
4299  -1.3333333
4300   3.6666667
4301   4.0000000
4302   5.6666667
4303  -7.0000000
4304   8.3333333
4305  -0.6666667
4306   3.0000000
4307   3.3333333
4308   0.3333333
4309  -0.6666667
4310  -1.3333333
4311  -3.3333333
4312   4.0000000
4313   7.3333333
4314  -0.6666667
4315  -0.3333333
4316  -0.6666667
4317   1.0000000
4318   2.3333333
4319  -0.6666667
4320  -3.0000000
4321  -3.0000000
4322   0.3333333
4323   6.6666667
4324   2.0000000
4325  -3.6666667
4326  -5.3333333
4327  -4.0000000
4328   3.6666667
4329   0.0000000
4330  -2.6666667
4331   2.3333333
4332   0.3333333
4333  -4.0000000
4334   2.0000000
4335  -2.6666667
4336   4.6666667
4337   8.3333333
4338   5.0000000
4339   4.0000000
4340  -3.6666667
4341   0.6666667
4342   1.0000000
4343   2.6666667
4344  -2.0000000
4345   4.3333333
4346   4.0000000
4347   2.0000000
4348   2.0000000
4349   5.3333333
4350  -3.0000000
4351  -7.3333333
4352  -2.3333333
4353   3.0000000
4354   0.3333333
4355  -2.6666667
4356   2.0000000
4357  -5.0000000
4358   5.3333333
4359   2.0000000
4360   7.0000000
4361   3.3333333
4362  -0.6666667
4363   2.3333333
4364   4.0000000
4365   4.3333333
4366   0.0000000
4367   3.0000000
4368  13.0000000
4369  -3.3333333
4370  -2.0000000
4371   6.3333333
4372  -5.6666667
4373   1.0000000
4374   1.3333333
4375  -5.0000000
4376  -0.3333333
4377   0.3333333
4378  -1.3333333
4379   8.3333333
4380   3.0000000
4381   5.6666667
4382   2.6666667
4383   5.6666667
4384   2.0000000
4385   4.6666667
4386  -3.3333333
4387  -1.0000000
4388   3.3333333
4389   5.3333333
4390  -5.0000000
4391   5.3333333
4392  -1.0000000
4393  -2.3333333
4394  -4.6666667
4395   5.6666667
4396  -5.0000000
4397  -0.3333333
4398  -4.6666667
4399   5.3333333
4400  -5.0000000
4401   2.0000000
4402   3.6666667
4403   3.0000000
4404  -2.6666667
4405   1.3333333
4406   5.0000000
4407   3.0000000
4408   1.6666667
4409   3.3333333
4410   6.0000000
4411  -5.3333333
4412   4.3333333
4413   2.6666667
4414  -5.0000000
4415  -0.3333333
4416   7.0000000
4417   3.0000000
4418   2.3333333
4419   7.3333333
4420  -2.3333333
4421   1.6666667
4422  -1.3333333
4423  -8.6666667
4424   3.0000000
4425   6.0000000
4426   1.0000000
4427   2.0000000
4428  -7.6666667
4429   8.3333333
4430  -2.0000000
4431  -0.6666667
4432  -6.0000000
4433   5.0000000
4434   6.6666667
4435   7.0000000
4436   8.3333333
4437   1.0000000
4438   3.0000000
4439  -1.0000000
4440  -0.3333333
4441  -7.3333333
4442  -9.0000000
4443   7.3333333
4444   6.3333333
4445  -0.6666667
4446   5.0000000
4447   4.3333333
4448  -2.6666667
4449  -6.3333333
4450  -5.3333333
4451  -1.0000000
4452  -1.6666667
4453  -6.3333333
4454  -3.0000000
4455  -0.3333333
4456   4.3333333
4457   2.3333333
4458   5.6666667
4459  -0.6666667
4460   1.6666667
4461  -2.6666667
4462  -0.6666667
4463   0.0000000
4464  -3.0000000
4465   5.0000000
4466 -10.3333333
4467  -4.6666667
4468  -2.0000000
4469   5.0000000
4470  -0.6666667
4471   5.6666667
4472  -3.3333333
4473   1.6666667
4474  -2.0000000
4475  -0.3333333
4476  -4.6666667
4477  -7.0000000
4478   4.0000000
4479   1.0000000
4480  11.0000000
4481   7.3333333
4482  -9.0000000
4483  -5.6666667
4484   3.0000000
4485  -4.6666667
4486  -3.3333333
4487   4.0000000
4488  -3.3333333
4489   0.3333333
4490  -1.3333333
4491   1.0000000
4492   0.0000000
4493   3.0000000
4494  -0.3333333
4495   2.3333333
4496   7.3333333
4497   0.3333333
4498   0.0000000
4499   0.6666667
4500   0.6666667
4501   2.0000000
4502   1.3333333
4503   0.0000000
4504   5.0000000
4505  -1.3333333
4506   4.3333333
4507  -0.6666667
4508   5.0000000
4509  -7.6666667
4510  -4.0000000
4511   1.6666667
4512  -5.6666667
4513   3.6666667
4514   2.0000000
4515   5.3333333
4516   0.6666667
4517   7.3333333
4518   3.3333333
4519   8.0000000
4520   0.6666667
4521   3.0000000
4522  -0.6666667
4523   1.6666667
4524  -3.3333333
4525 -10.3333333
4526   2.3333333
4527  -2.3333333
4528   9.0000000
4529   4.3333333
4530  -9.3333333
4531 -10.0000000
4532  -4.6666667
4533   6.3333333
4534  -1.3333333
4535  -5.0000000
4536   1.0000000
4537   1.0000000
4538  -2.6666667
4539  -6.3333333
4540  15.0000000
4541   1.0000000
4542   5.0000000
4543   3.3333333
4544  -0.3333333
4545   4.3333333
4546  -1.0000000
4547   0.3333333
4548  -3.0000000
4549   0.0000000
4550   3.0000000
4551  -1.3333333
4552   3.0000000
4553  -8.3333333
4554  -1.0000000
4555   2.6666667
4556   0.6666667
4557   4.3333333
4558  -1.6666667
4559  -4.0000000
4560   9.3333333
4561   7.6666667
4562   6.3333333
4563  -9.6666667
4564  -4.3333333
4565   2.3333333
4566   7.6666667
4567  -4.3333333
4568   2.3333333
4569   3.0000000
4570  -1.0000000
4571   1.6666667
4572   1.0000000
4573   5.0000000
4574  -9.0000000
4575   1.3333333
4576   0.3333333
4577  -2.3333333
4578   5.0000000
4579   2.6666667
4580  -7.0000000
4581  -3.0000000
4582  -5.0000000
4583   0.3333333
4584   3.3333333
4585   2.3333333
4586   1.6666667
4587  -7.0000000
4588   2.0000000
4589   6.0000000
4590  -0.3333333
4591   1.0000000
4592  -0.3333333
4593   2.3333333
4594   5.3333333
4595  -5.6666667
4596   0.0000000
4597  -4.3333333
4598   7.3333333
4599  -2.3333333
4600   6.0000000
4601   5.3333333
4602   0.6666667
4603  -3.0000000
4604   6.6666667
4605   0.3333333
4606   2.6666667
4607   0.6666667
4608   2.0000000
4609  -0.6666667
4610   5.3333333
4611   6.0000000
4612   6.0000000
4613   1.0000000
4614  -1.3333333
4615  -1.0000000
4616   4.6666667
4617  -3.6666667
4618  -2.0000000
4619   0.0000000
4620  -3.6666667
4621  -3.0000000
4622  -4.0000000
4623  -3.0000000
4624  -4.3333333
4625  -8.0000000
4626   0.0000000
4627   0.6666667
4628   0.0000000
4629   2.0000000
4630   2.0000000
4631   3.6666667
4632  -4.3333333
4633   0.6666667
4634   4.0000000
4635  -4.0000000
4636  -5.6666667
4637  -0.3333333
4638  11.3333333
4639  -2.0000000
4640   3.6666667
4641  -2.0000000
4642   5.3333333
4643   1.3333333
4644  -3.6666667
4645   6.6666667
4646   7.3333333
4647  -4.0000000
4648  -3.0000000
4649   0.3333333
4650 -11.3333333
4651   0.6666667
4652   6.3333333
4653  -1.3333333
4654   0.3333333
4655  -4.0000000
4656  -8.6666667
4657  -6.0000000
4658   2.3333333
4659   0.3333333
4660  -0.6666667
4661   1.3333333
4662   5.3333333
4663   1.0000000
4664  -2.6666667
4665   2.6666667
4666   7.6666667
4667   6.3333333
4668   2.3333333
4669   0.3333333
4670  -5.0000000
4671   4.0000000
4672   6.6666667
4673   0.3333333
4674   3.3333333
4675  -1.6666667
4676   1.3333333
4677   1.3333333
4678   1.6666667
4679  -2.6666667
4680   1.3333333
4681  -2.0000000
4682   3.3333333
4683   6.3333333
4684  -4.0000000
4685  -9.3333333
4686   3.0000000
4687  -6.3333333
4688   2.3333333
4689  -3.3333333
4690   6.0000000
4691   2.6666667
4692 -12.3333333
4693   5.0000000
4694   3.0000000
4695   4.3333333
4696  -1.6666667
4697  -3.3333333
4698  -1.0000000
4699  -1.6666667
4700   1.6666667
4701  -2.6666667
4702  -0.3333333
4703  -2.3333333
4704  -2.6666667
4705   4.6666667
4706   9.3333333
4707   5.3333333
4708  -4.0000000
4709  -1.3333333
4710  -6.6666667
4711  -3.3333333
4712   0.3333333
4713   7.3333333
4714   2.6666667
4715  -2.6666667
4716  -7.6666667
4717  -1.3333333
4718   2.6666667
4719  -2.3333333
4720  -3.0000000
4721   0.3333333
4722   3.3333333
4723   5.3333333
4724   3.0000000
4725  -3.6666667
4726  -0.6666667
4727   8.3333333
4728  -0.6666667
4729  -5.3333333
4730  -1.3333333
4731   7.0000000
4732  -6.6666667
4733   5.3333333
4734  -6.0000000
4735   2.6666667
4736   4.3333333
4737   1.3333333
4738  -4.0000000
4739  -2.3333333
4740   1.3333333
4741   1.0000000
4742  -0.3333333
4743  -2.6666667
4744   0.6666667
4745   1.3333333
4746  -9.6666667
4747  -0.3333333
4748   1.0000000
4749  -8.6666667
4750   0.6666667
4751  -6.0000000
4752   3.3333333
4753   2.6666667
4754  -6.6666667
4755  -6.6666667
4756   5.0000000
4757  -3.0000000
4758   1.0000000
4759   2.0000000
4760   2.0000000
4761  -3.0000000
4762   3.6666667
4763  -5.3333333
4764   3.3333333
4765  -1.6666667
4766   1.6666667
4767   6.6666667
4768  -4.3333333
4769   0.6666667
4770  -4.6666667
4771  -0.3333333
4772  -2.6666667
4773  -4.3333333
4774  -1.6666667
4775   4.3333333
4776   5.3333333
4777   5.3333333
4778   3.0000000
4779   4.0000000
4780   0.6666667
4781   2.6666667
4782  -2.3333333
4783   5.3333333
4784   1.0000000
4785   5.6666667
4786  -4.0000000
4787  -1.6666667
4788  -3.0000000
4789   4.0000000
4790  -1.6666667
4791  -2.0000000
4792  -1.3333333
4793  -8.3333333
4794   3.0000000
4795  -3.6666667
4796  -0.3333333
4797   0.0000000
4798  -2.0000000
4799  -2.0000000
4800  -5.0000000
4801  10.0000000
4802   1.3333333
4803  -6.6666667
4804   3.6666667
4805  -0.6666667
4806   6.0000000
4807   4.0000000
4808  -1.6666667
4809  -1.3333333
4810  -1.3333333
4811  -5.3333333
4812   3.3333333
4813  -0.6666667
4814  -8.6666667
4815   9.3333333
4816  -8.3333333
4817   4.3333333
4818  -1.0000000
4819  -3.3333333
4820   2.3333333
4821  -7.3333333
4822   3.3333333
4823   1.3333333
4824   0.3333333
4825   5.0000000
4826   1.3333333
4827  -3.3333333
4828  -1.6666667
4829  -4.6666667
4830   6.3333333
4831  -4.3333333
4832   3.0000000
4833  -0.6666667
4834   3.0000000
4835  11.0000000
4836   6.3333333
4837   1.0000000
4838  -2.0000000
4839  -0.3333333
4840   6.6666667
4841   2.3333333
4842   3.0000000
4843  -0.6666667
4844   4.0000000
4845   5.3333333
4846   7.6666667
4847  -2.6666667
4848   6.0000000
4849   0.0000000
4850   6.3333333
4851  -8.0000000
4852  -6.3333333
4853   3.3333333
4854  -5.6666667
4855  -3.0000000
4856  -5.3333333
4857  -0.3333333
4858  -4.0000000
4859  -4.3333333
4860  -2.0000000
4861   8.0000000
4862   1.3333333
4863   2.0000000
4864   3.3333333
4865   2.6666667
4866  -1.3333333
4867   6.3333333
4868  -3.0000000
4869   0.0000000
4870   0.3333333
4871  -5.3333333
4872  -6.3333333
4873  -4.3333333
4874  -3.3333333
4875   0.0000000
4876  -3.6666667
4877   6.6666667
4878   6.0000000
4879   4.6666667
4880  -0.6666667
4881  -2.0000000
4882  -0.3333333
4883  -2.3333333
4884   0.6666667
4885  -6.6666667
4886   5.6666667
4887   5.3333333
4888   6.6666667
4889  -2.3333333
4890  -1.6666667
4891  -8.3333333
4892  -0.3333333
4893  -6.3333333
4894  -1.6666667
4895   3.3333333
4896   7.0000000
4897  -5.3333333
4898  -3.0000000
4899   0.0000000
4900  -9.0000000
4901   2.6666667
4902   7.3333333
4903   0.0000000
4904  -4.3333333
4905  -1.0000000
4906  -0.6666667
4907   1.3333333
4908  -1.6666667
4909   0.3333333
4910   3.6666667
4911   6.0000000
4912  -7.6666667
4913  -4.6666667
4914   0.3333333
4915   0.0000000
4916  -1.6666667
4917  -5.0000000
4918   5.6666667
4919  -1.3333333
4920   3.0000000
4921   0.6666667
4922  -0.6666667
4923   4.0000000
4924   4.6666667
4925   9.6666667
4926   4.0000000
4927  -7.6666667
4928  -2.3333333
4929   0.6666667
4930   1.0000000
4931  -5.6666667
4932  -3.6666667
4933  -2.0000000
4934  -2.3333333
4935  -0.6666667
4936   6.0000000
4937   1.0000000
4938  -2.3333333
4939  -1.6666667
4940   6.6666667
4941  -2.0000000
4942  -0.6666667
4943   6.0000000
4944  -1.3333333
4945   7.3333333
4946  -2.6666667
4947  -4.6666667
4948  -4.6666667
4949   0.3333333
4950  -5.6666667
4951   1.6666667
4952   0.6666667
4953   1.0000000
4954  -7.6666667
4955   3.0000000
4956  -6.6666667
4957  -0.3333333
4958   2.3333333
4959  -4.6666667
4960   0.0000000
4961   4.6666667
4962  -0.6666667
4963  -4.3333333
4964   2.0000000
4965   2.0000000
4966  -2.3333333
4967  -6.3333333
4968  -9.0000000
4969   4.6666667
4970  -4.6666667
4971  -4.3333333
4972   3.6666667
4973   2.6666667
4974   2.0000000
4975   2.3333333
4976   0.0000000
4977  -9.3333333
4978  -2.0000000
4979   7.0000000
4980   9.0000000
4981   3.0000000
4982  -1.3333333
4983  -3.3333333
4984   0.0000000
4985  -4.3333333
4986   0.3333333
4987  -8.3333333
4988  -6.3333333
4989  -8.3333333
4990  -5.6666667
4991   2.6666667
4992  -1.3333333
4993   6.3333333
4994   1.6666667
4995   3.0000000
4996  -1.6666667
4997  -7.0000000
4998   4.0000000
4999   1.6666667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Everytime I run it, the values are different since the data is shuffled.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set graph theme</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="at">new =</span> <span class="fu">theme_classic</span>())</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_tip, <span class="sc">~</span> diffmean, <span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_tip, </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Null Distribution by Permutation"</span>, </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Histogram"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Difference in Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_ecdf</span>(<span class="at">data =</span> null_dist_tip, <span class="sc">~</span> diffmean, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_tip, </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Null Distribution by Permutation"</span>, </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Cumulative Density"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Difference in Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Inference:-</p>
<ul>
<li><p>The <strong>histogram</strong> shows the differences between the two groups (Veg and Non-veg) when the data is shuffled randomly. The red line shows the actual difference that was observed (-2.33).</p></li>
<li><p>Since the red line falls in the middle of the random results,so the difference is not unusual- it could just be due to random chance.</p></li>
<li><p>The <strong>cumulative plot</strong> (the second graph) backs this up. It shows that the observed difference is well within what I’d expect if there was no real difference.</p></li>
</ul>
<p><strong>Conclusion</strong>: There’s no strong evidence that the difference in tips between Veg and Non-veg preferences is meaningful, it could easily be due to chance. I initially thought the tips dataset might be useless because of the lack of significant differences between the groups. However, during class, i realised that even with no significant results, the data can still provide valuable insights into patterns and trends in tipping behavior. So, it’s definitely not useless!</p>
</div>
</div>
<p>sample data<br>
mean<br>
shapiro<br>
t-test<br>
if necessary winc</p>
<p><a href="https://av-quarto.netlify.app/content/courses/analytics/inference/modules/110-twomeans/#observed-and-test-statistic" class="uri">https://av-quarto.netlify.app/content/courses/analytics/inference/modules/110-twomeans/#observed-and-test-statistic</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>